/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7b2c259d-6a32-43b3-b742-69c37d4f82a9

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We proved the main theorem relating the Frobenius action on the roots of the polynomial $f(x) = x^3 - 13x - 13$ modulo $N$ to the values of $c = N^{(13-1)/3} \pmod{13}$. Specifically, we showed that if $c \equiv s_1 \pmod{13}$, then $\alpha^N = \gamma$, and if $c \equiv s_2 \pmod{13}$, then $\alpha^N = \beta$, where $\alpha, \beta, \gamma$ are the roots of $f$ in the splitting field. The proof relies on the explicit Frobenius action on the periods of the cyclotomic field $L = \mathbb{Q}(\zeta_{13})$ and the identification of the roots $\alpha, \beta, \gamma$ with these periods.
-/

/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1702907a-097e-46eb-8341-956c0f47dd23

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have formalized the sketch of the proof for the Frobenius Orientation conjecture in the case q=13.
We defined the cyclotomic field L = Q(ζ_13), the Gaussian periods η_0, η_1, η_2, and the cubic roots α, β, γ.
We verified the cyclic relations for β and γ.
We established the global Galois action on α, showing how σ_N permutes the roots based on N mod 13.
We defined the residue field k_P and the reduction map π.
We proved the Artin symbol property for α: π(σ_N(α)) = π(α)^N.
Finally, we proved the Explicit Frobenius Action theorem, determining the action of the Frobenius automorphism on \bar{α} in terms of \bar{α} for each case of N mod 13.
-/

import Mathlib

namespace Q0013


set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of L, ζ, and the periods, with explicit instances to help the type class inference.
-/
open Polynomial NumberField

def L := CyclotomicField 13 ℚ

instance : Field L := CyclotomicField.instField 13 ℚ
instance : CharZero L := CyclotomicField.instCharZero 13 ℚ
instance : IsCyclotomicExtension {13} ℚ L := CyclotomicField.isCyclotomicExtension 13 ℚ

noncomputable def ζ : L := IsCyclotomicExtension.zeta 13 ℚ L

def η₀ : L := ζ + ζ^5 + ζ^8 + ζ^12
def η₁ : L := ζ^2 + ζ^3 + ζ^10 + ζ^11
def η₂ : L := ζ^4 + ζ^6 + ζ^7 + ζ^9

def α : L := -(η₂ - η₁)
def β : L := -(η₀ - η₂)
def γ : L := -(η₁ - η₀)

/-
The cubic roots α, β, γ satisfy the cyclic relation: 5β = -3α² + 2α + 26.
-/
theorem cyclic_relation_beta : 5 * β = -3 * α^2 + 2 * α + 26 := by
  -- Expand the definitions of α and β, then simplify the right-hand side in terms of the powers of ζ.
  unfold α β
  simp +decide
  ring_nf at *;
  unfold η₀ η₁ η₂;
  -- We know that $ζ$ is a primitive 13th root of unity, so $ζ^{13} = 1$ and $ζ^k ≠ 1$ for $1 ≤ k < 13$.
  have h_primitive : ζ ^ 13 = 1 ∧ ∀ k : ℕ, 1 ≤ k → k < 13 → ζ ^ k ≠ 1 := by
    have h_primitive : IsPrimitiveRoot ζ 13 := by
      convert IsCyclotomicExtension.zeta_spec 13 ℚ L using 1
    generalize_proofs at *; (
    exact ⟨ h_primitive.pow_eq_one, fun k hk₁ hk₂ hk₃ => by have := h_primitive.pow_eq_one_iff_dvd k; interval_cases k <;> simp_all +decide ⟩)
  generalize_proofs at *; (
  grind +ring)

/-
The cubic roots α, β, γ satisfy the cyclic relation: 5γ = 3α² - 7α - 26.
-/
theorem cyclic_relation_gamma : 5 * γ = 3 * α^2 - 7 * α - 26 := by
  simp +decide [ γ, α, β, η₀, η₁, η₂ ];
  -- By definition of $ζ$, we know that $ζ^13 = 1$ and $ζ^k ≠ 1$ for $1 ≤ k < 13$.
  have hζ : ζ ^ 13 = 1 ∧ ∀ k : ℕ, 1 ≤ k → k < 13 → ζ ^ k ≠ 1 := by
    have hζ : IsPrimitiveRoot ζ 13 := by
      convert IsCyclotomicExtension.zeta_spec 13 ℚ L using 1;
    exact ⟨ hζ.pow_eq_one, fun k hk₁ hk₂ => fun hk₃ => by have := hζ.2 k hk₃; interval_cases k <;> contradiction ⟩;
  grind +ring

/-
The 13th cyclotomic polynomial is irreducible over Q.
-/
theorem h_irr : Irreducible (cyclotomic 13 ℚ) := Polynomial.cyclotomic.irreducible_rat (by norm_num)

/-
Checking the signature of autEquivPow to debug the type mismatch.
-/
#check @IsCyclotomicExtension.autEquivPow

/-
Definition of the Galois automorphism σ_u for u ∈ (Z/13Z)ˣ.
-/
noncomputable def sigma (u : (ZMod 13)ˣ) : L ≃ₐ[ℚ] L :=
  (IsCyclotomicExtension.autEquivPow L h_irr).symm u

/-
Global Permutation Theorem (Part 1): If u ≡ 2, 3, 10, 11 (mod 13), then σ_u(α) = β.
-/
theorem global_permutation_beta (u : (ZMod 13)ˣ) (h : (u : ZMod 13) ∈ ({2, 3, 10, 11} : Set (ZMod 13))) :
  sigma u α = β := by
    simp +zetaDelta at *;
    -- We need to express the action of σ_u on α = -(η₂ - η₁) in terms of ζ.
    have h_sigma_u_eta : (sigma u) ζ = ζ ^ (u.val.val : ℕ) := by
      unfold sigma;
      simp +decide [ IsCyclotomicExtension.autEquivPow ];
      erw [ PowerBasis.equivOfMinpoly_apply ];
      erw [ PowerBasis.lift_gen ] ; aesop;
    -- By definition of $η₀$, $η₁$, and $η₂$, we can expand $σ_u(α)$ using the properties of exponents.
    have h_expand : (sigma u) α = -( (ζ ^ (4 * (u.val.val : ℕ)) + ζ ^ (6 * (u.val.val : ℕ)) + ζ ^ (7 * (u.val.val : ℕ)) + ζ ^ (9 * (u.val.val : ℕ))) - (ζ ^ (2 * (u.val.val : ℕ)) + ζ ^ (3 * (u.val.val : ℕ)) + ζ ^ (10 * (u.val.val : ℕ)) + ζ ^ (11 * (u.val.val : ℕ))) ) := by
      unfold α;
      unfold η₂ η₁; norm_num [ h_sigma_u_eta, pow_mul ] ;
      ring;
    -- We'll use that ζ is a primitive 13th root of unity to simplify the exponents modulo 13.
    have h_exp_mod : ∀ (n : ℕ), ζ ^ n = ζ ^ (n % 13) := by
      have h_exp_mod : ζ ^ 13 = 1 := by
        exact IsCyclotomicExtension.zeta_pow _ _ _;
      exact fun n => by rw [ ← Nat.mod_add_div n 13, pow_add, pow_mul ] ; aesop;
    rcases h with ( h | h | h | h ) <;> simp +decide [ h, h_expand, h_exp_mod ];
    · unfold β; ring;
      unfold η₀ η₂; ring!;
      norm_num [ ZMod.val ] ; ring!;
    · unfold β; norm_num [ ZMod.val ] ; ring;
      unfold η₀ η₂; ring;
    · unfold β; norm_num [ ZMod.val ] ; ring;
      unfold η₀ η₂; ring;
    · unfold β; ring;
      unfold η₀ η₂; norm_num [ ZMod.val ] ; ring;

/-
Global Permutation Theorem (Part 2): If u ≡ 4, 6, 7, 9 (mod 13), then σ_u(α) = γ.
-/
theorem global_permutation_gamma (u : (ZMod 13)ˣ) (h : (u : ZMod 13) ∈ ({4, 6, 7, 9} : Set (ZMod 13))) :
  sigma u α = γ := by
    unfold sigma α γ;
    -- Let's simplify the expression using the definitions of η₀, η₁, and η₂.
    simp [η₀, η₁, η₂];
    erw [ PowerBasis.equivOfMinpoly_apply ] ; ring;
    erw [ PowerBasis.lift_gen ] ; ring!;
    fin_cases u <;> simp +decide at h ⊢;
    · simp +decide [ ZMod.val ] ; ring!;
      -- Since $\zeta$ is a primitive 13th root of unity, we have $\zeta^{13} = 1$.
      have h_zeta_13 : IsCyclotomicExtension.zeta 13 ℚ L ^ 13 = 1 := by
        exact IsCyclotomicExtension.zeta_pow 13 ℚ L;
      grind +ring;
    · simp +decide [ ZMod.val ] ; ring!;
      -- Since ζ is a primitive 13th root of unity, we have ζ^13 = 1.
      have h_zeta_13 : IsCyclotomicExtension.zeta 13 ℚ L ^ 13 = 1 := by
        exact IsCyclotomicExtension.zeta_pow 13 ℚ L;
      grind +ring;
    · simp +decide [ ZMod.val ] ; ring!;
      -- Since $\zeta$ is a primitive 13th root of unity, we have $\zeta^{13} = 1$.
      have h_zeta_13 : IsCyclotomicExtension.zeta 13 ℚ L ^ 13 = 1 := by
        exact IsCyclotomicExtension.zeta_pow 13 ℚ L;
      grind;
    · simp +decide [ ZMod.val ] ; ring!;
      -- Since $\zeta$ is a primitive 13th root of unity, we have $\zeta^{13} = 1$.
      have h_zeta_13 : (IsCyclotomicExtension.zeta 13 ℚ L) ^ 13 = 1 := by
        exact IsCyclotomicExtension.zeta_pow 13 ℚ L;
      grind +ring

/-
We prove that ζ, α, β, γ are algebraic integers and define them as elements of the ring of integers O_L.
-/
theorem zeta_mem_O : IsIntegral ℤ ζ := by
  -- Since $\zeta$ is a root of unity, it satisfies the polynomial $x^{13} - 1 = 0$, which is monic and has integer coefficients.
  use Polynomial.X ^ 13 - 1;
  simp +zetaDelta at *;
  exact ⟨ Polynomial.monic_X_pow_sub_C _ ( by decide ), sub_eq_zero.mpr <| by simpa using IsCyclotomicExtension.zeta_pow 13 ℚ L ⟩

theorem alpha_mem_O : IsIntegral ℤ α := by
  -- Since ζ is a root of unity, ζ is integral over ℤ.
  have hζ_integral : IsIntegral ℤ ζ := by
    -- Since $\zeta$ is a root of unity, it satisfies the polynomial $x^{13} - 1 = 0$, which is monic and has integer coefficients.
    use Polynomial.X ^ 13 - 1;
    simp +zetaDelta at *;
    exact ⟨ Polynomial.monic_X_pow_sub_C _ ( by decide ), sub_eq_zero.mpr <| by simpa using IsCyclotomicExtension.zeta_pow 13 ℚ L ⟩;
  apply_rules [ IsIntegral.neg, IsIntegral.add, IsIntegral.sub, IsIntegral.pow, hζ_integral ]

theorem beta_mem_O : IsIntegral ℤ β := by
  -- Since ζ is a root of unity, it is integral over ℤ.
  have hζ_integral : IsIntegral ℤ ζ := by
    -- Since $\zeta$ is a root of unity, it satisfies the polynomial $x^{13} - 1 = 0$, which is monic and has integer coefficients.
    use Polynomial.X ^ 13 - 1;
    simp +zetaDelta at *;
    exact ⟨ Polynomial.monic_X_pow_sub_C _ ( by decide ), sub_eq_zero.mpr <| by simpa using IsCyclotomicExtension.zeta_pow 13 ℚ L ⟩;
  refine' IsIntegral.neg _;
  refine' IsIntegral.sub _ _;
  · exact IsIntegral.add ( IsIntegral.add ( IsIntegral.add hζ_integral ( hζ_integral.pow 5 ) ) ( hζ_integral.pow 8 ) ) ( hζ_integral.pow 12 );
  · refine' IsIntegral.add _ _;
    · exact IsIntegral.add ( IsIntegral.add ( hζ_integral.pow 4 ) ( hζ_integral.pow 6 ) ) ( hζ_integral.pow 7 );
    · exact hζ_integral.pow 9

theorem gamma_mem_O : IsIntegral ℤ γ := by
  -- Since ζ is a root of the monic polynomial x^13 - 1 with integer coefficients, ζ is an algebraic integer.
  have h_zeta_int : IsIntegral ℤ ζ := by
    -- Since $\zeta$ is a root of unity, it satisfies the polynomial $x^{13} - 1 = 0$, which is monic and has integer coefficients.
    use Polynomial.X ^ 13 - 1;
    simp +zetaDelta at *;
    exact ⟨ Polynomial.monic_X_pow_sub_C _ ( by decide ), sub_eq_zero.mpr <| by simpa using IsCyclotomicExtension.zeta_pow 13 ℚ L ⟩;
  have h_eta_int : IsIntegral ℤ η₀ ∧ IsIntegral ℤ η₁ ∧ IsIntegral ℤ η₂ := by
    exact ⟨ IsIntegral.add ( IsIntegral.add ( IsIntegral.add h_zeta_int ( h_zeta_int.pow _ ) ) ( h_zeta_int.pow _ ) ) ( h_zeta_int.pow _ ), IsIntegral.add ( IsIntegral.add ( IsIntegral.add ( h_zeta_int.pow _ ) ( h_zeta_int.pow _ ) ) ( h_zeta_int.pow _ ) ) ( h_zeta_int.pow _ ), IsIntegral.add ( IsIntegral.add ( IsIntegral.add ( h_zeta_int.pow _ ) ( h_zeta_int.pow _ ) ) ( h_zeta_int.pow _ ) ) ( h_zeta_int.pow _ ) ⟩;
  exact IsIntegral.neg ( IsIntegral.sub h_eta_int.2.1 h_eta_int.1 )

def alpha_O : 𝓞 L := ⟨α, alpha_mem_O⟩
def beta_O : 𝓞 L := ⟨β, beta_mem_O⟩
def gamma_O : 𝓞 L := ⟨γ, gamma_mem_O⟩

/-
We prove that N is coprime to 13 and define the corresponding unit in (ZMod 13)ˣ.
-/
theorem coprime_N_13 (N : ℕ) [Fact N.Prime] (hN : N ≠ 13) : Nat.Coprime N 13 := by
  exact ( Fact.out : Nat.Prime N ) |> fun h => h.coprime_iff_not_dvd.mpr fun h' => hN <| by have := Nat.le_of_dvd ( by decide ) h'; interval_cases N <;> trivial;

def uN (N : ℕ) [Fact N.Prime] (hN : N ≠ 13) : (ZMod 13)ˣ := ZMod.unitOfCoprime N (coprime_N_13 N hN)

/-
Defining unit_N as the element in (ZMod 13)ˣ corresponding to N.
-/
def unit_N (N : ℕ) [Fact N.Prime] (hN : N ≠ 13) : (ZMod 13)ˣ := ZMod.unitOfCoprime N (coprime_N_13 N hN)

/-
We register the NumberField instances for Q and L, and the DedekindDomain instance for O_L.
-/
instance : NumberField ℚ := inferInstance
instance : NumberField L := CyclotomicField.instNumberField 13 ℚ
instance : IsDedekindDomain (𝓞 L) := inferInstance

/-
We define σ_O as the restriction of the automorphism σ to the ring of integers O_L, as a ring automorphism.
-/
noncomputable def sigma_O (u : (ZMod 13)ˣ) : (𝓞 L) ≃+* (𝓞 L) :=
  NumberField.RingOfIntegers.mapRingEquiv (sigma u)

/-
We define zeta_O as the element ζ in the ring of integers.
We then state the Artin symbol property for ζ: π(σ_N(ζ)) = π(ζ)^N.
-/
def zeta_O : 𝓞 L := ⟨ζ, zeta_mem_O⟩

section ResidueField

variable (N : ℕ) [Fact N.Prime] (hN : N ≠ 13)
variable (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal]

def k_P := (𝓞 L) ⧸ P

noncomputable instance : Field (k_P P) := Ideal.Quotient.field P

def pi : 𝓞 L →+* k_P P := Ideal.Quotient.mk P

theorem artin_symbol_zeta : pi P (sigma_O (unit_N N hN) zeta_O) = (pi P zeta_O) ^ N := by
  -- By definition of σ_O, we have σ_O (unit_N N hN) zeta_O = ζ^(unit_N N hN).
  have h_sigma_zeta : (sigma (unit_N N hN)) (ζ : L) = ζ ^ (unit_N N hN).val.val := by
    rw [sigma];
    simp +decide [ IsCyclotomicExtension.autEquivPow ];
    rw [ PowerBasis.equivOfMinpoly_apply ];
    convert ( IsPrimitiveRoot.powerBasis ℚ ( show IsPrimitiveRoot ( IsCyclotomicExtension.zeta 13 ℚ L ) 13 from ?_ ) ).lift_gen _ _;
    exact?;
  -- Since $ζ$ is a 13th root of unity, we have $ζ^N = ζ^{unit_N N hN}$.
  have h_zeta_pow : (ζ : L) ^ N = (ζ : L) ^ ((unit_N N hN).val.val : ℕ) := by
    -- Since ζ is a 13th root of unity, we have ζ^13 = 1. Therefore, ζ^N = ζ^(N mod 13).
    have h_zeta_pow : (ζ : L) ^ N = (ζ : L) ^ (N % 13) := by
      have h_zeta_pow : (ζ : L) ^ 13 = 1 := by
        convert IsCyclotomicExtension.zeta_pow 13 ℚ L using 1;
      rw [ ← Nat.mod_add_div N 13, pow_add, pow_mul ] ; aesop;
    exact?;
  convert congr_arg ( pi P ) ( show ( sigma_O ( unit_N N hN ) ) zeta_O = zeta_O ^ N from ?_ ) using 1;
  refine' Subtype.ext _;
  convert h_sigma_zeta using 1

end ResidueField

/-
We prove that the automorphism σ_N maps ζ to ζ^N.
-/
lemma sigma_zeta_val (N : ℕ) [Fact N.Prime] (hN : N ≠ 13) :
  sigma (unit_N N hN) ζ = ζ ^ N := by
    -- By definition of `sigma`, we know that `sigma u (ζ) = ζ ^ u`.
    have h_sigma_def : ∀ u : (ZMod 13)ˣ, sigma u ζ = ζ ^ (u.val.val : ℕ) := by
      unfold sigma;
      simp +zetaDelta at *;
      intro u;
      rw [ PowerBasis.equivOfMinpoly_apply ];
      erw [ PowerBasis.lift_gen ];
      rfl;
    -- Since $N)$ is coprime to 13, we have $\zeta^{N \mod 13} = \zeta^N$.
    have h_mod : ζ ^ (N % 13) = ζ ^ N := by
      -- Since ζ is a 13th root of unity, we have ζ^13 = 1.
      have h_zeta_13 : ζ ^ 13 = 1 := by
        exact IsCyclotomicExtension.zeta_pow _ _ _;
      rw [ ← Nat.mod_add_div N 13, pow_add, pow_mul ] ; aesop;
    convert h_mod using 1;
    convert h_sigma_def ( unit_N N hN ) using 1

/-
We prove that σ_O(ζ) = ζ^N.
-/
lemma sigma_O_zeta (N : ℕ) [Fact N.Prime] (hN : N ≠ 13) :
  sigma_O (unit_N N hN) zeta_O = zeta_O ^ N := by
    -- By definition of sigma_O, we have sigma_O (unit_N N hN) zeta_O = sigma (unit_N N hN) ζ.
    have h_sigma_O_zeta : sigma_O (unit_N N hN) zeta_O = sigma (unit_N N hN) ζ := by
      exact?;
    refine' Subtype.ext _;
    convert h_sigma_O_zeta.trans ( sigma_zeta_val N hN ) using 1

/-
We prove that the residue field (O_L)/P has characteristic N.
-/
lemma char_k_P (N : ℕ) [Fact N.Prime] (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal] : CharP ((𝓞 L) ⧸ P) N := by
  -- Since $P$ lies over $(N)$, the image of $N$ in the quotient ring is zero.
  have h_image_zero : (algebraMap ℤ (𝓞 L ⧸ P)) N = 0 := by
    -- Since $P$ lies over $(N)$, the ideal $P$ contains $N$. Therefore, when we take the quotient $R/P$, the element $N$ is congruent to zero modulo $P$.
    have hN_in_P : (N : 𝓞 L) ∈ P := by
      -- Use `liesOver_iff` to identify the comap of `P` with the ideal `(N)` in ℤ,
      -- then translate membership via `Ideal.mem_comap`.
      have h_span_comap :
          Ideal.span { (N : ℤ) } = Ideal.comap (algebraMap ℤ (𝓞 L)) P := by
        simpa using
          ((Ideal.liesOver_iff P (Ideal.span { (N : ℤ) })).mp
              (show P.LiesOver (Ideal.span { (N : ℤ) }) from inferInstance))
      have hN_mem_comap : (N : ℤ) ∈ Ideal.comap (algebraMap ℤ (𝓞 L)) P := by
        have : (N : ℤ) ∈ Ideal.span { (N : ℤ) } := by
          simpa using (Ideal.mem_span_singleton_self (N : ℤ))
        simpa [h_span_comap] using this
      simpa using (Ideal.mem_comap.mp hN_mem_comap)
    erw [ Ideal.Quotient.eq_zero_iff_mem ] ; aesop;
  refine' ⟨ fun n => _ ⟩;
  constructor <;> intro hn <;> simp_all +decide [ ← ZMod.natCast_eq_zero_iff ];
  · erw [ Ideal.Quotient.eq_zero_iff_mem ] at *;
    -- Since $P$ lies over $(N)$, we have that $N \mid n$.
    have h_div : (N : ℤ) ∣ n := by
      have h_div : (Ideal.span {(N : ℤ)}) = (Ideal.comap (algebraMap ℤ (𝓞 L)) P) := by
        simpa using
          ((Ideal.liesOver_iff P (Ideal.span { (N : ℤ) })).mp
              (show P.LiesOver (Ideal.span { (N : ℤ) }) from inferInstance))

      exact Ideal.mem_span_singleton.mp ( h_div.symm ▸ Ideal.mem_comap.mpr hn );
    simpa [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ] using h_div;
  · rw [ ZMod.natCast_eq_zero_iff ] at hn;
    cases hn ; aesop

/-
We express α_O as a polynomial in ζ_O.
-/
lemma alpha_O_eq_poly_zeta : alpha_O = -(zeta_O^4 + zeta_O^6 + zeta_O^7 + zeta_O^9 - (zeta_O^2 + zeta_O^3 + zeta_O^10 + zeta_O^11)) := by
  exact?

/-
We prove the Artin symbol property for α: π(σ_N(α)) = π(α)^N.
We use the expansion of α in terms of ζ, the action of σ_N on ζ, and the properties of the Frobenius map in characteristic N.
-/
theorem artin_symbol_alpha (N : ℕ) [Fact N.Prime] (hN : N ≠ 13) (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal] :
  pi P (sigma_O (unit_N N hN) alpha_O) = (pi P alpha_O) ^ N := by
    -- The Artin symbol property for ζ gives us π(σ_N(ζ)) = π(ζ)^N.
    have h_artin_zeta : (pi P (sigma_O (unit_N N hN) zeta_O)) = (pi P zeta_O) ^ N := by
      exact?;
    -- By definition of $alpha_O$, we have $alpha_O = -(zeta_O^4 + zeta_O^6 + zeta_O^7 + zeta_O^9 - (zeta_O^2 + zeta_O^3 + zeta_O^10 + zeta_O^11))$.
    have h_alpha_def : alpha_O = -(zeta_O^4 + zeta_O^6 + zeta_O^7 + zeta_O^9 - (zeta_O^2 + zeta_O^3 + zeta_O^10 + zeta_O^11)) := by
      exact?;
    simp_all +decide [ pow_mul', ← mul_pow ];
    have h_frobenius : ∀ (x y : (𝓞 L) ⧸ P), (x + y) ^ N = x ^ N + y ^ N := by
      have h_char : CharP ((𝓞 L) ⧸ P) N := by
        exact?;
      exact?;
    simp_all +decide [ add_mul, mul_add, pow_succ ];
    have h_frobenius : ∀ (x y : (𝓞 L) ⧸ P), (x - y) ^ N = x ^ N - y ^ N := by
      intro x y; rw [ sub_eq_add_neg, h_frobenius ] ;
      rw [ neg_pow ] ; simp +decide [ Nat.Prime.even_iff Fact.out, sub_eq_add_neg ] ;
      by_cases h : Even N <;> simp_all +decide [ Nat.Prime.even_iff Fact.out ];
      · grind;
      · rw [ neg_one_pow_eq_pow_mod_two ] ; norm_num [ Nat.Prime.eq_two_or_odd ( Fact.out : Nat.Prime N ) |> Or.resolve_left <| h ];
    simp_all +decide [ ← mul_pow ]

/-
We prove that σ_O(α_O) = β_O under the given congruence condition.
-/
lemma sigma_O_alpha_eq_beta_O (N : ℕ) [Fact N.Prime] (hN : N ≠ 13)
  (h_congr : (unit_N N hN : ZMod 13) ∈ ({2, 3, 10, 11} : Set (ZMod 13))) :
  sigma_O (unit_N N hN) alpha_O = beta_O := by
  apply Subtype.ext
  simp only [sigma_O, alpha_O, beta_O, NumberField.RingOfIntegers.mapRingEquiv_apply, NumberField.RingOfIntegers.mapRingHom_apply, NumberField.RingOfIntegers.map_mk]
  exact global_permutation_beta (unit_N N hN) h_congr

/-
We prove Case 1 of the Explicit Frobenius Action theorem: if $N \equiv 2, 3, 10, 11 \pmod{13}$, then $\bar{\alpha}^N = (-3\bar{\alpha}^2 + 2\bar{\alpha} + 26)/5$.
-/
theorem explicit_frobenius_action_case1 (N : ℕ) [Fact N.Prime] (hN : N ≠ 13) (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal]
  (h_congr : (unit_N N hN : ZMod 13) ∈ ({2, 3, 10, 11} : Set (ZMod 13))) :
  (pi P alpha_O) ^ N = (pi P (-3 * alpha_O^2 + 2 * alpha_O + 26)) * (5 : k_P P)⁻¹ := by
    -- By Lemma~\ref{lem:global_permutation_beta}, we know that $\sigma_N(\alpha) = \beta$.
    have h_sigma_beta : sigma_O (unit_N N hN) alpha_O = beta_O := by
      exact?;
    -- Using the Artin symbol property and the fact that the residue field'reduced versions of the algebraic relations.
    have h_beta_eq : (pi P beta_O) = (pi P (-3 * alpha_O^2 + 2 * alpha_O + 26)) * 5⁻¹ := by
      have h_beta_eq : (pi P beta_O) = (pi P (-3 * alpha_O^2 + 2 * alpha_O + 26)) * (pi P (5 : 𝓞 L))⁻¹ := by
        have h_beta_eq : (pi P beta_O) * (pi P (5 : 𝓞 L)) = (pi P (-3 * alpha_O^2 + 2 * alpha_O + 26)) := by
          have h_beta_eq : beta_O * (5 : 𝓞 L) = -3 * alpha_O^2 + 2 * alpha_O + 26 := by
            have h_beta_eq : (beta_O : L) * 5 = -3 * (alpha_O : L)^2 + 2 * (alpha_O : L) + 26 := by
              convert cyclic_relation_beta using 1;
              exact mul_comm _ _;
            exact Subtype.ext h_beta_eq;
          rw [ ← map_mul, h_beta_eq ];
        rw [ ← h_beta_eq, mul_assoc, mul_inv_cancel₀, mul_one ];
        intro h; have := Ideal.Quotient.eq_zero_iff_mem.mp h; simp_all +decide [ Ideal.mem_span_singleton ] ;
        -- Since $5 \in P$, we have $N \mid 5$.
        have h_div : (N : ℤ) ∣ 5 := by
          have h_div : (5 : ℤ) ∈ Ideal.span {(N : ℤ)} := by
            -- Translate `(5 : 𝓞 L) ∈ P` down to `(5 : ℤ) ∈ (N)` using `liesOver_iff`.
            have h5_mem_comap : (5 : ℤ) ∈ Ideal.comap (algebraMap ℤ (𝓞 L)) P := by
              refine Ideal.mem_comap.mpr ?_
              simpa using this
            have h_span_comap :
                Ideal.span {(N : ℤ)} = Ideal.comap (algebraMap ℤ (𝓞 L)) P := by
              simpa using
                ((Ideal.liesOver_iff P (Ideal.span {(N : ℤ)})).mp
                    (show P.LiesOver (Ideal.span {(N : ℤ)}) from inferInstance))
            exact (h_span_comap.symm ▸ h5_mem_comap)

          exact Ideal.mem_span_singleton.mp h_div;
        norm_cast at h_div; have := Nat.le_of_dvd ( by decide ) h_div; interval_cases N <;> simp +decide at h_div h_congr ⊢;
        · exact Nat.not_prime_one Fact.out;
        · simp_all +decide [ unit_N ];
      convert h_beta_eq using 1;
    rw [ ← h_beta_eq, ← h_sigma_beta, artin_symbol_alpha ]

/-
We prove that σ_O(α_O) = γ_O under the given congruence condition (Case 2).
-/
lemma sigma_O_alpha_eq_gamma_O (N : ℕ) [Fact N.Prime] (hN : N ≠ 13)
  (h_congr : (unit_N N hN : ZMod 13) ∈ ({4, 6, 7, 9} : Set (ZMod 13))) :
  sigma_O (unit_N N hN) alpha_O = gamma_O := by
  apply Subtype.ext
  simp only [sigma_O, alpha_O, gamma_O, NumberField.RingOfIntegers.mapRingEquiv_apply, NumberField.RingOfIntegers.mapRingHom_apply, NumberField.RingOfIntegers.map_mk]
  exact global_permutation_gamma (unit_N N hN) h_congr

/-
We prove Case 2 of the Explicit Frobenius Action theorem: if $N \equiv 4, 6, 7, 9 \pmod{13}$, then $\bar{\alpha}^N = (3\bar{\alpha}^2 - 7\bar{\alpha} - 26)/5$.
-/
theorem explicit_frobenius_action_case2 (N : ℕ) [Fact N.Prime] (hN : N ≠ 13) (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal]
  (h_congr : (unit_N N hN : ZMod 13) ∈ ({4, 6, 7, 9} : Set (ZMod 13))) :
  (pi P alpha_O) ^ N = (pi P (3 * alpha_O^2 - 7 * alpha_O - 26)) * (5 : k_P P)⁻¹ := by
    -- Using the fact that $σ_O(α_O) = γ_O$ in $k_P$, we can rewrite the right-hand side.
    have h_rewrite : (pi P (sigma_O (unit_N N hN) alpha_O)) = (pi P (gamma_O)) := by
      exact congr_arg _ ( sigma_O_alpha_eq_gamma_O N hN h_congr );
    -- Using the fact that $σ_O(α_O) = γ_O$ in $k_P$, we can rewrite the right-hand side of the equation.
    have h_rewrite_rhs : (pi P (gamma_O)) = (pi P (3 * alpha_O ^ 2 - 7 * alpha_O - 26)) * (5 : k_P P)⁻¹ := by
      have h_gamma : (gamma_O : 𝓞 L) * 5 = 3 * alpha_O ^ 2 - 7 * alpha_O - 26 := by
        have h_gamma : (gamma_O : L) * 5 = 3 * alpha_O ^ 2 - 7 * alpha_O - 26 := by
          have h_gamma_eq : (gamma_O : L) = (3 * alpha_O ^ 2 - 7 * alpha_O - 26) / 5 := by
            field_simp;
            convert cyclic_relation_gamma using 1;
            · exact mul_comm _ _;
            · ring!
          rw [ h_gamma_eq, div_mul_cancel₀ _ ( by norm_num ) ];
        exact Subtype.ext h_gamma;
      have h_inv : (pi P (5 : 𝓞 L)) ≠ 0 := by
        -- First, show that `5` is not in the ideal `(N)` of `ℤ`.
        have h5_not_mem : (5 : ℤ) ∉ Ideal.span {(N : ℤ)} := by
          rw [ Ideal.mem_span_singleton ]
          norm_cast
          intro h
          have := Nat.le_of_dvd (by decide) h
          interval_cases N <;> simp_all +decide
          · exact Nat.not_prime_one Fact.out
          · simp_all +decide [ unit_N ]
        -- If `pi P 5 = 0`, then `5 ∈ P`, hence `5 ∈ (N)` by `liesOver_iff`, contradiction.
        intro hzero
        have h5_mem_P : (5 : 𝓞 L) ∈ P := by
          exact Ideal.Quotient.eq_zero_iff_mem.mp hzero
        have h_span_comap :
            Ideal.span {(N : ℤ)} = Ideal.comap (algebraMap ℤ (𝓞 L)) P := by
          simpa using
            ((Ideal.liesOver_iff P (Ideal.span {(N : ℤ)})).mp
                (show P.LiesOver (Ideal.span {(N : ℤ)}) from inferInstance))
        have h5_mem_comap : (5 : ℤ) ∈ Ideal.comap (algebraMap ℤ (𝓞 L)) P := by
          refine Ideal.mem_comap.mpr ?_
          simpa using h5_mem_P
        have h5_mem_span : (5 : ℤ) ∈ Ideal.span {(N : ℤ)} := by
          exact (h_span_comap.symm ▸ h5_mem_comap)
        exact h5_not_mem h5_mem_span

      rw [ ← h_gamma, map_mul ];
      exact?;
    rw [ ← h_rewrite_rhs, ← h_rewrite, artin_symbol_alpha ]

/-
Global Permutation Theorem (Split Case): If u ≡ 1, 5, 8, 12 (mod 13), then σ_u(α) = α.
-/
theorem global_permutation_alpha (u : (ZMod 13)ˣ) (h : (u : ZMod 13) ∈ ({1, 5, 8, 12} : Set (ZMod 13))) :
  sigma u α = α := by
    have h_sigma_zeta : sigma u ζ = ζ ^ (u : ZMod 13).val := by
      have h_sigma_zeta : ∀ (u : (ZMod 13)ˣ), sigma u ζ = ζ ^ (u : ZMod 13).val := by
        intro u
        have h_sigma_zeta : sigma u ζ = ζ ^ (u : ZMod 13).val := by
          have h_sigma_zeta_def : sigma u = (IsCyclotomicExtension.autEquivPow L h_irr).symm u := by
            rfl
          simp +zetaDelta at *;
          rw [ h_sigma_zeta_def, PowerBasis.equivOfMinpoly_apply ];
          erw [ PowerBasis.lift_gen ];
          exact?;
        exact h_sigma_zeta;
      exact h_sigma_zeta u;
    -- By definition of α, we have α = -(η₂ - η₁).
    have h_alpha : α = -(ζ^4 + ζ^6 + ζ^7 + ζ^9 - (ζ^2 + ζ^3 + ζ^10 + ζ^11)) := by
      exact?;
    simp_all +decide [ pow_succ, mul_assoc ];
    -- Since ζ is a primitive 13th root of unity, we have ζ^13 = 1.
    have h_zeta_13 : ζ ^ 13 = 1 := by
      convert IsPrimitiveRoot.pow_eq_one ( IsCyclotomicExtension.zeta_spec 13 ℚ L );
    rcases h with ( rfl | h | h | h ) <;> norm_num [ pow_succ, mul_assoc, h_zeta_13 ];
    · simp +decide [ ZMod.val ];
    · simp_all +decide [ ZMod.val ];
      grind +ring;
    · simp_all +decide [ ZMod.val ];
      grind +ring;
    · simp_all +decide [ ZMod.val ];
      grind

/-
We prove the split case of the Explicit Frobenius Action: if $N \equiv 1, 5, 8, 12 \pmod{13}$, then $\bar{\alpha}^N = \bar{\alpha}$.
-/
theorem explicit_frobenius_action_split (N : ℕ) [Fact N.Prime] (hN : N ≠ 13) (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal]
  (h_congr : (unit_N N hN : ZMod 13) ∈ ({1, 5, 8, 12} : Set (ZMod 13))) :
  (pi P alpha_O) ^ N = pi P alpha_O := by
  rw [← artin_symbol_alpha N hN P]
  have h_global : sigma (unit_N N hN) α = α := global_permutation_alpha (unit_N N hN) h_congr
  have h_sigma_O : sigma_O (unit_N N hN) alpha_O = alpha_O := by
    ext
    simp only [sigma_O, alpha_O, NumberField.RingOfIntegers.mapRingEquiv_apply, NumberField.RingOfIntegers.mapRingHom_apply, NumberField.RingOfIntegers.map_mk]
    exact h_global
  rw [h_sigma_O]

/-
Calculation of s1 in ZMod 13.
-/
lemma s1_value : (↑(-5 - 3 : ℤ) : ZMod 13) * (6 : ZMod 13)⁻¹ = 3 := by
  native_decide +revert

/-
Calculation of s2 in ZMod 13.
-/
lemma s2_value : (↑(5 - 3 : ℤ) : ZMod 13) * (6 : ZMod 13)⁻¹ = 9 := by
  native_decide +revert

/-
Characterization of elements with 4th power equal to 3 in ZMod 13.
-/
lemma N_pow_4_eq_3 (n : ZMod 13) : n^4 = 3 ↔ n ∈ ({2, 3, 10, 11} : Set (ZMod 13)) := by
  decide +revert

/-
Characterization of elements with 4th power equal to 9 in ZMod 13.
-/
lemma N_pow_4_eq_9 (n : ZMod 13) : n^4 = 9 ↔ n ∈ ({4, 6, 7, 9} : Set (ZMod 13)) := by
  native_decide +revert

/-
The sum of the roots alpha, beta, gamma is zero.
-/
lemma sum_roots_zero : α + β + γ = 0 := by
  unfold α β γ; ring;

/-
The cyclic relation for gamma holds in the ring of integers O_L.
-/
lemma cyclic_relation_gamma_O : 5 * gamma_O = 3 * alpha_O^2 - 7 * alpha_O - 26 := by
  exact Subtype.ext <| cyclic_relation_gamma.trans <| by norm_cast;

/-
Identification of beta_bar_expr with pi P gamma_O using the cyclic relation and invertibility of 10.
-/
lemma beta_bar_identification (N : ℕ) [Fact N.Prime] (hN_odd : N % 2 ≠ 0) (hN_q : N ≠ 13) (hN_a : Nat.Coprime 5 N)
  (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal] :
  let alpha_bar := pi P alpha_O
  let beta_bar_expr := (6 * alpha_bar^2 - (14 : k_P P) * alpha_bar - (52 : k_P P)) * (10 : k_P P)⁻¹
  beta_bar_expr = pi P gamma_O := by
    -- Applying the cyclic relation to gamma_O, we get 5 * pi P gamma_O = 3 * alpha_bar^2 - 7 * alpha_bar - 26 in k_P P.
    have h_gamma_O : 5 * (pi P) gamma_O = 3 * ((pi P) alpha_O)^2 - 7 * ((pi P) alpha_O) - 26 := by
      convert congr_arg ( pi P ) ( cyclic_relation_gamma_O ) using 1;
    -- Since $N$ is coprime to $10$, $10$ is invertible in $k_P$.
    have h_inv : (10 : k_P P) ≠ 0 := by
      -- Since $N$ is coprime to $10$, $N$ does not divide $10$, hence $10$ is non-zero in $k_P$.
      have h_not_div : ¬(N : ℤ) ∣ 10 := by
        norm_cast; intro h; have := Nat.le_of_dvd ( by decide ) h; interval_cases N <;> trivial;
      contrapose! h_not_div;
      erw [ Ideal.Quotient.eq_zero_iff_mem ] at h_not_div;
      have := ‹P.LiesOver ( Ideal.span { ( N : ℤ ) } ) ›.1;
      rw [ SetLike.ext_iff ] at this;
      exact Ideal.mem_span_singleton.mp ( this _ |>.2 <| by simpa using h_not_div );
    field_simp;
    linear_combination' -h_gamma_O * 2

/-
Identification of gamma_bar with pi P beta_O.
-/
lemma gamma_bar_identification (N : ℕ) [Fact N.Prime] (hN_odd : N % 2 ≠ 0) (hN_q : N ≠ 13) (hN_a : Nat.Coprime 5 N)
  (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal] :
  let alpha_bar := pi P alpha_O
  let beta_bar := (6 * alpha_bar^2 - (↑(5 + 9) : k_P P) * alpha_bar - (↑(4 * 13) : k_P P)) * (↑(2 * 5) : k_P P)⁻¹
  let gamma_bar := -alpha_bar - beta_bar
  gamma_bar = pi P beta_O := by
    have h_beta_bar_eq_pi_gamma_O : (pi P) gamma_O = ((6 * (pi P) alpha_O^2 - (14 : k_P P) * (pi P) alpha_O - (52 : k_P P)) * (10 : k_P P)⁻¹) := by
      convert beta_bar_identification N hN_odd hN_q hN_a P |> Eq.symm using 1;
    have h_gamma_bar_eq_pi_beta_O : (pi P) beta_O = -(pi P) alpha_O - (pi P) gamma_O := by
      convert congr_arg ( pi P ) ( show beta_O = -alpha_O - gamma_O from ?_ ) using 1;
      have h_gamma_bar_eq_pi_beta_O : (alpha_O : 𝓞 L) + (beta_O : 𝓞 L) + (gamma_O : 𝓞 L) = 0 := by
        exact Subtype.ext <| sum_roots_zero;
      linear_combination' h_gamma_bar_eq_pi_beta_O;
    rw [ h_gamma_bar_eq_pi_beta_O, h_beta_bar_eq_pi_gamma_O ] ; ring

/-
Proof of the first case of the main theorem: if c = s1, then alpha^N = gamma.
-/
lemma main_theorem_case1 (N : ℕ) [Fact N.Prime] (hN_odd : N % 2 ≠ 0) (hN_q : N ≠ 13) (hN_a : Nat.Coprime 5 N)
  (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal]
  (h_irr_N : Irreducible (Polynomial.X^3 - Polynomial.C (13 : ZMod N) * Polynomial.X - Polynomial.C (13 : ZMod N))) :
  let q : ℕ := 13
  let a : ℕ := 5
  let s1 : ZMod 13 := (↑(-5 - 3 : ℤ) : ZMod 13) * (6 : ZMod 13)⁻¹
  let c : ZMod 13 := (N : ZMod 13) ^ ((q - 1) / 3)
  let alpha_bar := pi P alpha_O
  let beta_bar := (6 * alpha_bar^2 - (↑(a + 9) : k_P P) * alpha_bar - (↑(4 * q) : k_P P)) * (↑(2 * a) : k_P P)⁻¹
  let gamma_bar := -alpha_bar - beta_bar
  c = s1 → alpha_bar ^ N = gamma_bar := by
    -- By the properties of the Frobenius map in characteristic N, we have that π(α)^N = π(α^N).
    intro q a s1 c alpha_bar beta_bar gamma_bar hc
    have h_frobenius : (pi P alpha_O) ^ N = (pi P (sigma_O (unit_N N hN_q) alpha_O)) := by
      exact?;
    -- By the properties of the Frobenius map in characteristic N, we have that π(α^N) = π(β).
    have h_frobenius_beta : (pi P (sigma_O (unit_N N hN_q) alpha_O)) = (pi P beta_O) := by
      rw [ sigma_O_alpha_eq_beta_O ];
      have h_congr : (N : ZMod 13) ^ 4 = 3 := by
        convert hc using 1;
        · norm_num +zetaDelta at *;
        · native_decide;
      exact?;
    convert h_frobenius_beta using 1;
    convert gamma_bar_identification N hN_odd hN_q hN_a P using 1;
    norm_num +zetaDelta at *

/-
Proof of the second case of the main theorem: if c = s2, then alpha^N = beta.
-/
lemma main_theorem_case2 (N : ℕ) [Fact N.Prime] (hN_odd : N % 2 ≠ 0) (hN_q : N ≠ 13) (hN_a : Nat.Coprime 5 N)
  (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal]
  (h_irr_N : Irreducible (Polynomial.X^3 - Polynomial.C (13 : ZMod N) * Polynomial.X - Polynomial.C (13 : ZMod N))) :
  let q : ℕ := 13
  let a : ℕ := 5
  let s2 : ZMod 13 := (↑(5 - 3 : ℤ) : ZMod 13) * (6 : ZMod 13)⁻¹
  let c : ZMod 13 := (N : ZMod 13) ^ ((q - 1) / 3)
  let alpha_bar := pi P alpha_O
  let beta_bar := (6 * alpha_bar^2 - (↑(a + 9) : k_P P) * alpha_bar - (↑(4 * q) : k_P P)) * (↑(2 * a) : k_P P)⁻¹
  c = s2 → alpha_bar ^ N = beta_bar := by
    field_simp;
    intro h
    have hc : (unit_N N hN_q : ZMod 13) ∈ ({4, 6, 7, 9} : Set (ZMod 13)) := by
      have h_unit : (N : ZMod 13) ^ 4 = 9 := by
        have h_unit : (↑N ^ 4 : ZMod 13) = (↑(5 - 3) * 6⁻¹ : ZMod 13) := by
          convert h using 1;
        exact h_unit.trans ( by native_decide );
      exact?
    have h_alpha_gamma : (pi P alpha_O) ^ N = (pi P gamma_O) := by
      convert explicit_frobenius_action_case2 N hN_q P hc using 1;
      have h_gamma_O : 5 * gamma_O = 3 * alpha_O^2 - 7 * alpha_O - 26 := by
        convert cyclic_relation_gamma_O using 1;
      rw [ ← h_gamma_O, mul_comm ];
      erw [ map_mul ];
      erw [ show ( 5 : 𝓞 L ) = ( 5 : ℤ ) • 1 from by norm_num, map_zsmul ] ; norm_num;
      have h_inv : (5 : k_P P) ≠ 0 := by
        intro h_zero
        have h_char : CharP (𝓞 L ⧸ P) N := by
          exact?;
        have := CharP.cast_eq_zero_iff ( 𝓞 L ⧸ P ) N 5; simp_all +decide ;
        have := Nat.le_of_dvd ( by decide ) this; interval_cases N <;> trivial;
      rw [ ← mul_assoc, inv_mul_cancel₀ h_inv, one_mul ]
    have h_beta_gamma : (pi P gamma_O) = ((6 * (pi P alpha_O)^2 - (↑(5 + 9) : k_P P) * (pi P alpha_O) - (↑(4 * 13) : k_P P)) * (↑(2 * 5) : k_P P)⁻¹) := by
      convert beta_bar_identification N hN_odd hN_q hN_a P |> Eq.symm using 1 ; ring!;
    rw [h_alpha_gamma, h_beta_gamma];
    ring

/-
The main theorem relating the Frobenius action on alpha to beta and gamma.
-/
theorem main_theorem (N : ℕ) [Fact N.Prime] (hN_odd : N % 2 ≠ 0) (hN_q : N ≠ 13) (hN_a : Nat.Coprime 5 N)
  (P : Ideal (𝓞 L)) [P.IsPrime] [P.LiesOver (Ideal.span { (N : ℤ) })] [P.IsMaximal]
  (h_irr_N : Irreducible (Polynomial.X^3 - Polynomial.C (13 : ZMod N) * Polynomial.X - Polynomial.C (13 : ZMod N))) :
  let q : ℕ := 13
  let a : ℕ := 5
  let s1 : ZMod 13 := (↑(-5 - 3 : ℤ) : ZMod 13) * (6 : ZMod 13)⁻¹
  let s2 : ZMod 13 := (↑(5 - 3 : ℤ) : ZMod 13) * (6 : ZMod 13)⁻¹
  let c : ZMod 13 := (N : ZMod 13) ^ ((q - 1) / 3)
  let alpha_bar := pi P alpha_O
  let beta_bar := (6 * alpha_bar^2 - (↑(a + 9) : k_P P) * alpha_bar - (↑(4 * q) : k_P P)) * (↑(2 * a) : k_P P)⁻¹
  let gamma_bar := -alpha_bar - beta_bar
  (c = s1 → alpha_bar ^ N = gamma_bar) ∧
  (c = s2 → alpha_bar ^ N = beta_bar) := by
    exact ⟨ main_theorem_case1 N hN_odd hN_q hN_a P h_irr_N, main_theorem_case2 N hN_odd hN_q hN_a P h_irr_N ⟩
