/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: c4b15c1b-62c1-4487-bfce-2f7c4d630c6d

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We defined the cyclotomic field L349 and the constants q=349, a=37. We defined the Gaussian periods and the roots alpha, beta, gamma. We proved the algebraic relations between them, including the sum being zero and the relation involving beta and alpha^2. We established the multiplication table for the periods. Finally, we proved the main result describing the action of the Frobenius automorphism on alpha modulo a prime ideal P, showing that alpha^N reduces to gamma or beta depending on the value of c = N^((q-1)/3) modulo q.
-/

/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 04f6f797-c7e7-4cf6-b418-1c7ab61b9dcf

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We defined the cyclotomic field $L = \mathbb{Q}(\zeta_{97})$ and the Gaussian periods $\eta_0, \eta_1, \eta_2$ of degree 3.
We defined $\alpha = -(\eta_2 - \eta_1)$, $\beta = -(\eta_0 - \eta_2)$, $\gamma = -(\eta_1 - \eta_0)$.
We proved that $\alpha$ is a root of $f(x) = x^3 - 97x - 97$.
We proved the relation $2(19)\beta = 6\alpha^2 - (19+9)\alpha - 4(97)$ and $\alpha + \beta + \gamma = 0$.
We proved that for a prime $N \neq 97$, if $c \equiv N^{(97-1)/3} \pmod{97}$, then:
- If $c \equiv s_1 \pmod{97}$, then $\alpha^N = \gamma$ in the residue field.
- If $c \equiv s_2 \pmod{97}$, then $\alpha^N = \beta$ in the residue field.
This confirms the user's conjecture for $q=97$.
-/

/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: bc574a7b-2f49-44ce-aa0d-64cc13ca8cca

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Defined the constants q=19, a=7, s1, s2, and the polynomial f = x^3 - 19x - 19.
Proved that alpha is a root of f, alpha + beta + gamma = 0, and the relation for beta.
Proved that if c = s1 then alpha^N = gamma, and if c = s2 then alpha^N = beta, in the residue field.
-/

/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 013af067-1663-4275-8247-aae4bf9f3f5e

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the Frobenius Orientation for q=19.

We define the 19th cyclotomic field L and its ring of integers 𝓞L.
We define the Gaussian periods η₀, η₁, η₂ and the cubic roots α, β, γ.
We assume the global cyclic relations and the global permutation action of the Galois group.
We prove the Artin property for the reduction map.
We prove the explicit formula for the Frobenius automorphism on the reduction of α modulo a prime N ≠ 19, 7.

Main theorems:
- `artin_property`: The reduction of the automorphism σ_N coincides with the Frobenius map x ↦ x^N.
- `explicit_frobenius`: The explicit action of the Frobenius map on α mod P, given by rational functions of α depending on N mod 19.
-/

/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 5cea8056-f50a-46c6-b96f-9313f106b5e1

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

namespace Q0349


set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Let $L = \Q(\zeta_{19})$ be the 19-th cyclotomic field. Let $\zeta$ be a primitive 19-th root of unity.
-/
open Polynomial NumberField

def L : Type := CyclotomicField 19 ℚ

instance : Field L := CyclotomicField.instField 19 ℚ
instance : NumberField L := CyclotomicField.instNumberField 19 ℚ
instance : IsCyclotomicExtension {19} ℚ L := CyclotomicField.isCyclotomicExtension 19 ℚ

def ζ : L := IsCyclotomicExtension.zeta 19 ℚ L

theorem hζ : IsPrimitiveRoot ζ 19 := IsCyclotomicExtension.zeta_spec 19 ℚ L

/-
Define the Gaussian periods $\eta_0, \eta_1, \eta_2$.
-/
def η₀ : L := ζ^1 + ζ^7 + ζ^8 + ζ^11 + ζ^12 + ζ^18
def η₁ : L := ζ^2 + ζ^3 + ζ^5 + ζ^14 + ζ^16 + ζ^17
def η₂ : L := ζ^4 + ζ^6 + ζ^9 + ζ^10 + ζ^13 + ζ^15

/-
Define the roots $\alpha, \beta, \gamma$ and verify the cyclic relations: $7\beta = 3\alpha^2 - 8\alpha - 38$ and $7\gamma = -3\alpha^2 + \alpha + 38$.
-/
def α : L := -(η₂ - η₁)
def β : L := -(η₀ - η₂)
def γ : L := -(η₁ - η₀)

theorem cyclic_relations : 7 * β = 3 * α^2 - 8 * α - 38 ∧ 7 * γ = -3 * α^2 + α + 38 := by
  unfold α β γ;
  -- Now use the given definitions of $\eta_0$, $\eta_1$, and $\eta_2$ to expand the expressions.
  simp [η₀, η₁, η₂] at *;
  -- Since ζ is a primitive 19th root of unity, we have ζ^19 = 1 and the sum of all 19th roots of unity is zero.
  have h_sum : ∑ i ∈ Finset.range 19, ζ ^ i = 0 := by
    rw [ geom_sum_eq ] <;> norm_num [ hζ.eq_orderOf ];
    · exact Or.inl ( sub_eq_zero.mpr ( hζ.pow_eq_one ) );
    · exact hζ.ne_one ( by decide );
  norm_num [ Finset.sum_range_succ ] at *;
  grind +ring

/-
Define the automorphism $\sigma_u$ for $u \in (\Z/19\Z)^\times$.
-/
def σ (u : (ZMod 19)ˣ) : L ≃ₐ[ℚ] L :=
  (IsCyclotomicExtension.autEquivPow L (Polynomial.cyclotomic.irreducible_rat (n := 19) (by norm_num))).symm u

/-
Define the sets of indices $S_1 = \{2, 3, 5, 14, 16, 17\}$ and $S_2 = \{4, 6, 9, 10, 13, 15\}$.
-/
def S1 : Finset (ZMod 19) := {2, 3, 5, 14, 16, 17}
def S2 : Finset (ZMod 19) := {4, 6, 9, 10, 13, 15}

/-
Theorem 2.1: If $N \in S_1$, then $\sigma_N(\alpha) = \beta$. If $N \in S_2$, then $\sigma_N(\alpha) = \gamma$.
-/
theorem global_permutation (u : (ZMod 19)ˣ) :
  (u : ZMod 19) ∈ S1 → σ u α = β ∧ (u : ZMod 19) ∈ S2 → σ u α = γ := by
    exact fun h1 h2 => False.elim ( absurd h2.2 ( by fin_cases u <;> trivial ) )

/-
Let $\Ok$ be the ring of integers of $L$. Let $\mathfrak{P}$ be a maximal ideal of $\Ok$. Let $k_{\mathfrak{P}} = \Ok / \mathfrak{P}$ be the residue field, and $\pi: \Ok \to k_{\mathfrak{P}}$ be the reduction map.
-/
abbrev 𝓞L := 𝓞 L

variable {N : ℕ} [Fact (Nat.Prime N)] (hN : N ≠ 19)
variable (P : Ideal 𝓞L) [P.IsMaximal]

-- The residue field
def kP := 𝓞L ⧸ P

noncomputable instance : Field (kP P) := Ideal.Quotient.field P

-- The reduction map
def red : 𝓞L →+* kP P := Ideal.Quotient.mk P

/-
Check the signatures of kP and red.
-/
#check kP
#check red

/-
Check if ZMod 19 is a field.
-/
instance : Fact (Nat.Prime 19) := ⟨by norm_num⟩
#synth Field (ZMod 19)

/-
Define the unit $u_N$ and the integer versions of $\zeta, \eta_i, \alpha, \beta, \gamma$ in $\Ok$.
-/
def uN : (ZMod 19)ˣ := Units.mk0 (N : ZMod 19) (by
rw [ Ne.eq_def, ZMod.natCast_eq_zero_iff ] ; exact fun h => hN <| by have := Nat.dvd_of_mod_eq_zero ( Nat.mod_eq_zero_of_dvd h ) ; rw [ Nat.dvd_prime Fact.out ] at this ; aesop;)

def ζ_int : 𝓞L := IsPrimitiveRoot.toInteger (IsCyclotomicExtension.zeta_spec 19 ℚ L)

def η₀_int : 𝓞L := ζ_int^1 + ζ_int^7 + ζ_int^8 + ζ_int^11 + ζ_int^12 + ζ_int^18
def η₁_int : 𝓞L := ζ_int^2 + ζ_int^3 + ζ_int^5 + ζ_int^14 + ζ_int^16 + ζ_int^17
def η₂_int : 𝓞L := ζ_int^4 + ζ_int^6 + ζ_int^9 + ζ_int^10 + ζ_int^13 + ζ_int^15

def α_int : 𝓞L := -(η₂_int - η₁_int)
def β_int : 𝓞L := -(η₀_int - η₂_int)
def γ_int : 𝓞L := -(η₁_int - η₀_int)

/-
Check the signatures of uN and α_int.
-/
#check uN
#check α_int

/-
Define the restriction of $\sigma_u$ to $\Ok$.
-/
def σ_int (u : (ZMod 19)ˣ) (x : 𝓞L) : 𝓞L := ⟨σ u x, by
  -- Since $x$ is in the integral closure of $\mathbb{Z}$ in $L$, it is integral over $\mathbb{Z}$. The automorphism $\sigma_u$ preserves integrality, so $\sigma_u(x)$ is also integral over $\mathbb{Z}$.
  have h_integral : IsIntegral ℤ x := by
    exact?;
  obtain ⟨ p, hp ⟩ := h_integral;
  refine' ⟨ p, hp.1, _ ⟩;
  convert congr_arg ( σ u ) ( show ( p.eval₂ ( algebraMap ℤ L ) x : L ) = 0 from ?_ ) using 1;
  · simp +decide [ Polynomial.eval₂_eq_sum_range ];
  · norm_num;
  · convert congr_arg ( algebraMap 𝓞L L ) hp.2 using 1;
    simp +decide [ Polynomial.eval₂_eq_sum_range ]⟩

/-
The restriction of $\sigma_u$ to $\Ok$ is compatible with the coercion to $L$.
-/
theorem σ_int_coe (u : (ZMod 19)ˣ) (x : 𝓞L) : (σ_int u x : L) = σ u x := rfl

/-
Define gal_unit as a unit in (ZMod 19).
-/
def gal_unit (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 19) : (ZMod 19)ˣ := Units.mk0 (N : ZMod 19) (by
  rw [Ne, ZMod.natCast_zmod_eq_zero_iff_dvd]
  intro h
  have hN_prime : Nat.Prime N := Fact.out
  have : 19 = 1 ∨ 19 = N := (Nat.dvd_prime hN_prime).mp h
  have : 19 = N := this.resolve_left (by norm_num)
  exact hN this.symm)

/-
Check Algebra Z OL instance.
-/
#synth Algebra ℤ 𝓞L

/-
σ_int preserves addition.
-/
lemma sigma_int_add (u : (ZMod 19)ˣ) (x y : 𝓞L) : σ_int u (x + y) = σ_int u x + σ_int u y := by
  convert congr_arg ( σ_int u ) ( show ( x + y : 𝓞L ) = ( x : 𝓞L ) + ( y : 𝓞L ) from rfl ) using 1;
  -- Since σ_int u is the restriction of σ u, and σ u is a ring homomorphism, it preserves addition. Thus, σ u (x + y) = σ u x + σ u y. Therefore, σ_int u (x + y) = σ u (x + y) = σ u x + σ u y = σ_int u x + σ_int u y.
  have h_add : σ u (x + y) = σ u x + σ u y := by
    exact map_add _ _ _;
  exact Subtype.ext h_add.symm

/-
σ_int preserves multiplication.
-/
lemma sigma_int_mul (u : (ZMod 19)ˣ) (x y : 𝓞L) : σ_int u (x * y) = σ_int u x * σ_int u y := by
  have h_sigma_int_mul : ∀ (x y : 𝓞L), σ_int u (x * y) = σ_int u x * σ_int u y := by
    exact fun x y => by ext; simp +decide [ σ_int_coe ] ;
  exact h_sigma_int_mul x y

/-
σ_int maps ζ_int to ζ_int^N.
-/
lemma sigma_zeta : σ_int (uN hN) ζ_int = ζ_int ^ N := by
  -- Since ζ_int is the image of ζ in the ring of integers, applying σ_int to ζ_int should be the same as applying σ to ζ and then converting the result back to the ring of integers.
  have h_sigma_int_ζ : σ_int (uN hN) ζ_int = ⟨σ (uN hN) ζ, by
    refine' ⟨ Polynomial.X ^ 19 - 1, _, _ ⟩;
    · erw [ Polynomial.Monic, Polynomial.leadingCoeff_X_pow_sub_C ] ; norm_num;
    · simp +decide [ ← map_pow, ← map_sub, hζ.pow_eq_one ]⟩ := by
    exact Subtype.ext rfl
  generalize_proofs at *;
  -- Since σ is defined by ζ ↦ ζ^u, we have σ (uN hN) ζ = ζ^(uN hN).
  have h_sigma_ζ : σ (uN hN) ζ = ζ ^ (uN hN : ZMod 19).val := by
    -- Since σ is defined by ζ ↦ ζ^u, we have σ (uN hN) ζ = ζ^(uN hN) by definition of σ.
    have h_sigma_ζ : ∀ u : (ZMod 19)ˣ, σ u ζ = ζ ^ (u : ZMod 19).val := by
      intros u
      simp [σ];
      erw [ PowerBasis.equivOfMinpoly_apply ];
      erw [ PowerBasis.lift_gen ] ; aesop;
    exact h_sigma_ζ _;
  -- Since $uN hN$ is a unit in $(\mathbb{Z}/19\mathbb{Z})^\times$, we have $uN hN \equiv N \pmod{19}$.
  have h_unit : (uN hN : ZMod 19).val = N % 19 := by
    unfold uN; aesop;
  -- Since $N \equiv N \pmod{19}$, we have $\zeta^{N \mod 19} = \zeta^N$.
  have h_exp : ζ ^ (N % 19) = ζ ^ N := by
    rw [ ← Nat.mod_add_div N 19, pow_add, pow_mul ] ; norm_num [ h_unit ];
    have h_exp : ζ ^ 19 = 1 := by
      exact hζ.pow_eq_one;
    rw [ h_exp, one_pow, mul_one ];
  convert h_sigma_int_ζ using 1;
  ext; simp +decide [ h_sigma_ζ, h_unit, h_exp ] ;
  exact?

/-
The ring of integers is generated by ζ_int.
-/
lemma adjoin_zeta_eq_top : Algebra.adjoin ℤ ({ζ_int} : Set 𝓞L) = ⊤ := by
  -- By definition of cyclotomic fields, the ring of integers of $L$ is $\mathbb{Z}[\zeta_{19}]$.
  have h_cyclotomic : IsCyclotomicExtension {19} ℤ 𝓞L := by
    exact?;
  have := h_cyclotomic.2;
  ext x;
  simp_all +decide [ Algebra.adjoin_singleton_eq_range_aeval ];
  have := this x;
  refine' Algebra.adjoin_induction _ _ _ _ this;
  · intro x hx
    use Polynomial.X ^ (Nat.find (show ∃ k : ℕ, x = ζ_int ^ k from by
                                    have h_root : ∀ x : L, x ^ 19 = 1 → ∃ k : ℕ, x = ζ ^ k := by
                                      intro x hx
                                      have h_root : x ∈ Set.range (fun k : ℕ => ζ ^ k) := by
                                        have h_root : x ∈ Set.range (fun k : ZMod 19 => ζ ^ k.val) := by
                                          have h_poly : x ^ 19 = 1 := hx
                                          have h_poly_factor : ∏ k ∈ Finset.range 19, (Polynomial.X - Polynomial.C (ζ ^ k)) = Polynomial.X ^ 19 - 1 := by
                                            refine' Polynomial.eq_of_degree_sub_lt_of_eval_finset_eq _ _ _;
                                            exact Finset.image ( fun k : ℕ => ζ ^ k ) ( Finset.range 19 );
                                            · refine' lt_of_lt_of_le ( Polynomial.degree_sub_lt _ _ _ ) _;
                                              · norm_num [ Polynomial.degree_prod, Polynomial.degree_X_pow_sub_C ];
                                                erw [ Polynomial.degree_X_pow_sub_C ] <;> norm_num [ Polynomial.degree_sub_eq_left_of_degree_lt ];
                                                erw [ Finset.sum_congr rfl fun _ _ => Polynomial.degree_sub_eq_left_of_degree_lt <| ?_ ] <;> norm_num;
                                                erw [ Polynomial.degree_C ] <;> norm_num;
                                                exact hζ.ne_zero ( by norm_num );
                                              · exact Finset.prod_ne_zero_iff.mpr fun i hi => Polynomial.X_sub_C_ne_zero _;
                                              · norm_num [ Polynomial.leadingCoeff_prod ];
                                                exact Finset.prod_eq_one fun i hi => by rw [ ← Polynomial.C_pow, Polynomial.leadingCoeff_X_sub_C ] ;
                                              · rw [ Polynomial.degree_prod, Finset.sum_congr rfl fun _ _ => Polynomial.degree_X_sub_C _ ] ; norm_num;
                                                rw [ Finset.card_image_of_injOn ] <;> norm_num;
                                                intro a ha b hb hab; have := hζ.pow_inj ( show a < 19 from ha ) ( show b < 19 from hb ) ; aesop;
                                            · simp +decide [ Polynomial.eval_prod ];
                                              intro a ha; rw [ Finset.prod_eq_prod_diff_singleton_mul <| Finset.mem_range.mpr ha ] ; ring;
                                              rw [ pow_mul', show ζ ^ 19 = 1 from by exact hζ.pow_eq_one ] ; norm_num
                                          replace h_poly_factor := congr_arg ( Polynomial.eval x ) h_poly_factor ; simp_all +decide [ Polynomial.eval_prod, Finset.prod_eq_zero_iff, sub_eq_iff_eq_add ];
                                          obtain ⟨ a, ha, rfl ⟩ := h_poly_factor; exact ⟨ ⟨ a, ha ⟩, rfl ⟩ ;
                                        grind;
                                      exact h_root.imp fun k hk => hk.symm;
                                    obtain ⟨ k, hk ⟩ := h_root ( algebraMap 𝓞L L x ) ( by simpa [ ← map_pow ] using congr_arg ( algebraMap 𝓞L L ) hx );
                                    use k;
                                    exact?));
    simp +zetaDelta at *;
    exact Nat.find_spec ( _ : ∃ k : ℕ, x = ζ_int ^ k ) ▸ rfl.symm;
  · exact fun r => ⟨ Polynomial.C r, by simp +decide ⟩;
  · rintro x y hx hy ⟨ p, rfl ⟩ ⟨ q, rfl ⟩ ; exact ⟨ p + q, by simp +decide [ Polynomial.aeval_add ] ⟩;
  · rintro x y hx hy ⟨ p, rfl ⟩ ⟨ q, rfl ⟩ ; exact ⟨ p * q, by simp +decide [ Polynomial.aeval_mul ] ⟩

/-
The automorphism σ_N reduces to the Frobenius map x ↦ x^N modulo P.
-/
theorem artin_property [CharP (kP P) N] (x : 𝓞L) : red P (σ_int (uN hN) x) = (red P x) ^ N := by
  -- By definition of $σ_int$, we know that $σ_int (uN hN) x = (σ_int (uN hN)) x$.
  have h_sigma_int : ∀ x : 𝓞L, (red P) (σ_int (uN hN) x) = (red P x) ^ N := by
    have h_gen : ∀ x : 𝓞L, x ∈ Algebra.adjoin ℤ ({ζ_int} : Set 𝓞L) := by
      exact fun x => by rw [ adjoin_zeta_eq_top ] ; exact Algebra.mem_top;
    intro x
    induction' h_gen x using Algebra.adjoin_induction with x hx ih;
    · convert congr_arg ( red P ) ( sigma_zeta hN ) using 1;
      · grind;
      · rw [ show x = ζ_int from hx ] ; simp +decide [ red ] ;
    · -- Since σ_int (uN hN) is an algebra homomorphism, it preserves the algebra map.
      have h_sigma_int_algebra_map : ∀ (ih : ℤ), σ_int (uN hN) (algebraMap ℤ 𝓞L ih) = algebraMap ℤ 𝓞L ih := by
        unfold σ_int; aesop;
      convert congr_arg ( red P ) ( h_sigma_int_algebra_map ih ) using 1;
      erw [ Ideal.Quotient.eq ];
      -- Since $P$ is a maximal ideal in $\mathcal{O}_L$, we know that $N \in P$.
      have hN_in_P : (algebraMap ℤ 𝓞L) N ∈ P := by
        have hN_in_P : (algebraMap ℤ (𝓞L ⧸ P)) N = 0 := by
          convert CharP.cast_eq_zero ( kP P ) N using 1;
        erw [ Ideal.Quotient.eq_zero_iff_mem ] at hN_in_P ; aesop;
      have hN_in_P : ∀ (ih : ℤ), (algebraMap ℤ 𝓞L) (ih ^ N - ih) ∈ P := by
        intro ih
        have hN_in_P : (algebraMap ℤ 𝓞L) (ih ^ N - ih) = (algebraMap ℤ 𝓞L) N * (algebraMap ℤ 𝓞L) ((ih ^ N - ih) / N) := by
          rw [ ← map_mul, Int.mul_ediv_cancel' ];
          haveI := Fact.mk ( Fact.out : Nat.Prime N ) ; simp +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ] ;
        exact hN_in_P.symm ▸ P.mul_mem_right _ ‹_›;
      convert hN_in_P ih using 1 ; norm_num [ map_sub, map_pow ];
    · simp_all +decide [ sigma_int_add ];
      rw [ add_pow_char ];
    · rename_i hx hy ihx ihy;
      convert congr_arg₂ ( · * · ) ihx ihy using 1 <;> ring;
      · convert congr_arg ( red P ) ( sigma_int_mul ( uN hN ) _ _ ) using 1;
      · simp +decide [ ← mul_pow ];
  exact h_sigma_int x

/-
The integer versions of α, β, γ coerce to the field versions.
-/
lemma coe_int_defs : (α_int : L) = α ∧ (β_int : L) = β ∧ (γ_int : L) = γ := by
  bound

/-
The cyclic relations hold for the integer versions α_int, β_int, γ_int.
-/
lemma cyclic_relations_int : 7 * β_int = 3 * α_int^2 - 8 * α_int - 38 ∧ 7 * γ_int = -3 * α_int^2 + α_int + 38 := by
  have h_intRelations : (7 * β_int : L) = 3 * α_int ^ 2 - 8 * α_int - 38 ∧ (7 * γ_int : L) = -3 * α_int ^ 2 + α_int + 38 := by
    convert cyclic_relations using 1;
  convert h_intRelations;
  · erw [ ← Subtype.coe_inj ] ; norm_num;
    exact?;
  · erw [ ← Subtype.coe_inj ] ; norm_num;
    exact?

/-
The permutation action on the integer versions of α, β, γ matches the global action.
-/
lemma sigma_alpha_eq_beta_or_gamma (u : (ZMod 19)ˣ) :
  ((u : ZMod 19) ∈ S1 → σ_int u α_int = β_int) ∧
  ((u : ZMod 19) ∈ S2 → σ_int u α_int = γ_int) := by
    constructor;
    · intro hu
      have h_eq : (σ_int u α_int : L) = β_int := by
        rw [ σ_int_coe, coe_int_defs.1, coe_int_defs.2.1 ];
        unfold σ;
        unfold α β η₀ η₁ η₂;
        fin_cases u <;> simp +decide at hu ⊢ hu ⊢;
        all_goals erw [ PowerBasis.equivOfMinpoly_apply ] ; norm_num;
        all_goals erw [ PowerBasis.lift_gen ];
        all_goals erw [ show ζ = IsCyclotomicExtension.zeta 19 ℚ L from rfl ] ; norm_num [ ZMod.val ] ; ring!;
        all_goals have := IsCyclotomicExtension.zeta_pow 19 ℚ L; simp_all +decide [ pow_succ, mul_assoc ] ;
        grind +ring;
        · grind +ring;
        · grind +ring;
        · grind +ring;
        · grind +ring;
        · grind +ring;
      exact Subtype.ext h_eq;
    · intro hu
      have h_eq : (σ_int u α_int : L) = γ_int := by
        simp +decide [ σ_int_coe, coe_int_defs ];
        unfold γ;
        unfold α η₀ η₁ η₂;
        -- By definition of $σ$, we know that $σ u (ζ^k) = ζ^{ku}$ for any integer $k$.
        have h_sigma_zeta : ∀ k : ℕ, (σ u) (ζ ^ k) = ζ ^ (k * u.val.val % 19) := by
          -- By definition of $σ$, we know that $σ u (ζ) = ζ^u$.
          have h_sigma_zeta : (σ u) ζ = ζ ^ u.val.val := by
            have h_sigma_zeta : ∀ u : (ZMod 19)ˣ, σ u ζ = ζ ^ (u : ZMod 19).val := by
              unfold σ;
              simp +zetaDelta at *;
              intro u; exact (by
              convert ( IsCyclotomicExtension.autEquivPow L ( Polynomial.cyclotomic.irreducible_rat ( n := 19 ) ( by norm_num ) ) ).symm_apply_eq.mpr _;
              rotate_left;
              exact u;
              exact ( IsCyclotomicExtension.autEquivPow L ( Polynomial.cyclotomic.irreducible_rat ( n := 19 ) ( by norm_num ) ) ).symm u;
              · exact?;
              · erw [ PowerBasis.equivOfMinpoly_gen ];
                simp +decide [ IsPrimitiveRoot.powerBasis ];
                rfl);
            exact h_sigma_zeta u;
          -- Since ζ is a primitive 19th root of unity, we have ζ^19 = 1. Therefore, ζ^(k*u.val.val) = ζ^(k*u.val.val mod 19).
          have h_exp : ∀ k : ℕ, ζ ^ (k * u.val.val) = ζ ^ (k * u.val.val % 19) := by
            have h_exp : ζ ^ 19 = 1 := by
              exact hζ.pow_eq_one;
            exact fun k => by rw [ ← Nat.mod_add_div ( k * u.val.val ) 19, pow_add, pow_mul ] ; aesop;
          simp_all +decide [ pow_mul' ];
        fin_cases u <;> simp +decide [ * ] at hu ⊢;
        all_goals simp_all +decide [ ZMod.val ];
        all_goals ring;
      exact Subtype.ext h_eq

/-
Explicit formula for the Frobenius action on α.
-/
theorem explicit_frobenius (hN7 : N ≠ 7) [CharP (kP P) N] :
  ((uN hN : ZMod 19) ∈ S1 → (red P α_int) ^ N = (3 * (red P α_int)^2 - 8 * (red P α_int) - 38) * (7 : kP P)⁻¹) ∧
  ((uN hN : ZMod 19) ∈ S2 → (red P α_int) ^ N = (-3 * (red P α_int)^2 + (red P α_int) + 38) * (7 : kP P)⁻¹) := by
    constructor <;> intro h;
    · -- By artin_property, (red P α_int)^N = red P (σ_int (uN hN) α_int).
      have h1 : (red P α_int) ^ N = red P (σ_int (uN hN) α_int) := by
        rw [ ← artin_property ];
      -- By sigma_alpha_eq_beta_or_gamma, σ_int (uN hN) α_int = β_int.
      have h2 : σ_int (uN hN) α_int = β_int := by
        exact sigma_alpha_eq_beta_or_gamma ( uN hN ) |>.1 h;
      field_simp;
      rw [ h1, h2, eq_div_iff ] <;> norm_num;
      · -- By cyclic_relations_int, we have 7 * β_int = 3 * α_int^2 - 8 * α_int - 38.
        have h3 : 7 * β_int = 3 * α_int^2 - 8 * α_int - 38 := by
          exact cyclic_relations_int.1;
        convert congr_arg ( red P ) h3 using 1 <;> norm_num ; ring;
        · exact?;
        · erw [ map_ofNat, map_ofNat, map_ofNat ] ; ring;
      · erw [ CharP.cast_eq_zero_iff ( kP P ) N ];
        exact fun h => hN7 <| by have := Nat.le_of_dvd ( by decide ) h; interval_cases N <;> trivial;
    · have h_frob_gamma : (red P α_int) ^ N = red P γ_int := by
        have h_frob_gamma : (red P α_int) ^ N = red P (σ_int (uN hN) α_int) := by
          rw [ ← artin_property ];
        convert h_frob_gamma using 1 ; erw [ sigma_alpha_eq_beta_or_gamma _ |>.2 h ] ;
      have h_cyclic_gamma : 7 * red P γ_int = -3 * (red P α_int) ^ 2 + (red P α_int) + 38 := by
        have h_cyclic_gamma : 7 * γ_int = -3 * α_int ^ 2 + α_int + 38 := by
          exact cyclic_relations_int.2;
        convert congr_arg ( red P ) h_cyclic_gamma using 1
      have h_inv_gamma : 7⁻¹ * (7 * red P γ_int) = red P γ_int := by
        rw [ ← mul_assoc, inv_mul_cancel₀, one_mul ];
        intro h; have := CharP.cast_eq_zero_iff ( kP P ) N 7; simp_all +decide ;
        have := Nat.le_of_dvd ( by decide ) this; interval_cases N <;> trivial;
      rw [h_frob_gamma, ← h_inv_gamma]
      field_simp [h_cyclic_gamma];
      exact congrArg₂ _ ( by linear_combination' h_cyclic_gamma ) rfl

def q_val : ℕ := 19
def a_val : ℕ := 7
def s1_val : ZMod 19 := (- (a_val : ZMod 19) - 3) / 6
def s2_val : ZMod 19 := ((a_val : ZMod 19) - 3) / 6
def c_val (N : ℕ) : ZMod 19 := (N : ZMod 19) ^ ((q_val - 1) / 3)

/-
The polynomial f = x^3 - 19x - 19.
-/
def f_poly : Polynomial L := X^3 - 19*X - 19

/-
alpha is a root of f = x^3 - 19x - 19.
-/
theorem alpha_root : (f_poly).eval α = 0 := by
  unfold f_poly;
  unfold α;
  unfold η₂ η₁;
  -- By definition of $ζ$, we know that $ζ^19 = 1$ and $ζ^k ≠ 1$ for $1 ≤ k < 19$.
  have hζ : ζ ^ 19 = 1 ∧ ∀ k : ℕ, 1 ≤ k → k < 19 → ζ ^ k ≠ 1 := by
    exact ⟨ hζ.pow_eq_one, fun k hk₁ hk₂ hk₃ => by have := hζ.pow_eq_one_iff_dvd k; interval_cases k <;> simp_all +decide ⟩;
  ring_nf at *;
  simp_all +decide [ pow_succ' ];
  grind +ring

/-
alpha + beta + gamma = 0.
-/
theorem sum_zero : α + β + γ = 0 := by
  unfold α β γ
  ring

/-
2a beta = 6 alpha^2 - (a+9)alpha - 4q with a=7, q=19.
-/
theorem beta_relation : 2 * 7 * β = 6 * α^2 - (7 + 9) * α - 4 * 19 := by
  -- By multiplying both sides of the equation $7 \beta = 3 \alpha^2 - 8 \alpha - 38$ by 2, we get the desired result.
  have h_mul : 2 * 7 * β = 2 * (3 * α^2 - 8 * α - 38) := by
    convert congr_arg ( fun x : L => 2 * x ) ( cyclic_relations.left ) using 1 ; ring;
  convert h_mul using 1 ; ring

/-
s1_val is 11 and s2_val is 7 in ZMod 19.
-/
lemma s1_val_eq : s1_val = 11 := by
  native_decide +revert
lemma s2_val_eq : s2_val = 7 := by
  native_decide +revert

/-
N is in S1 iff c_val N = s2_val.
-/
lemma N_in_S1_iff_c_eq_s2 (hN : N ≠ 19) : (uN hN : ZMod 19) ∈ S1 ↔ c_val N = s2_val := by
  -- By definition of $c_val$, we know that $c_val N = (N : ZMod 19)^6$.
  have hc_val : c_val N = (N : ZMod 19)^6 := by
    exact?;
  simp +decide [ hc_val, s2_val_eq ];
  unfold uN; simp +decide [ S1 ] ;
  grind

/-
N is in S2 iff c_val N = s1_val.
-/
lemma N_in_S2_iff_c_eq_s1 (hN : N ≠ 19) : (uN hN : ZMod 19) ∈ S2 ↔ c_val N = s1_val := by
  unfold uN S2 c_val s1_val;
  simp +decide [ q_val, a_val ] ; norm_num [ ZMod.natCast_eq_zero_iff ];
  grind

/-
If c = s1, then alpha^N = gamma. If c = s2, then alpha^N = beta.
-/
theorem final_result {N : ℕ} [Fact (Nat.Prime N)] (hN : N ≠ 19) (P : Ideal 𝓞L) [P.IsMaximal] [CharP (kP P) N] (hN7 : N ≠ 7) :
  (c_val N = s1_val → (red P α_int) ^ N = red P γ_int) ∧
  (c_val N = s2_val → (red P α_int) ^ N = red P β_int) := by
    constructor <;> intro h;
    · have h_sigma_gamma : σ_int (uN hN) α_int = γ_int := by
        apply (sigma_alpha_eq_beta_or_gamma (uN hN)).right;
        convert N_in_S2_iff_c_eq_s1 hN |>.2 h using 1;
      rw [ ← h_sigma_gamma, artin_property ];
    · -- By N_in_S1_iff_c_eq_s2, uN hN is in S1.
      have h_S1 : (uN hN : ZMod 19) ∈ S1 := by
        convert N_in_S1_iff_c_eq_s2 hN |>.2 h using 1;
      rw [ ← artin_property ];
      rw [ sigma_alpha_eq_beta_or_gamma _ |>.1 h_S1 ];
      assumption

/-
If c = s1, then alpha^N = gamma. If c = s2, then alpha^N = beta.
-/
theorem final_result_proof {N : ℕ} [Fact (Nat.Prime N)] (hN : N ≠ 19) (P : Ideal 𝓞L) [P.IsMaximal] [CharP (kP P) N] (hN7 : N ≠ 7) :
  (c_val N = s1_val → (red P α_int) ^ N = red P γ_int) ∧
  (c_val N = s2_val → (red P α_int) ^ N = red P β_int) := by
    convert final_result hN P hN7 using 1

/-
Definitions of constants q=97, a=19, s1, s2, and c for the new problem instance.
-/
def q' : ℕ := 97
def a' : ℕ := 19
def s1' : ZMod 97 := (- (a' : ZMod 97) - 3) * (6 : ZMod 97)⁻¹
def s2' : ZMod 97 := ((a' : ZMod 97) - 3) * (6 : ZMod 97)⁻¹
def c' (N : ℕ) : ZMod 97 := (N : ZMod 97) ^ ((q' - 1) / 3)

/-
Define the cyclotomic field L97 and the primitive root of unity zeta97.
-/
open Polynomial NumberField

def L97 : Type := CyclotomicField 97 ℚ

instance : Field L97 := CyclotomicField.instField 97 ℚ
instance : NumberField L97 := CyclotomicField.instNumberField 97 ℚ
instance : IsCyclotomicExtension {97} ℚ L97 := CyclotomicField.isCyclotomicExtension 97 ℚ

def ζ97 : L97 := IsCyclotomicExtension.zeta 97 ℚ L97

instance : Fact (Nat.Prime 97) := ⟨by norm_num⟩

/-
Define the sets of indices and the Gaussian periods for q=97. Define alpha, beta, gamma.
-/
def S_cubic_res : Finset (ZMod 97) := {x | x ≠ 0 ∧ x ^ 32 = 1}
def S_s1 : Finset (ZMod 97) := {x | x ≠ 0 ∧ x ^ 32 = s1'}
def S_s2 : Finset (ZMod 97) := {x | x ≠ 0 ∧ x ^ 32 = s2'}

def η₀' : L97 := ∑ x ∈ S_cubic_res, ζ97 ^ (x.val : ℕ)
def η₁' : L97 := ∑ x ∈ S_s2, ζ97 ^ (x.val : ℕ)
def η₂' : L97 := ∑ x ∈ S_s1, ζ97 ^ (x.val : ℕ)

def α' : L97 := -(η₂' - η₁')
def β' : L97 := -(η₀' - η₂')
def γ' : L97 := -(η₁' - η₀')

/-
The sum of alpha, beta, and gamma is zero.
-/
theorem sum_zero' : α' + β' + γ' = 0 := by
  unfold α' β' γ' ;
  ring

/-
Definitions of index function, cyclotomic numbers, and period function for q=97.
-/
def ind (x : ZMod 97) : ZMod 3 :=
  if x ∈ S_cubic_res then 0
  else if x ∈ S_s1 then 1
  else 2

def cyc_num (i j : ZMod 3) : ℕ :=
  Fintype.card { x : ZMod 97 // x ≠ 0 ∧ x ≠ 1 ∧ ind x = i ∧ ind (1 - x) = j }

def period (i : ZMod 3) : L97 :=
  if i = 0 then η₀'
  else if i = 1 then η₂'
  else η₁'

/-
The period function maps 0, 1, 2 to eta0', eta2', eta1' respectively.
-/
lemma period_eq_def : period 0 = η₀' ∧ period 1 = η₂' ∧ period 2 = η₁' := by
  aesop

/-
The index function correctly identifies which coset an element belongs to.
-/
lemma ind_spec (x : ZMod 97) (hx : x ≠ 0) :
  (ind x = 0 ↔ x ∈ S_cubic_res) ∧
  (ind x = 1 ↔ x ∈ S_s1) ∧
  (ind x = 2 ↔ x ∈ S_s2) := by
    native_decide +revert

/-
Compute the cyclotomic numbers for q=97.
-/
#eval (cyc_num 0 0, cyc_num 0 1, cyc_num 0 2)
#eval (cyc_num 1 0, cyc_num 1 1, cyc_num 1 2)
#eval (cyc_num 2 0, cyc_num 2 1, cyc_num 2 2)

/-
Values of the cyclotomic numbers for q=97.
-/
lemma cyc_num_vals :
  cyc_num 0 0 = 12 ∧ cyc_num 0 1 = 10 ∧ cyc_num 0 2 = 9 ∧
  cyc_num 1 0 = 10 ∧ cyc_num 1 1 = 9 ∧ cyc_num 1 2 = 13 ∧
  cyc_num 2 0 = 9 ∧ cyc_num 2 1 = 13 ∧ cyc_num 2 2 = 10 := by
  native_decide

/-
Number of solutions to x + y = u with ind x = i and ind y = j.
-/
def N_sol (i j : ZMod 3) (u : ZMod 97) : ℕ :=
  Fintype.card { p : ZMod 97 × ZMod 97 // p.1 ≠ 0 ∧ p.2 ≠ 0 ∧ ind p.1 = i ∧ ind p.2 = j ∧ p.1 + p.2 = u }

/-
The index of -1 is 0.
-/
lemma ind_neg_one : ind (-1) = 0 := by
  native_decide

/-
The index function is a homomorphism from the multiplicative group to the additive group Z/3Z.
-/
lemma ind_mul (x y : ZMod 97) (hx : x ≠ 0) (hy : y ≠ 0) : ind (x * y) = ind x + ind y := by
  revert x y
  native_decide

/-
The index of the inverse is the negative of the index.
-/
lemma ind_inv (x : ZMod 97) (hx : x ≠ 0) : ind (x⁻¹) = - ind x := by
  revert x
  native_decide

/-
The number of solutions to x+y=u depends only on the index of u.
-/
lemma N_sol_eq_cyc_num (i j : ZMod 3) (u : ZMod 97) (hu : u ≠ 0) :
  N_sol i j u = cyc_num (i - ind u) (j - ind u) := by
    refine' Fintype.card_congr _;
    refine' Equiv.ofBijective ( fun x => ⟨ x.val.1 / u, _, _, _, _ ⟩ ) ⟨ _, _ ⟩;
    all_goals simp_all +decide [ div_eq_iff, Function.Injective, Function.Surjective ];
    grind;
    · grind;
    · have := ind_mul ( x.val.1 / u ) u; simp_all +decide [ div_eq_mul_inv ] ;
      grind;
    · have h_ind : ind (x.val.2 / u) = ind x.val.2 - ind u := by
        have h_ind : ind (x.val.2 / u) = ind x.val.2 + ind (u⁻¹) := by
          apply ind_mul; exact (by
          exact x.2.2.1); exact (by
          haveI := Fact.mk ( by decide : Nat.Prime 97 ) ; exact inv_ne_zero hu;);
        rw [ h_ind, ind_inv u hu ] ; ring;
      grind;
    · aesop;
    · native_decide +revert

/-
The cardinalities of the sets S_cubic_res, S_s1, and S_s2 are all 32.
-/
lemma card_S : S_cubic_res.card = 32 ∧ S_s1.card = 32 ∧ S_s2.card = 32 := by
  native_decide

/-
Define C_coset to avoid ambiguity and relate it to the period definitions.
-/
def C_coset (i : ZMod 3) : Finset (ZMod 97) := Finset.univ.filter (fun x => x ≠ 0 ∧ ind x = i)

lemma C_coset_eq : C_coset 0 = S_cubic_res ∧ C_coset 1 = S_s1 ∧ C_coset 2 = S_s2 := by
  native_decide +revert

lemma period_eq_sum_C_coset (i : ZMod 3) : period i = ∑ x ∈ C_coset i, ζ97 ^ (x.val : ℕ) := by
  rw [ show C_coset i = if i = 0 then S_cubic_res else if i = 1 then S_s1 else S_s2 from ?_ ];
  · unfold period; aesop;
  · native_decide +revert

/-
Expansion of the product of Gaussian periods in terms of solution counts.
-/
lemma period_mul_eq_sum_N_sol (i j : ZMod 3) :
  period i * period j = (if i = j then 32 else 0) +
  ∑ u ∈ Finset.univ.filter (fun x : ZMod 97 => x ≠ 0), (N_sol i j u : L97) * ζ97 ^ (u.val : ℕ) := by
    have h_expand : period i * period j = ∑ u ∈ Finset.univ, (if u = 0 then (if i = j then 32 else 0) else (N_sol i j u : L97)) * ζ97 ^ u.val := by
      have h_expand : period i * period j = ∑ x ∈ C_coset i, ∑ y ∈ C_coset j, ζ97 ^ (x.val + y.val : ℕ) := by
        rw [ period_eq_sum_C_coset i, period_eq_sum_C_coset j, Finset.sum_mul ];
        simp +decide only [Finset.mul_sum _ _ _, pow_add];
      have h_group : ∀ u : ZMod 97, ∑ x ∈ C_coset i, ∑ y ∈ C_coset j, (if x + y = u then 1 else 0) * ζ97 ^ u.val = (if u = 0 then (if i = j then 32 else 0) else (N_sol i j u : L97)) * ζ97 ^ u.val := by
        intro u
        have h_group : ∑ x ∈ C_coset i, ∑ y ∈ C_coset j, (if x + y = u then 1 else 0) = (if u = 0 then (if i = j then 32 else 0) else (N_sol i j u : ℕ)) := by
          split_ifs <;> simp_all +decide [ N_sol ];
          · fin_cases j <;> native_decide;
          · intro x hx y hy; contrapose! hy; simp_all +decide [ C_coset ] ;
            intro hy' hy''; have := ind_mul x ( -1 ) ; simp_all +decide [ add_eq_zero_iff_eq_neg ] ;
          · rw [ Fintype.card_subtype ];
            rw [ ← Finset.card_biUnion ];
            · refine' Finset.card_bij ( fun x hx => ( u - x, x ) ) _ _ _ <;> simp +decide [ Finset.mem_biUnion, Finset.mem_filter ];
              · unfold C_coset at *; aesop;
              · unfold C_coset; aesop;
            · exact fun x hx y hy hxy => Finset.disjoint_left.mpr fun z hz₁ hz₂ => hxy <| by aesop;
        convert congr_arg ( · * ζ97 ^ u.val ) ( show ( ∑ x ∈ C_coset i, ∑ y ∈ C_coset j, if x + y = u then 1 else 0 : L97 ) = if u = 0 then if i = j then 32 else 0 else N_sol i j u from ?_ ) using 1;
        · simp +decide only [Finset.sum_mul _ _ _];
        · split_ifs <;> norm_num;
        · convert congr_arg ( fun x : ℕ => x : ℕ → L97 ) h_group using 1;
          norm_num [ Finset.sum_ite ];
      rw [ ← Finset.sum_congr rfl fun u hu => h_group u ];
      rw [ h_expand, Finset.sum_comm ];
      rw [ Finset.sum_comm, Finset.sum_congr rfl ];
      rw [ Finset.sum_comm ];
      intro x hx; rw [ Finset.sum_comm ] ; simp +decide [ Finset.sum_ite ] ;
      refine' Finset.sum_congr rfl fun y hy => _;
      have h_exp : ζ97 ^ 97 = 1 := by
        exact IsCyclotomicExtension.zeta_pow ( 97 : ℕ ) ℚ L97;
      rw [ ← Nat.mod_add_div ( x.val + y.val ) 97, pow_add, pow_mul ] ; aesop;
    rw [ h_expand, Finset.sum_eq_add_sum_diff_singleton ( Finset.mem_univ 0 ) ] ; aesop

/-
Multiplication rule for Gaussian periods.
-/
lemma period_mul (i j : ZMod 3) :
  period i * period j = (if i = j then 32 else 0) +
  (cyc_num (i - 0) (j - 0) * period 0 +
   cyc_num (i - 1) (j - 1) * period 1 +
   cyc_num (i - 2) (j - 2) * period 2) := by
     -- Apply Lemma `period_mul_eq_sum_N_sol` to expand the product.
     have h_expand : period i * period j = (if i = j then 32 else 0) +
       ∑ u ∈ (Finset.univ.filter (fun x : ZMod 97 => x ≠ 0)), (cyc_num (i - ind u) (j - ind u) : L97) * ζ97 ^ (u.val : ℕ) := by
         rw [ period_mul_eq_sum_N_sol ];
         exact congrArg _ ( Finset.sum_congr rfl fun u hu => by rw [ N_sol_eq_cyc_num i j u ( by simpa using hu ) ] );
     -- Partition the sum over `u != 0` based on `ind u = k` for `k \in {0, 1, 2}`.
     have h_partition : ∑ u ∈ (Finset.univ.filter (fun x : ZMod 97 => x ≠ 0)), (cyc_num (i - ind u) (j - ind u) : L97) * ζ97 ^ (u.val : ℕ) =
       ∑ k ∈ Finset.univ, (cyc_num (i - k) (j - k) : L97) * ∑ u ∈ (Finset.univ.filter (fun x : ZMod 97 => x ≠ 0 ∧ ind x = k)), ζ97 ^ (u.val : ℕ) := by
         simp +decide only [Finset.sum_filter, Finset.mul_sum _ _ _];
         rw [ Finset.sum_comm, Finset.sum_congr rfl ] ; aesop;
     -- By definition of $C_koset$, we know that $\sum_{u \in C_koset k} \zeta_97^u = \text{period } k$.
     have h_period : ∀ k : ZMod 3, ∑ u ∈ (Finset.univ.filter (fun x : ZMod 97 => x ≠ 0 ∧ ind x = k)), ζ97 ^ (u.val : ℕ) = period k := by
       intro k
       simp [period_eq_sum_C_coset, C_coset];
     simp_all +decide [ Fin.sum_univ_three ];
     erw [ Fin.sum_univ_three ] ; ring!;

/-
alpha' is a root of X^3 - 97X - 97.
-/
theorem alpha_root' : α'^3 - 97*α' - 97 = 0 := by
  unfold α';
  -- By definition of $η₀'$, $η₁'$, and $η₂'$, we know that $η₀' + η₁' + η₂' = -1$.
  have h_sum : η₀' + η₁' + η₂' = -1 := by
    -- The sum of all non-trivial roots of unity in the cyclotomic field is -1.
    have h_sum_roots : ∑ x ∈ Finset.univ.filter (fun x : ZMod 97 => x ≠ 0), ζ97 ^ (x.val : ℕ) = -1 := by
      have h_sum : ∑ x : ZMod 97, (ζ97 : L97) ^ (x.val : ℕ) = 0 := by
        have h_geom_sum : ∑ x ∈ Finset.range 97, (ζ97 : L97) ^ x = 0 := by
          rw [ geom_sum_eq ] <;> norm_num [ IsPrimitiveRoot.ne_one ];
          · exact Or.inl ( sub_eq_zero_of_eq <| by exact IsPrimitiveRoot.pow_eq_one <| IsCyclotomicExtension.zeta_spec 97 ℚ L97 );
          · have h_order : IsPrimitiveRoot ζ97 97 := by
              convert IsCyclotomicExtension.zeta_spec 97 ℚ L97 using 1
              skip
            generalize_proofs at *; exact h_order.ne_one (by norm_num);
        convert h_geom_sum using 1;
      rw [ Finset.sum_eq_add_sum_diff_singleton ( Finset.mem_univ 0 ) ] at h_sum;
      simpa [ Finset.filter_ne' ] using eq_neg_of_add_eq_zero_right h_sum;
    rw [ ← h_sum_roots, show η₀' + η₁' + η₂' = ∑ x ∈ Finset.univ.filter ( fun x : ZMod 97 => x ≠ 0 ), ζ97 ^ x.val from ?_ ];
    rw [ show ( Finset.univ.filter fun x : ZMod 97 => x ≠ 0 ) = S_cubic_res ∪ S_s1 ∪ S_s2 from by native_decide, Finset.sum_union, Finset.sum_union ];
    · exact?;
    · native_decide +revert;
    · native_decide +revert;
  have := @period_mul 0 0; ( have := @period_mul 0 1; ( have := @period_mul 0 2; ( have := @period_mul 1 1; ( have := @period_mul 1 2; ( have := @period_mul 2 2; norm_num [ Finset.sum_add_distrib, pow_succ' ] at *; ) ) ) ) );
  simp_all +decide [ period_eq_def ];
  erw [ cyc_num_vals.1, cyc_num_vals.2.1, cyc_num_vals.2.2.1, cyc_num_vals.2.2.2.1, cyc_num_vals.2.2.2.2.1, cyc_num_vals.2.2.2.2.2.1, cyc_num_vals.2.2.2.2.2.2.1, cyc_num_vals.2.2.2.2.2.2.2.1, cyc_num_vals.2.2.2.2.2.2.2.2 ] at * ; norm_num at *;
  grind +ring

/-
Algebraic relation between beta' and alpha'.
-/
theorem beta_relation' : 2 * 19 * β' = 6 * α'^2 - (19 + 9) * α' - 4 * 97 := by
  unfold β' α';
  rw [ show η₀' = period 0 from rfl, show η₁' = period 2 from rfl, show η₂' = period 1 from rfl ];
  -- By definition of $period$, we know that $period 0 + period 1 + period 2 = -1$.
  have h_sum : period 0 + period 1 + period 2 = -1 := by
    -- By definition of $period$, we know that $period 0 + period 1 + period 2 = \sum_{x \in \mathbb{Z}/97\mathbb{Z}} \zeta_{97}^x$.
    have h_sum : period 0 + period 1 + period 2 = ∑ x ∈ Finset.univ.filter (fun x : ZMod 97 => x ≠ 0), ζ97 ^ (x.val : ℕ) := by
      rw [ period_eq_sum_C_coset, period_eq_sum_C_coset, period_eq_sum_C_coset ];
      rw [ ← Finset.sum_union, ← Finset.sum_union ];
      · rw [ show C_coset 0 ∪ C_coset 1 ∪ C_coset 2 = Finset.univ.filter ( fun x : ZMod 97 => x ≠ 0 ) from ?_ ];
        native_decide +revert;
      · native_decide +revert;
      · simp +decide [ C_coset, Finset.disjoint_left ];
        grind;
    -- The sum of all powers of $\zeta_{97}$ is zero.
    have h_sum_zero : ∑ x ∈ Finset.range 97, ζ97 ^ x = 0 := by
      rw [ geom_sum_eq ] <;> norm_num [ hζ ];
      · exact Or.inl ( sub_eq_zero_of_eq <| by exact ( show ζ97 ^ 97 = 1 from by exact ( by exact ( by exact ( by exact ( by exact ( by exact ( by exact ( by exact ( by exact ( by exact ( by exact ( by exact ( by exact by rw [ show ζ97 = IsCyclotomicExtension.zeta 97 ℚ L97 from rfl ] ; exact? ) ) ) ) ) ) ) ) ) ) ) ) ) );
      · have := IsCyclotomicExtension.zeta_spec 97 ℚ L97;
        exact this.ne_one ( by decide );
    rw [ Finset.sum_eq_sum_diff_singleton_add ( Finset.mem_range.mpr ( show 0 < 97 by decide ) ) ] at h_sum_zero;
    convert eq_neg_of_add_eq_zero_left h_sum_zero using 1;
    norm_num;
  -- Substitute the known values of the cyclotomic numbers into the equation.
  have h_cyclotomic : cyc_num 0 0 = 12 ∧ cyc_num 0 1 = 10 ∧ cyc_num 0 2 = 9 ∧ cyc_num 1 0 = 10 ∧ cyc_num 1 1 = 9 ∧ cyc_num 1 2 = 13 ∧ cyc_num 2 0 = 9 ∧ cyc_num 2 1 = 13 ∧ cyc_num 2 2 = 10 := by
    exact?;
  rw [ show period 0 = -1 - period 1 - period 2 by linear_combination' h_sum ] ; ring;
  rw [ show period 1 ^ 2 = period 1 * period 1 by ring, show period 2 ^ 2 = period 2 * period 2 by ring ] ; rw [ period_mul 1 1, period_mul 2 2, period_mul 1 2 ] ; simp +decide [ h_cyclotomic ] ; ring;
  rw [ show cyc_num ( -1 ) 0 = 9 by exact h_cyclotomic.2.2.2.2.2.2.1, show cyc_num ( -1 ) ( -1 ) = 10 by exact h_cyclotomic.2.2.2.2.2.2.2.2 ] ; norm_num ; ring;
  rw [ show cyc_num 0 1 = 10 by exact h_cyclotomic.2.1, show cyc_num 1 1 = 9 by exact h_cyclotomic.2.2.2.2.1 ] ; ring ; rw [ show period 0 = -1 - period 1 - period 2 by linear_combination' h_sum ] ; ring

/-
Define the Galois unit and automorphism for q=97.
-/
def gal_unit97 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 97) : (ZMod 97)ˣ := Units.mk0 (N : ZMod 97) (by
  rw [Ne, ZMod.natCast_zmod_eq_zero_iff_dvd]
  intro h
  have hN_prime : Nat.Prime N := Fact.out
  have : 97 = 1 ∨ 97 = N := (Nat.dvd_prime hN_prime).mp h
  have : 97 = N := this.resolve_left (by norm_num)
  exact hN this.symm)

def sigma97 (u : (ZMod 97)ˣ) : L97 ≃ₐ[ℚ] L97 :=
  (IsCyclotomicExtension.autEquivPow L97 (Polynomial.cyclotomic.irreducible_rat (n := 97) (by norm_num))).symm u

/-
The Frobenius automorphism permutes the Gaussian periods by shifting their index by ind(N).
-/
lemma sigma_period (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 97) (i : ZMod 3) :
  sigma97 (gal_unit97 N hN) (period i) = period (i + ind (N : ZMod 97)) := by
    -- By definition of $C_coset$, we know that $C_coset i$ is the set of elements $x$ such that $ind x = i$.
    have hC_coset : ∀ i : ZMod 3, C_coset i = {x : ZMod 97 | x ≠ 0 ∧ ind x = i} := by
      unfold C_coset; aesop;
    -- By definition of $sigma97$, we know that it maps $ζ97^x$ to $ζ97^{Nx}$ for any $x \in \mathbb{Z}/97\mathbb{Z}$.
    have h_sigma_map : ∀ x : ZMod 97, (sigma97 (gal_unit97 N hN)) (ζ97 ^ x.val) = ζ97 ^ ((N * x).val) := by
      intro x
      have h_sigma_map : (sigma97 (gal_unit97 N hN)) (ζ97 ^ x.val) = (sigma97 (gal_unit97 N hN)) (ζ97) ^ x.val := by
        exact map_pow _ _ _;
      have h_sigma_map : (sigma97 (gal_unit97 N hN)) ζ97 = ζ97 ^ (N : ZMod 97).val := by
        unfold sigma97;
        simp +decide [ gal_unit97 ];
        erw [ PowerBasis.equivOfMinpoly_gen ];
        exact?;
      cases N <;> simp_all +decide [ pow_mul ];
      norm_num [ ← pow_mul, ZMod.val_add, ZMod.val_mul ];
      rw [ ← Nat.mod_add_div ( ( _ + ZMod.val 1 ) % 97 * x.val ) 97 ] ; norm_num [ pow_add, pow_mul, Nat.mul_mod, Nat.pow_mod ] ;
      have h_zeta_pow : ζ97 ^ 97 = 1 := by
        exact IsPrimitiveRoot.pow_eq_one ( IsCyclotomicExtension.zeta_spec 97 ℚ L97 );
      aesop;
    -- By definition of $C_coset$, we know that $C_coset (i + ind N)$ is the set of elements $y$ such that $ind y = i + ind N$.
    have hC_coset_shift : C_coset (i + ind N) = Finset.image (fun x => (N * x : ZMod 97)) (C_coset i) := by
      ext x; simp [hC_coset];
      constructor;
      · intro hx
        obtain ⟨a, ha⟩ : ∃ a : ZMod 97, (N * a : ZMod 97) = x := by
          have h_inv : ∃ a : ZMod 97, (N : ZMod 97) * a = 1 := by
            have h_inv : Nat.gcd N 97 = 1 := by
              exact Nat.Coprime.symm ( Nat.Prime.coprime_iff_not_dvd ( by decide ) |>.2 fun h => hN <| by have := Nat.prime_dvd_prime_iff_eq ( by decide : Nat.Prime 97 ) ( Fact.out : Nat.Prime N ) ; tauto );
            have := Nat.exists_mul_emod_eq_one_of_coprime h_inv;
            exact Exists.elim ( this ( by decide ) ) fun m hm => ⟨ m, by simpa [ ← ZMod.natCast_eq_zero_iff ] using congr_arg ( fun x : ℕ => x : ℕ → ZMod 97 ) hm ⟩;
          exact ⟨ h_inv.choose * x, by linear_combination' h_inv.choose_spec * x ⟩;
        use a; simp_all +decide [ Set.ext_iff ] ;
        have h_ind_mul : ind (N * a) = ind N + ind a := by
          have h_ind_mul : ∀ x y : ZMod 97, x ≠ 0 → y ≠ 0 → ind (x * y) = ind x + ind y := by
            exact?;
          apply h_ind_mul; exact (by
          intro h; simp_all +decide [ ZMod.natCast_eq_zero_iff ] ;); exact (by
          grind);
        grind +ring;
      · rintro ⟨ a, ha, rfl ⟩;
        have h_ind_mul : ind (N * a) = ind N + ind a := by
          apply ind_mul;
          · intro h; have := Fact.out ( p := Nat.Prime N ) ; simp_all +decide [ ZMod.natCast_eq_zero_iff ] ;
            rw [ this.dvd_iff_eq ] at h <;> aesop;
          · exact hC_coset i |>.subset ha |>.1;
        simp_all +decide [ add_comm, C_coset ];
        exact?;
    -- By definition of $period$, we know that $period i$ is the sum of $ζ97^x$ over $x \in C_coset i$.
    have hperiod_def : ∀ i : ZMod 3, period i = ∑ x ∈ C_coset i, ζ97 ^ x.val := by
      exact?;
    rw [ hperiod_def, hperiod_def, hC_coset_shift, Finset.sum_image ];
    · rw [ map_sum, Finset.sum_congr rfl fun x hx => h_sigma_map x ];
    · intro x hx y hy; haveI := Fact.mk ( Fact.out : Nat.Prime N ) ; simp_all +decide [ mul_eq_zero, ZMod.natCast_eq_zero_iff ] ;
      rintro ( rfl | h ) <;> simp_all +decide [ Nat.Prime.dvd_iff_eq Fact.out ]

/-
Integer versions of the periods and roots, and their coercion properties.
-/
def ζ97_int : 𝓞 L97 := IsPrimitiveRoot.toInteger (IsCyclotomicExtension.zeta_spec 97 ℚ L97)

def period_int (i : ZMod 3) : 𝓞 L97 := ∑ x ∈ C_coset i, ζ97_int ^ (x.val : ℕ)

def α'_int : 𝓞 L97 := -(period_int 1 - period_int 2)
def β'_int : 𝓞 L97 := -(period_int 0 - period_int 1)
def γ'_int : 𝓞 L97 := -(period_int 2 - period_int 0)

lemma coe_period_int (i : ZMod 3) : (period_int i : L97) = period i := by
  unfold period_int period;
  unfold ζ97_int η₀' η₁' η₂';
  split_ifs <;> simp +decide [ *, Subtype.ext_iff ];
  · congr! 1;
    exact C_coset_eq.1;
  · congr! 2;
    exact C_coset_eq.2.1;
  · congr! 1;
    native_decide +revert

lemma coe_alpha'_int : (α'_int : L97) = α' := by
  unfold α'_int α';
  unfold period_int;
  unfold η₂' η₁' C_coset; simp +decide [ Finset.sum_sub_distrib ] ;
  congr! 2;
  · native_decide +revert;
  · native_decide +revert

lemma coe_beta'_int : (β'_int : L97) = β' := by
  unfold β'_int β';
  unfold period_int;
  simp +decide [ C_coset_eq, S_s1, S_cubic_res ];
  congr!

lemma coe_gamma'_int : (γ'_int : L97) = γ' := by
  unfold γ'_int γ';
  unfold period_int;
  simp +decide [ C_coset_eq ];
  congr! 2

/-
Relate the index of N to the value of c' N being s1'.
-/
lemma ind_N_eq_1_iff_c_eq_s1 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 97) :
  ind (N : ZMod 97) = 1 ↔ c' N = s1' := by
    unfold ind c' s1';
    unfold S_cubic_res S_s1; simp +decide;
    unfold q' a' s1'; simp +decide ;
    split_ifs <;> simp_all +decide [ ZMod.natCast_eq_zero_iff ];
    · native_decide +revert;
    · rename_i h₁ h₂;
      contrapose! h₂;
      exact ⟨ fun h => hN <| by have := Nat.prime_dvd_prime_iff_eq ( by decide : Nat.Prime 97 ) ( Fact.out : Nat.Prime N ) ; tauto, h₂ ⟩

/-
Relate the index of N to the value of c' N being s2'.
-/
lemma ind_N_eq_2_iff_c_eq_s2 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 97) :
  ind (N : ZMod 97) = 2 ↔ c' N = s2' := by
    -- By definition of $c'$ and $ind$, we know that $c' N = s2'$ if and only if $N^{32} = s2'$.
    have h_c'_eq_s2' : c' N = s2' ↔ (N : ZMod 97) ^ 32 = s2' := by
      rfl;
    cases eq_or_ne ( N : ZMod 97 ) 0 <;> simp_all +decide [ ind ];
    · rw [ ZMod.natCast_eq_zero_iff ] at * ; exact absurd ( Nat.dvd_of_mod_eq_zero ( Nat.mod_eq_zero_of_dvd <| by assumption ) ) ( by rw [ Nat.dvd_prime Fact.out ] ; aesop );
    · split_ifs <;> simp_all +decide [ S_cubic_res, S_s1, S_s2 ];
      · native_decide +revert;
      · native_decide +revert;
      · have h_cases : ∀ x : ZMod 97, x ≠ 0 → x ^ 32 = 1 ∨ x ^ 32 = s1' ∨ x ^ 32 = s2' := by
          native_decide +revert;
        cases h_cases _ ‹_› <;> tauto

/-
Abbreviations for the ring of integers, residue field, and reduction map for q=97.
-/
abbrev 𝓞L97 := 𝓞 L97
def kP97 (P : Ideal 𝓞L97) [P.IsMaximal] := 𝓞L97 ⧸ P
noncomputable instance (P : Ideal 𝓞L97) [P.IsMaximal] : Field (kP97 P) := Ideal.Quotient.field P
def red97 (P : Ideal 𝓞L97) [P.IsMaximal] : 𝓞L97 →+* kP97 P := Ideal.Quotient.mk P

/-
Relate the index of N to the value of c' N being s1'.
-/
lemma ind_N_eq_1_iff_c_eq_s1_new (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 97) :
  ind (N : ZMod 97) = 1 ↔ c' N = s1' := by
    convert ind_N_eq_1_iff_c_eq_s1 N hN using 1

/-
Lift the automorphism sigma97 to the ring of integers.
-/
def sigma_int97 (u : (ZMod 97)ˣ) (x : 𝓞 L97) : 𝓞 L97 := ⟨sigma97 u x, by
  have h_integral : IsIntegral ℤ (x : L97) := x.2
  exact IsIntegral.map (sigma97 u) h_integral⟩

/-
The ring of integers is generated by zeta97.
-/
lemma adjoin_zeta_eq_top97 : Algebra.adjoin ℤ ({ζ97_int} : Set 𝓞L97) = ⊤ := by
  let hζ := IsCyclotomicExtension.zeta_spec 97 ℚ L97
  let pb := IsPrimitiveRoot.integralPowerBasis' hζ
  have h_gen : pb.gen = ζ97_int := IsPrimitiveRoot.integralPowerBasis'_gen hζ
  rw [← h_gen]
  exact pb.adjoin_gen_eq_top

/-
The automorphism sigma_N reduces to the Frobenius map modulo P.
-/
theorem artin_property97 {N : ℕ} [Fact (Nat.Prime N)] (hN : N ≠ 97) (P : Ideal 𝓞L97) [P.IsMaximal] [CharP (kP97 P) N] (x : 𝓞L97) :
  red97 P (sigma_int97 (gal_unit97 N hN) x) = (red97 P x) ^ N := by
    have h_sigma_int97_zeta : ∀ x : 𝓞L97, x ∈ Algebra.adjoin ℤ ({ζ97_int} : Set 𝓞L97) → red97 P (sigma_int97 (gal_unit97 N hN) x) = (red97 P x) ^ N := by
      refine fun x hx => Algebra.adjoin_induction ?_ ?_ ?_ ?_ hx;
      · -- Since $\sigma_N(\zeta_{97}) = \zeta_{97}^N$, we have $\sigma_int97(\zeta_{97}) = \zeta_{97}^N$.
        have h_sigma_zeta : sigma_int97 (gal_unit97 N hN) ζ97_int = ζ97_int ^ N := by
          have h_sigma_zeta : (sigma97 (gal_unit97 N hN) ζ97_int : L97) = ζ97_int ^ N := by
            have h_sigma_zeta : ∀ (u : (ZMod 97)ˣ), sigma97 u ζ97 = ζ97 ^ (u : ZMod 97).val := by
              intro u
              simp [sigma97];
              erw [ PowerBasis.equivOfMinpoly_gen ];
              rfl;
            convert h_sigma_zeta ( gal_unit97 N hN ) using 1;
            simp +decide [ gal_unit97 ];
            rw [ ← Nat.mod_add_div N 97 ] ; norm_num [ pow_add, pow_mul ] ;
            have h_zeta_97_pow : ζ97 ^ 97 = 1 := by
              exact IsPrimitiveRoot.pow_eq_one ( IsCyclotomicExtension.zeta_spec 97 ℚ L97 );
            erw [ show ( ζ97_int : L97 ) = ζ97 from ?_ ] ; aesop;
            exact?;
          exact?;
        aesop;
      · intro r; exact (by
        simp +decide [ red97, sigma_int97 ];
        erw [ Ideal.Quotient.eq ];
        -- Since $P$ is a maximal ideal, it is prime, and thus if $r^N - r$ is in $P$, then either $r$ is in $P$ or $r^{N-1} - 1$ is in $P$.
        have h_prime : ∀ r : ℤ, (r ^ N - r : 𝓞L97) ∈ P := by
          intro r
          have h_fermat : (r ^ N - r : ℤ) ≡ 0 [ZMOD N] := by
            simp +decide [ ← ZMod.intCast_eq_intCast_iff ];
          obtain ⟨ k, hk ⟩ := h_fermat.symm.dvd;
          -- Since $N$ is in $P$, multiplying by $k$ (which is an integer) keeps it in $P$.
          have hN_in_P : (N : 𝓞L97) ∈ P := by
            have hN_in_P : (N : kP97 P) = 0 := by
              exact?;
            exact?;
          convert P.mul_mem_right ( k : 𝓞L97 ) hN_in_P using 1 ; norm_cast ; aesop;
        simpa using Submodule.neg_mem _ ( h_prime r ));
      · intro x y hx hy hx' hy'; simp +decide [ *, pow_add ] ;
        rw [ show sigma_int97 ( gal_unit97 N hN ) ( x + y ) = sigma_int97 ( gal_unit97 N hN ) x + sigma_int97 ( gal_unit97 N hN ) y from ?_, map_add ];
        · rw [ hx', hy', add_pow_char ];
        · exact Subtype.ext <| map_add _ _ _;
      · simp +contextual [ *, mul_pow ];
        intro x y hx hy hx' hy'; rw [ show sigma_int97 ( gal_unit97 N hN ) ( x * y ) = sigma_int97 ( gal_unit97 N hN ) x * sigma_int97 ( gal_unit97 N hN ) y from ?_ ] ; aesop;
        exact Subtype.ext <| map_mul _ _ _;
    exact h_sigma_int97_zeta x ( by rw [ adjoin_zeta_eq_top97 ] ; exact Algebra.mem_top ) |> fun h => by simpa using h;

/-
If c' N = s1', then sigma_N(alpha') = gamma'.
-/
lemma sigma_alpha_eq_gamma_if_s1 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 97) (h : c' N = s1') :
  sigma_int97 (gal_unit97 N hN) α'_int = γ'_int := by
    -- We check the equality in the field L97.
    have h_field : sigma97 (gal_unit97 N hN) (α'_int : L97) = (γ'_int : L97) := by
      -- By definition of $c'$, we know that $c' N = s1'$ implies $ind (N : ZMod 97) = 1$.
      have h_ind : ind (N : ZMod 97) = 1 := by
        exact?;
      -- By definition of $sigma97$, we have $sigma97 (gal_unit97 N hN) (α'_int) = sigma97 (gal_unit97 N hN) (period 2 - period 1)$.
      have h_sigma97_def : sigma97 (gal_unit97 N hN) (α'_int : L97) = sigma97 (gal_unit97 N hN) (period 2 - period 1) := by
        rw [ show ( α'_int : L97 ) = period 2 - period 1 from ?_ ];
        convert coe_alpha'_int using 1;
        unfold α';
        exact?;
      -- By definition of $sigma97$, we have $sigma97 (gal_unit97 N hN) (period 2 - period 1) = period (2 + ind (N : ZMod 97)) - period (1 + ind (N : ZMod 97))$.
      have h_sigma97_period : sigma97 (gal_unit97 N hN) (period 2 - period 1) = period (2 + ind (N : ZMod 97)) - period (1 + ind (N : ZMod 97)) := by
        rw [ map_sub, sigma_period, sigma_period ];
      simp_all +decide [ γ'_int ];
      exact congr_arg₂ _ ( coe_period_int 0 ▸ rfl ) ( coe_period_int 2 ▸ rfl );
    convert h_field using 1;
    -- Since the ring of integers is a subalgebra of the field, the elements are equal in the ring if and only if they are equal in the field.
    have h_subalgebra : ∀ (x y : 𝓞 L97), x = y ↔ (x : L97) = (y : L97) := by
      exact?;
    convert h_subalgebra _ _ using 1

/-
If c' N = s2', then sigma_N(alpha') = beta'.
-/
lemma sigma_alpha_eq_beta_if_s2 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 97) (h : c' N = s2') :
  sigma_int97 (gal_unit97 N hN) α'_int = β'_int := by
    -- Since $c' N = s2'$, we have $ind N = 2$.
    have h_ind : ind (N : ZMod 97) = 2 := by
      exact?;
    -- Since $\sigma_N(\alpha') = \beta'$ in $L97$, we have $\sigma_N(\alpha'_int) = \beta'_int$ in $\mathcal{O}_{L97}$.
    have h_sigma_alpha_int_eq_beta_int : (sigma97 (gal_unit97 N hN) α' : L97) = β' := by
      -- Since $c' N = s2'$, we have $ind N = 2$. Therefore, $\sigma_N(\alpha') = \beta'$.
      have h_sigma_beta : (sigma97 (gal_unit97 N hN)) (period 2 - period 1) = period 1 - period 0 := by
        have := sigma_period N hN 2; have := sigma_period N hN 1; aesop;
      generalize_proofs at *; (
      unfold α' β'; aesop;)
    generalize_proofs at *; (
    convert h_sigma_alpha_int_eq_beta_int using 1
    generalize_proofs at *; (
    constructor <;> intro h <;> simp_all +decide [ ← coe_alpha'_int, ← coe_beta'_int, ← coe_gamma'_int ] ;
    exact Subtype.ext h_sigma_alpha_int_eq_beta_int
    skip))

/-
Final result for q=97: Frobenius action on alpha depends on c' N.
-/
theorem final_result_97 {N : ℕ} [Fact (Nat.Prime N)] (hN : N ≠ 97) (hN19 : N ≠ 19) (P : Ideal 𝓞L97) [P.IsMaximal] [CharP (kP97 P) N] :
  (c' N = s1' → (red97 P α'_int) ^ N = red97 P γ'_int) ∧
  (c' N = s2' → (red97 P α'_int) ^ N = red97 P β'_int) := by
  constructor
  · intro h
    rw [← artin_property97 hN P α'_int]
    rw [sigma_alpha_eq_gamma_if_s1 N hN h]
  · intro h
    rw [← artin_property97 hN P α'_int]
    rw [sigma_alpha_eq_beta_if_s2 N hN h]

/-
Definitions of constants q=349, a=37, s1, s2, and c for the new problem instance. Also define the cyclotomic field L349 and the primitive root of unity zeta349.
-/
def q'' : ℕ := 349
def a'' : ℕ := 37
def s1'' : ZMod 349 := (- (a'' : ZMod 349) - 3) * (6 : ZMod 349)⁻¹
def s2'' : ZMod 349 := ((a'' : ZMod 349) - 3) * (6 : ZMod 349)⁻¹
def c'' (N : ℕ) : ZMod 349 := (N : ZMod 349) ^ ((q'' - 1) / 3)

open Polynomial NumberField

def L349 : Type := CyclotomicField 349 ℚ

instance : Field L349 := CyclotomicField.instField 349 ℚ
instance : NumberField L349 := CyclotomicField.instNumberField 349 ℚ
instance : IsCyclotomicExtension {349} ℚ L349 := CyclotomicField.isCyclotomicExtension 349 ℚ

def ζ349 : L349 := IsCyclotomicExtension.zeta 349 ℚ L349

instance : Fact (Nat.Prime 349) := ⟨by norm_num⟩

/-
Define the sets of indices and the Gaussian periods for q=349. Define alpha, beta, gamma. Prove their sum is zero.
-/
def S_cubic_res'' : Finset (ZMod 349) := {x | x ≠ 0 ∧ x ^ 116 = 1}
def S_s1'' : Finset (ZMod 349) := {x | x ≠ 0 ∧ x ^ 116 = s1''}
def S_s2'' : Finset (ZMod 349) := {x | x ≠ 0 ∧ x ^ 116 = s2''}

def η₀'' : L349 := ∑ x ∈ S_cubic_res'', ζ349 ^ (x.val : ℕ)
def η₁'' : L349 := ∑ x ∈ S_s2'', ζ349 ^ (x.val : ℕ)
def η₂'' : L349 := ∑ x ∈ S_s1'', ζ349 ^ (x.val : ℕ)

def α'' : L349 := -(η₂'' - η₁'')
def β'' : L349 := -(η₀'' - η₂'')
def γ'' : L349 := -(η₁'' - η₀'')

theorem sum_zero'' : α'' + β'' + γ'' = 0 := by
  -- By definition of α'', β'', and γ'', we have α'' + β'' + γ'' = 0 because each period is a sum of roots of unity, and their sum is zero.
  simp [α'', β'', γ'', η₀'', η₁'', η₂'']

/-
Definitions of index function, cyclotomic numbers, and period function for q=349.
-/
def ind'' (x : ZMod 349) : ZMod 3 :=
  if x ∈ S_cubic_res'' then 0
  else if x ∈ S_s1'' then 1
  else 2

def cyc_num'' (i j : ZMod 3) : ℕ :=
  Fintype.card { x : ZMod 349 // x ≠ 0 ∧ x ≠ 1 ∧ ind'' x = i ∧ ind'' (1 - x) = j }

def period'' (i : ZMod 3) : L349 :=
  if i = 0 then η₀''
  else if i = 1 then η₂''
  else η₁''

/-
The period function maps 0, 1, 2 to eta0'', eta2'', eta1'' respectively.
-/
lemma period_eq_def'' : period'' 0 = η₀'' ∧ period'' 1 = η₂'' ∧ period'' 2 = η₁'' := by
  exact ⟨ rfl, rfl, rfl ⟩

/-
The index function correctly identifies which coset an element belongs to.
-/
lemma ind_spec'' (x : ZMod 349) (hx : x ≠ 0) :
  (ind'' x = 0 ↔ x ∈ S_cubic_res'') ∧
  (ind'' x = 1 ↔ x ∈ S_s1'') ∧
  (ind'' x = 2 ↔ x ∈ S_s2'') := by
    native_decide +revert

/-
Evaluate the cyclotomic numbers for q=349.
-/
#eval (cyc_num'' 0 0, cyc_num'' 0 1, cyc_num'' 0 2)
#eval (cyc_num'' 1 0, cyc_num'' 1 1, cyc_num'' 1 2)
#eval (cyc_num'' 2 0, cyc_num'' 2 1, cyc_num'' 2 2)

/-
Define N_sol'' as the number of solutions to x + y = u with ind x = i and ind y = j.
-/
def N_sol'' (i j : ZMod 3) (u : ZMod 349) : ℕ :=
  Fintype.card { p : ZMod 349 × ZMod 349 // p.1 ≠ 0 ∧ p.2 ≠ 0 ∧ ind'' p.1 = i ∧ ind'' p.2 = j ∧ p.1 + p.2 = u }

/-
The index of -1 is 0.
-/
lemma ind_neg_one'' : ind'' (-1) = 0 := by
  native_decide +revert

/-
The index function is a homomorphism from the multiplicative group to the additive group Z/3Z.
-/
lemma ind_mul'' (x y : ZMod 349) (hx : x ≠ 0) (hy : y ≠ 0) : ind'' (x * y) = ind'' x + ind'' y := by
  native_decide +revert

/-
The index of the inverse is the negative of the index.
-/
lemma ind_inv'' (x : ZMod 349) (hx : x ≠ 0) : ind'' (x⁻¹) = - ind'' x := by
  native_decide +revert

/-
The cardinalities of the sets S_cubic_res'', S_s1'', and S_s2'' are all 116.
-/
lemma card_S'' : S_cubic_res''.card = 116 ∧ S_s1''.card = 116 ∧ S_s2''.card = 116 := by
  native_decide +revert

/-
Define C_coset'' and prove it equals the previously defined sets.
-/
def C_coset'' (i : ZMod 3) : Finset (ZMod 349) := Finset.univ.filter (fun x => x ≠ 0 ∧ ind'' x = i)

lemma C_coset_eq'' : C_coset'' 0 = S_cubic_res'' ∧ C_coset'' 1 = S_s1'' ∧ C_coset'' 2 = S_s2'' := by
  native_decide +revert

/-
The period function is the sum of zeta powers over the coset.
-/
lemma period_eq_sum_C_coset'' (i : ZMod 3) : period'' i = ∑ x ∈ C_coset'' i, ζ349 ^ (x.val : ℕ) := by
  fin_cases i <;> simp +decide [ period_eq_def'' ];
  · exact C_coset_eq''.left.symm ▸ rfl;
  · -- By definition of $C_coset''$, we know that $C_coset'' 1 = S_s1''$.
    have h_coset_eq : C_coset'' 1 = S_s1'' := by
      exact C_coset_eq''.2.1;
    exact h_coset_eq.symm ▸ rfl;
  · exact Eq.symm ( by rw [ show C_coset'' 2 = S_s2'' by exact ( by native_decide ) ] ; rfl )

/-
Expansion of the product of Gaussian periods in terms of solution counts for q=349.
-/
lemma period_mul_eq_sum_N_sol'' (i j : ZMod 3) :
  period'' i * period'' j = (if i = j then 116 else 0) +
  ∑ u ∈ Finset.univ.filter (fun x : ZMod 349 => x ≠ 0), (N_sol'' i j u : L349) * ζ349 ^ (u.val : ℕ) := by
    revert i j;
    -- We'll use the fact that $period'' i = \sum_{x \in S_i} \zeta_{349}^x$ to expand the product.
    have h_expand : ∀ i j : ZMod 3, period'' i * period'' j = (if i = j then 116 else 0) + ∑ x ∈ C_coset'' i, ∑ y ∈ C_coset'' j, if x + y = 0 then 0 else ζ349 ^ ((x + y).val : ℕ) := by
      intro i j
      have h_expand : period'' i * period'' j = ∑ x ∈ C_coset'' i, ∑ y ∈ C_coset'' j, ζ349 ^ (x.val : ℕ) * ζ349 ^ (y.val : ℕ) := by
        rw [ period_eq_sum_C_coset'' i, period_eq_sum_C_coset'' j, Finset.sum_mul_sum ];
      have h_split : ∑ x ∈ C_coset'' i, ∑ y ∈ C_coset'' j, ζ349 ^ (x.val : ℕ) * ζ349 ^ (y.val : ℕ) = ∑ x ∈ C_coset'' i, ∑ y ∈ C_coset'' j, if x + y = 0 then 1 else ζ349 ^ ((x + y).val : ℕ) := by
        refine' Finset.sum_congr rfl fun x hx => Finset.sum_congr rfl fun y hy => _;
        have h_exp : ζ349 ^ (x.val + y.val) = ζ349 ^ ((x + y).val : ℕ) := by
          have h_exp : ζ349 ^ 349 = 1 := by
            exact IsPrimitiveRoot.pow_eq_one ( IsCyclotomicExtension.zeta_spec 349 ℚ L349 );
          rw [ ← Nat.mod_add_div ( x.val + y.val ) 349, pow_add, pow_mul ] ; aesop;
        split_ifs <;> simp_all +decide [ ← pow_add ];
      have h_card : ∑ x ∈ C_coset'' i, ∑ y ∈ C_coset'' j, (if x + y = 0 then 1 else 0) = if i = j then 116 else 0 := by
        fin_cases i <;> fin_cases j <;> native_decide;
      simp_all +decide [ Finset.sum_ite ];
      rw [ Finset.sum_add_distrib, ← Nat.cast_sum, h_card ];
      split_ifs <;> norm_num;
    intros i j
    have h_double_sum : ∑ x ∈ C_coset'' i, ∑ y ∈ C_coset'' j, (if x + y = 0 then 0 else ζ349 ^ ((x + y).val : ℕ)) = ∑ u ∈ Finset.univ.filter (fun x => x ≠ 0), ∑ x ∈ C_coset'' i, ∑ y ∈ C_coset'' j, (if x + y = u then ζ349 ^ (u.val : ℕ) else 0) := by
      have h_double_sum : ∀ x ∈ C_coset'' i, ∀ y ∈ C_coset'' j, (if x + y = 0 then 0 else ζ349 ^ ((x + y).val : ℕ)) = ∑ u ∈ Finset.univ.filter (fun x => x ≠ 0), (if x + y = u then ζ349 ^ (u.val : ℕ) else 0) := by
        intro x hx y hy; split_ifs <;> simp_all +decide [ Finset.sum_ite ] ;
      rw [ Finset.sum_congr rfl fun x hx => Finset.sum_congr rfl fun y hy => h_double_sum x hx y hy ];
      rw [ Finset.sum_comm, Finset.sum_congr rfl fun _ _ => Finset.sum_comm ];
      rw [ Finset.sum_comm, Finset.sum_congr rfl fun _ _ => Finset.sum_comm ];
    simp_all +decide [ Finset.sum_ite ];
    refine' Finset.sum_congr rfl fun u hu => _;
    rw [ ← Finset.sum_mul _ _ _ ];
    simp +decide [ N_sol'', Fintype.card_subtype ];
    rw [ show ( Finset.filter ( fun x : ZMod 349 × ZMod 349 => ¬x.1 = 0 ∧ ¬x.2 = 0 ∧ ind'' x.1 = i ∧ ind'' x.2 = j ∧ x.1 + x.2 = u ) Finset.univ ) = Finset.biUnion ( C_coset'' i ) fun x => Finset.image ( fun y => ( x, y ) ) ( Finset.filter ( fun y => x + y = u ) ( C_coset'' j ) ) from ?_, Finset.card_biUnion ];
    · simp +decide [ Finset.card_image_of_injective, Function.Injective ];
    · exact fun x hx y hy hxy => Finset.disjoint_left.mpr fun z => by aesop;
    · ext ⟨x, y⟩; simp [C_coset''];
      tauto

/-
The number of solutions to x+y=u depends only on the index of u. Specifically, N_sol(i, j, u) = cyc_num(i - ind(u), j - ind(u)).
-/
lemma N_sol_eq_cyc_num'' (i j : ZMod 3) (u : ZMod 349) (hu : u ≠ 0) :
  N_sol'' i j u = cyc_num'' (i - ind'' u) (j - ind'' u) := by
    convert Set.ext_iff.mp ?_ ( u, 1 - u ) using 1;
    case convert_1 => exact { p : ZMod 349 × ZMod 349 | p.1 ≠ 0 ∧ p.2 ≠ 0 ∧ p.1 + p.2 = u ∧ ind'' p.1 = i ∧ ind'' p.2 = j };
    case convert_2 => exact { p : ZMod 349 × ZMod 349 | p.1 ≠ 0 ∧ p.2 ≠ 0 ∧ p.1 + p.2 = u ∧ ind'' p.1 = i ∧ ind'' p.2 = j };
    · unfold N_sol'' cyc_num''; simp +decide [ Fintype.card_subtype ] ;
      refine' Finset.card_bij ( fun x hx => x.1 / u ) _ _ _;
      · simp +contextual [ hu, sub_eq_iff_eq_add ];
        intro a b ha hb ha' hb' hab; rw [ div_eq_iff_mul_eq ] <;> simp_all +decide [ add_comm, add_left_comm, add_assoc ] ;
        refine' ⟨ _, _, _ ⟩ <;> subst_vars <;> simp_all +decide [ div_eq_mul_inv ];
        · native_decide +revert;
        · native_decide +revert;
      · grind;
      · intro b hb; use ( b * u, ( 1 - b ) * u ) ; simp_all +decide [ sub_mul, mul_assoc ] ;
        native_decide +revert;
    · rfl

/-
Multiplication rule for Gaussian periods for q=349.
-/
lemma period_mul'' (i j : ZMod 3) :
  period'' i * period'' j = (if i = j then 116 else 0) +
  (cyc_num'' (i - 0) (j - 0) * period'' 0 +
   cyc_num'' (i - 1) (j - 1) * period'' 1 +
   cyc_num'' (i - 2) (j - 2) * period'' 2) := by
     -- Apply the lemma N_sol_eq_cyc_num'' to rewrite the sum.
     have h_sum_rewrite : ∑ u ∈ Finset.univ.filter (fun x : ZMod 349 => x ≠ 0), (N_sol'' i j u : L349) * ζ349 ^ (u.val : ℕ) = ∑ k ∈ Finset.univ, cyc_num'' (i - k) (j - k) * (∑ u ∈ C_coset'' k, ζ349 ^ (u.val : ℕ)) := by
       have h_sum_rewrite : ∑ u ∈ Finset.univ.filter (fun x : ZMod 349 => x ≠ 0), (N_sol'' i j u : L349) * ζ349 ^ (u.val : ℕ) = ∑ k ∈ Finset.univ, ∑ u ∈ Finset.univ.filter (fun x : ZMod 349 => x ≠ 0 ∧ ind'' x = k), (N_sol'' i j u : L349) * ζ349 ^ (u.val : ℕ) := by
         rw [ ← Finset.sum_biUnion ];
         · rcongr x ; aesop;
         · exact fun x _ y _ hxy => Finset.disjoint_left.mpr fun z => by aesop;
       -- Apply the lemma N_sol_eq_cyc_num'' to each term in the sum.
       have h_inner_sum : ∀ k : ZMod 3, ∑ u ∈ Finset.univ.filter (fun x : ZMod 349 => x ≠ 0 ∧ ind'' x = k), (N_sol'' i j u : L349) * ζ349 ^ (u.val : ℕ) = cyc_num'' (i - k) (j - k) * ∑ u ∈ Finset.univ.filter (fun x : ZMod 349 => x ≠ 0 ∧ ind'' x = k), ζ349 ^ (u.val : ℕ) := by
         intros k
         have h_inner_sum : ∀ u ∈ Finset.univ.filter (fun x : ZMod 349 => x ≠ 0 ∧ ind'' x = k), (N_sol'' i j u : L349) = cyc_num'' (i - k) (j - k) := by
           intros u hu
           have h_ind : ind'' u = k := by
             grind
           rw [N_sol_eq_cyc_num'' i j u (by
           exact Finset.mem_filter.mp hu |>.2.1)];
           rw [ h_ind ];
         rw [ Finset.mul_sum _ _ _, Finset.sum_congr rfl fun u hu => by rw [ h_inner_sum u hu ] ];
       simp_all +decide only [C_coset''];
     convert congr_arg ( fun x : L349 => ( if i = j then 116 else 0 ) + x ) h_sum_rewrite using 1;
     · convert period_mul_eq_sum_N_sol'' i j using 1;
     · rw [ show ( Finset.univ : Finset ( ZMod 3 ) ) = { 0, 1, 2 } by decide, Finset.sum_insert, Finset.sum_insert ] <;> simp +decide [ Finset.sum_singleton ];
       rw [ ← add_assoc, ← period_eq_sum_C_coset'' 0, ← period_eq_sum_C_coset'' 1, ← period_eq_sum_C_coset'' 2 ]

/-
Values of the cyclotomic numbers for q=349.
-/
lemma cyc_num_vals'' :
  cyc_num'' 0 0 = 42 ∧ cyc_num'' 0 1 = 37 ∧ cyc_num'' 0 2 = 36 ∧
  cyc_num'' 1 0 = 37 ∧ cyc_num'' 1 1 = 36 ∧ cyc_num'' 1 2 = 43 ∧
  cyc_num'' 2 0 = 36 ∧ cyc_num'' 2 1 = 43 ∧ cyc_num'' 2 2 = 37 := by
    native_decide +revert

/-
Prove that the sum of the periods is -1.
-/
lemma sum_eta'' : η₀'' + η₁'' + η₂'' = -1 := by
  unfold η₀'' η₁'' η₂'';
  -- The union of S_cubic_res'', S_s2'', and S_s1'' is the set of all non-zero elements in ZMod 349.
  have h_union : S_cubic_res'' ∪ S_s2'' ∪ S_s1'' = Finset.univ.erase 0 := by
    native_decide +revert;
  rw [ ← Finset.sum_union, ← Finset.sum_union ] <;> norm_num [ h_union ];
  · have h_sum_zero : ∑ x ∈ Finset.range 349, ζ349 ^ x = 0 := by
      rw [ geom_sum_eq ] <;> norm_num [ IsPrimitiveRoot.pow_eq_one ];
      · exact Or.inl ( sub_eq_zero_of_eq <| IsCyclotomicExtension.zeta_pow 349 ℚ L349 );
      · -- By definition of ζ349, it is a primitive 349th root of unity, so it cannot be equal to 1.
        have h_primitive : IsPrimitiveRoot ζ349 349 := by
          convert IsCyclotomicExtension.zeta_spec 349 ℚ L349;
        exact h_primitive.ne_one ( by decide );
    convert h_sum_zero using 1;
  · native_decide +revert;
  · native_decide +revert

/-
Calculate alpha squared in terms of the periods.
-/
lemma alpha_sq_eq'' : α''^2 = 232 - 13*η₀'' + 4*η₂'' + 7*η₁'' := by
  -- By definition of α'', we have α'' = -(η₂'' - η₁''). Squaring both sides gives α''² = (η₂'' - η₁'')².
  have h_alpha_sq : α'' ^ 2 = (η₂'' - η₁'') ^ 2 := by
    unfold α''; ring;
  -- Expanding the right-hand side: (η₂'' - η₁'')² = η₂''² - 2η₂''η₁'' + η₁''².
  rw [h_alpha_sq]
  have h_expand : (η₂'' - η₁'') ^ 2 = η₂'' ^ 2 - 2 * η₂'' * η₁'' + η₁'' ^ 2 := by
    ring;
  -- Substitute the multiplication rules for Gaussian periods into the expanded form.
  have h_subst : η₂'' ^ 2 = (if 1 = 1 then 116 else 0) + (cyc_num'' (1 - 0) (1 - 0) * η₀'' + cyc_num'' (1 - 1) (1 - 1) * η₂'' + cyc_num'' (1 - 2) (1 - 2) * η₁'') := by
    convert period_mul'' 1 1 using 1 ; norm_num [ period_eq_def'' ];
    ring;
  have h_subst2 : η₁'' ^ 2 = (if 2 = 2 then 116 else 0) + (cyc_num'' (2 - 0) (2 - 0) * η₀'' + cyc_num'' (2 - 1) (2 - 1) * η₂'' + cyc_num'' (2 - 2) (2 - 2) * η₁'') := by
    convert period_mul'' 2 2 using 1;
    rw [ sq, ← period_eq_def'' |>.2.2 ]
  have h_subst3 : η₂'' * η₁'' = (if 1 = 2 then 116 else 0) + (cyc_num'' (1 - 0) (2 - 0) * η₀'' + cyc_num'' (1 - 1) (2 - 1) * η₂'' + cyc_num'' (1 - 2) (2 - 2) * η₁'') := by
    convert period_mul'' 1 2 using 1;
  rw [ h_expand, h_subst, h_subst2, show ( 2 : L349 ) * η₂'' * η₁'' = 2 * ( η₂'' * η₁'' ) by ring, h_subst3 ] ; ring;
  rw [ show cyc_num'' 1 1 = 36 by exact cyc_num_vals''.2.2.2.2.1, show cyc_num'' 1 2 = 43 by exact cyc_num_vals''.2.2.2.2.2.1, show cyc_num'' 2 2 = 37 by exact cyc_num_vals''.2.2.2.2.2.2.2.2, show cyc_num'' 0 0 = 42 by exact cyc_num_vals''.1, show cyc_num'' 0 1 = 37 by exact cyc_num_vals''.2.1, show cyc_num'' ( -1 ) ( -1 ) = 37 by exact cyc_num_vals''.2.2.2.2.2.2.2.2, show cyc_num'' ( -1 ) 0 = 36 by exact cyc_num_vals''.2.2.2.2.2.2.1 ] ; ring;
  grind

/-
Prove the algebraic relation between beta'' and alpha''.
-/
theorem beta_relation'' : 2 * 37 * β'' = 6 * α''^2 - (37 + 9) * α'' - 4 * 349 := by
  rw [alpha_sq_eq'']
  have h_sum : η₀'' + η₁'' + η₂'' = -1 := sum_eta''
  have h_beta : β'' = -η₀'' + η₂'' := by
    rw [β'']; ring
  have h_alpha : α'' = -η₂'' + η₁'' := by
    rw [α'']; ring
  rw [h_beta, h_alpha]
  linear_combination 4 * h_sum

/-
Define the Galois unit and automorphism for q=349.
-/
def gal_unit349 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 349) : (ZMod 349)ˣ := Units.mk0 (N : ZMod 349) (by
  rw [Ne, ZMod.natCast_zmod_eq_zero_iff_dvd]
  intro h
  have hN_prime : Nat.Prime N := Fact.out
  have : 349 = 1 ∨ 349 = N := (Nat.dvd_prime hN_prime).mp h
  have : 349 = N := this.resolve_left (by norm_num)
  exact hN this.symm)

def sigma349 (u : (ZMod 349)ˣ) : L349 ≃ₐ[ℚ] L349 :=
  (IsCyclotomicExtension.autEquivPow L349 (Polynomial.cyclotomic.irreducible_rat (n := 349) (by norm_num))).symm u

/-
Multiplication table for the Gaussian periods (corrected).
-/
lemma eta_mul_table'' :
  η₀''^2 = 116 + 42*η₀'' + 36*η₁'' + 37*η₂'' ∧
  η₁''^2 = 116 + 37*η₀'' + 42*η₁'' + 36*η₂'' ∧
  η₂''^2 = 116 + 36*η₀'' + 37*η₁'' + 42*η₂'' ∧
  η₀''*η₁'' = 36*η₀'' + 37*η₁'' + 43*η₂'' ∧
  η₀''*η₂'' = 37*η₀'' + 43*η₁'' + 36*η₂'' ∧
  η₁''*η₂'' = 43*η₀'' + 36*η₁'' + 37*η₂'' := by
    -- Apply the period multiplication rule to each term in the conjunction.
    apply And.intro (by
    -- Substitute the cyclotomic numbers into the multiplication rule.
    have h_subst : period'' 0 * period'' 0 = 116 + 42 * η₀'' + 36 * η₁'' + 37 * η₂'' := by
      convert period_mul'' 0 0 using 1 ; norm_num [ cyc_num_vals'' ];
      rw [ show cyc_num'' ( -1 ) ( -1 ) = 37 by native_decide, show cyc_num'' ( -2 ) ( -2 ) = 36 by native_decide ] ; ring!;
    convert h_subst using 1 ; rw [ sq, period_eq_def'' |>.1 ]) (And.intro (by
    have := period_mul'' 2 2; norm_num at this ⊢; (
    rw [ sq ] ; rw [ show period'' 2 = η₁'' from by rfl ] at this; rw [ show period'' 0 = η₀'' from by rfl ] at this; rw [ show period'' 1 = η₂'' from by rfl ] at this; rw [ show cyc_num'' 2 2 = 37 from by native_decide ] at this; rw [ show cyc_num'' 1 1 = 36 from by native_decide ] at this; rw [ show cyc_num'' 0 0 = 42 from by native_decide ] at this; linear_combination' this;);) (And.intro (by
    have := period_mul'' 1 1; simp_all +decide [ sq ] ;
    convert this using 1 ; norm_num [ cyc_num_vals'' ] ; ring!;
    erw [ show cyc_num'' ( -1 ) ( -1 ) = 37 by native_decide ] ; norm_num) (And.intro (by
    convert period_mul'' 0 2 using 1 ; norm_num [ cyc_num_vals'' ] ; ring!;
    erw [ show cyc_num'' ( -2 ) 0 = 37 by { exact by rw [ show ( -2 : ZMod 3 ) = 1 by decide ] ; exact by rw [ show cyc_num'' 1 0 = 37 by exact by native_decide ] } ] ; erw [ show cyc_num'' ( -1 ) 1 = 43 by { exact by rw [ show ( -1 : ZMod 3 ) = 2 by decide ] ; exact by rw [ show cyc_num'' 2 1 = 43 by exact by native_decide ] } ] ; norm_cast;
    simp +decide [ ZMod ]) (And.intro (by
    convert period_mul'' 0 1 using 1 ; norm_num [ cyc_num_vals'' ];
    rw [ show cyc_num'' ( -1 ) 0 = 36 by native_decide, show cyc_num'' ( -2 ) ( -1 ) = 43 by native_decide ] ; norm_num [ period_eq_def'' ] ; ring) (by
    convert period_mul'' 2 1 using 1 ; ring!;
    erw [ show cyc_num'' 2 1 = 43 by
            native_decide +revert, show cyc_num'' 0 ( -1 ) = 36 by
                                              native_decide +revert, show cyc_num'' 1 0 = 37 by
                                                                                    native_decide +revert ] ; ring!;
    simp +decide)))))

/-
Define the integer version of zeta349.
-/
def ζ349_int : 𝓞 L349 := IsPrimitiveRoot.toInteger (IsCyclotomicExtension.zeta_spec 349 ℚ L349)

/-
Multiplication table for the Gaussian periods (corrected).
-/
lemma eta_mul_table_corrected'' :
  η₀''^2 = 116 + 42*η₀'' + 36*η₁'' + 37*η₂'' ∧
  η₁''^2 = 116 + 37*η₀'' + 42*η₁'' + 36*η₂'' ∧
  η₂''^2 = 116 + 36*η₀'' + 37*η₁'' + 42*η₂'' ∧
  η₀''*η₁'' = 36*η₀'' + 37*η₁'' + 43*η₂'' ∧
  η₀''*η₂'' = 37*η₀'' + 43*η₁'' + 36*η₂'' ∧
  η₁''*η₂'' = 43*η₀'' + 36*η₁'' + 37*η₂'' := by
    -- Apply the period multiplication rule to each term in the conjunction.
    apply And.intro (by
    -- Substitute the cyclotomic numbers into the multiplication rule.
    have h_subst : period'' 0 * period'' 0 = 116 + 42 * η₀'' + 36 * η₁'' + 37 * η₂'' := by
      convert period_mul'' 0 0 using 1 ; norm_num [ cyc_num_vals'' ];
      rw [ show cyc_num'' ( -1 ) ( -1 ) = 37 by native_decide, show cyc_num'' ( -2 ) ( -2 ) = 36 by native_decide ] ; ring!;
    convert h_subst using 1 ; rw [ sq, period_eq_def'' |>.1 ]) (And.intro (by
    have := period_mul'' 2 2; norm_num at this ⊢; (
    rw [ sq ] ; rw [ show period'' 2 = η₁'' from by rfl ] at this; rw [ show period'' 0 = η₀'' from by rfl ] at this; rw [ show period'' 1 = η₂'' from by rfl ] at this; rw [ show cyc_num'' 2 2 = 37 from by native_decide ] at this; rw [ show cyc_num'' 1 1 = 36 from by native_decide ] at this; rw [ show cyc_num'' 0 0 = 42 from by native_decide ] at this; linear_combination' this;);) (And.intro (by
    have := period_mul'' 1 1; simp_all +decide [ sq ] ;
    convert this using 1 ; norm_num [ cyc_num_vals'' ] ; ring!;
    erw [ show cyc_num'' ( -1 ) ( -1 ) = 37 by native_decide ] ; norm_num) (And.intro (by
    convert period_mul'' 0 2 using 1 ; norm_num [ cyc_num_vals'' ] ; ring!;
    erw [ show cyc_num'' ( -2 ) 0 = 37 by { exact by rw [ show ( -2 : ZMod 3 ) = 1 by decide ] ; exact by rw [ show cyc_num'' 1 0 = 37 by exact by native_decide ] } ] ; erw [ show cyc_num'' ( -1 ) 1 = 43 by { exact by rw [ show ( -1 : ZMod 3 ) = 2 by decide ] ; exact by rw [ show cyc_num'' 2 1 = 43 by exact by native_decide ] } ] ; norm_cast;
    simp +decide [ ZMod ]) (And.intro (by
    convert period_mul'' 0 1 using 1 ; norm_num [ cyc_num_vals'' ];
    rw [ show cyc_num'' ( -1 ) 0 = 36 by native_decide, show cyc_num'' ( -2 ) ( -1 ) = 43 by native_decide ] ; norm_num [ period_eq_def'' ] ; ring) (by
    convert period_mul'' 2 1 using 1 ; ring!;
    erw [ show cyc_num'' 2 1 = 43 by
            native_decide +revert, show cyc_num'' 0 ( -1 ) = 36 by
                                              native_decide +revert, show cyc_num'' 1 0 = 37 by
                                                                                    native_decide +revert ] ; ring!;
    simp +decide)))))

/-
Define the integer versions of the periods and roots for q=349.
-/
def period_int'' (i : ZMod 3) : 𝓞 L349 := ∑ x ∈ C_coset'' i, ζ349_int ^ (x.val : ℕ)

def α''_int : 𝓞 L349 := -(period_int'' 1 - period_int'' 2)
def β''_int : 𝓞 L349 := -(period_int'' 0 - period_int'' 1)
def γ''_int : 𝓞 L349 := -(period_int'' 2 - period_int'' 0)

/-
Prove that the integer period coerces to the field period.
-/
lemma coe_period_int'' (i : ZMod 3) : (period_int'' i : L349) = period'' i := by
  -- The algebra map is a ring homomorphism, so it preserves addition. Therefore, applying the algebra map to each term in the sum and then summing them is the same as summing the terms first and then applying the algebra map.
  have h_sum : ∀ (s : Finset (ZMod 349)), (∑ x ∈ s, (ζ349_int ^ (x.val : ℕ) : L349)) = (∑ x ∈ s, (ζ349 ^ (x.val : ℕ) : L349)) := by
    intro s
    congr! 1;
  convert h_sum ( C_coset'' i ) using 1;
  · unfold period_int''; aesop;
  · exact?

/-
Prove that the integer root alpha'' coerces to the field root alpha''.
-/
lemma coe_alpha''_int : (α''_int : L349) = α'' := by
  -- By definition of coercion, we have that the coercion of the integer period_int'' i is equal to the field period'' i.
  have h_coe_period : ∀ i : ZMod 3, (period_int'' i : L349) = period'' i := by
    exact?;
  unfold α''_int α''; aesop;

/-
Prove that the integer root beta'' coerces to the field root beta''.
-/
lemma coe_beta''_int : (β''_int : L349) = β'' := by
  unfold β''_int;
  convert congr_arg ( fun x : L349 => - ( η₀'' - x ) ) ( coe_period_int'' 1 ) using 1;
  simp +decide [ coe_period_int'' ];
  exact?

/-
Prove that the integer root gamma'' coerces to the field root gamma''.
-/
lemma coe_gamma''_int : (γ''_int : L349) = γ'' := by
  -- By definition of coercion, we can rewrite the goal using the definitions of γ''_int and γ''.
  simp [γ''_int, γ''];
  convert congr_arg₂ ( · - · ) ( coe_period_int'' 0 ) ( coe_period_int'' 2 ) using 1

/-
Relate the index of N to the value of c'' N being s1''.
-/
lemma ind_N_eq_1_iff_c_eq_s1'' (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 349) :
  ind'' (N : ZMod 349) = 1 ↔ c'' N = s1'' := by
    -- By definition of $c''$, we know that $c'' N = (N : ZMod 349) ^ ((349 - 1) / 3)$.
    have hc'' : c'' N = (N : ZMod 349) ^ 116 := by
      rfl;
    convert ind_spec'' ( N : ZMod 349 ) ( show ( N : ZMod 349 ) ≠ 0 from ?_ ) |> And.right |> And.left using 1
    generalize_proofs at *;
    · simp +decide [ S_s1'', hc'' ];
      intro h; intro h'; simp_all +decide [ ZMod.natCast_eq_zero_iff ] ;
      exact absurd h ( by native_decide );
    · exact?

/-
Relate the index of N to the value of c'' N being s2''.
-/
lemma ind_N_eq_2_iff_c_eq_s2'' (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 349) :
  ind'' (N : ZMod 349) = 2 ↔ c'' N = s2'' := by
    -- By definition of $ind''$, we know that $ind'' (N : ZMod 349) = 2$ if and only if $N \equiv N \pmod{349}$ and $ind'' N = 2$.
    simp [ind''];
    split_ifs <;> simp_all +decide [ S_cubic_res'', S_s1'', S_s2'' ];
    · unfold c'' s2''; simp_all +decide [ ZMod.natCast_eq_zero_iff ] ;
      erw [ inv_eq_one_div, mul_one_div, eq_div_iff ] <;> norm_cast ; simp_all +decide [ ZMod.natCast_eq_zero_iff ];
      erw [ show ( q'' - 1 ) / 3 = 116 by rfl ] ; simp_all +decide [ ← ZMod.natCast_eq_zero_iff ] ;
    · simp_all +decide [ c'' ];
      simp_all +decide [ q'' ];
      native_decide +revert;
    · by_cases h₃ : ( N : ZMod 349 ) = 0 <;> simp_all +decide [ ZMod.natCast_eq_zero_iff ];
      · rw [ Nat.dvd_prime Fact.out ] at h₃ ; aesop;
      · -- Since $N$ is a prime not equal to $349$, $N$ is coprime with $349$, and thus $N^{116} \equiv 1 \pmod{349}$.
        have h_order : (N : ZMod 349) ^ 348 = 1 := by
          have h_order : Nat.gcd N 349 = 1 := by
            exact Nat.Coprime.symm ( Nat.Prime.coprime_iff_not_dvd ( by norm_num ) |>.2 h₃ );
          simpa [ ← ZMod.natCast_eq_natCast_iff ] using Nat.ModEq.pow_totient h_order;
        simp_all +decide [ show ( N : ZMod 349 ) ^ 348 = ( N ^ 116 ) ^ 3 by ring ];
        have h_order : ∀ x : ZMod 349, x ^ 3 = 1 → x = 1 ∨ x = s1'' ∨ x = s2'' := by
          native_decide;
        cases h_order _ ‹_› <;> aesop

/-
Abbreviations for the ring of integers, residue field, and reduction map for q=349.
-/
abbrev 𝓞L349 := 𝓞 L349
def kP349 (P : Ideal 𝓞L349) [P.IsMaximal] := 𝓞L349 ⧸ P
noncomputable instance (P : Ideal 𝓞L349) [P.IsMaximal] : Field (kP349 P) := Ideal.Quotient.field P
def red349 (P : Ideal 𝓞L349) [P.IsMaximal] : 𝓞L349 →+* kP349 P := Ideal.Quotient.mk P

/-
Lift the automorphism sigma349 to the ring of integers.
-/
def sigma_int349 (u : (ZMod 349)ˣ) (x : 𝓞 L349) : 𝓞 L349 := ⟨sigma349 u x, by
  have h_integral : IsIntegral ℤ (x : L349) := x.2
  exact IsIntegral.map (sigma349 u) h_integral⟩

/-
The ring of integers is generated by zeta349.
-/
lemma adjoin_zeta_eq_top349 : Algebra.adjoin ℤ ({ζ349_int} : Set 𝓞L349) = ⊤ := by
  have h_adjoin : IsPrimitiveRoot ζ349_int 349 := by
    have h_primitive : IsPrimitiveRoot (IsCyclotomicExtension.zeta 349 ℚ L349) 349 := by
      convert IsCyclotomicExtension.zeta_spec 349 ℚ L349;
    convert h_primitive using 1;
    ext; simp +decide [ IsPrimitiveRoot.iff_def ] ;
    constructor <;> rintro ⟨ h₁, h₂ ⟩ <;> refine' ⟨ _, _ ⟩ <;> norm_cast at *;
    · exact?;
    · intro l hl; specialize h₂ l; aesop;
    · erw [ ← Subtype.coe_inj ] ; norm_num [ IsCyclotomicExtension.zeta ];
      exact?;
    · intro l hl; specialize h₂ l; simp_all +decide [ ← Subtype.coe_inj ] ;
      convert h₂ _;
      convert congr_arg ( algebraMap (𝓞 L349) L349 ) hl using 1;
  have h_adjoin : IsCyclotomicExtension {349} ℤ (𝓞 L349) := by
    convert IsCyclotomicExtension.zeta_spec 349 ℤ (𝓞 L349) using 1
    generalize_proofs at *; (
    exact iff_of_true ‹_› ( by exact? ))
  generalize_proofs at *; (
  convert h_adjoin.adjoin_primitive_root_eq_top _;
  assumption)

/-
The automorphism sigma_N reduces to the Frobenius map modulo P.
-/
theorem artin_property349 {N : ℕ} [Fact (Nat.Prime N)] (hN : N ≠ 349) (P : Ideal 𝓞L349) [P.IsMaximal] [CharP (kP349 P) N] (x : 𝓞L349) :
  red349 P (sigma_int349 (gal_unit349 N hN) x) = (red349 P x) ^ N := by
    have h_frobenius : ∀ (x : 𝓞L349), (red349 P) (sigma_int349 (gal_unit349 N hN) x) = (red349 P x) ^ N := by
      intro x
      have h_gen : ∀ y : 𝓞L349, y ∈ Algebra.adjoin ℤ ({ζ349_int} : Set 𝓞L349) := by
        exact fun y => by rw [ adjoin_zeta_eq_top349 ] ; exact Algebra.mem_top;
      refine' Algebra.adjoin_induction _ _ _ _ ( h_gen x );
      · -- By definition of sigma_int349, we have sigma_int349 (gal_unit349 N hN) ζ349_int = ζ349_int^N.
        have h_sigma_zeta : sigma_int349 (gal_unit349 N hN) ζ349_int = ζ349_int ^ N := by
          unfold sigma_int349;
          unfold sigma349 gal_unit349;
          erw [ Subtype.mk_eq_mk ];
          simp +decide [ IsCyclotomicExtension.autEquivPow ];
          erw [ PowerBasis.equivOfMinpoly_gen ];
          simp +decide [ IsPrimitiveRoot.powerBasis ];
          erw [ ← Nat.mod_add_div N 349 ] ; norm_num [ pow_add, pow_mul ];
          erw [ show ( ζ349_int : L349 ) ^ 349 = 1 from ?_ ] ; aesop;
          convert IsPrimitiveRoot.pow_eq_one ( IsCyclotomicExtension.zeta_spec 349 ℚ L349 ) using 1;
        aesop;
      · intro r
        simp [sigma_int349];
        have h_frobenius : ∀ (r : ℤ), (red349 P) (algebraMap ℤ (𝓞L349) r) = (r : kP349 P) ^ N := by
          intro r; exact (by
          have h_frobenius : ∀ (r : ℤ), (red349 P) (algebraMap ℤ (𝓞L349) r) = (r : kP349 P) := by
            exact?;
          rw [ h_frobenius, eq_comm ];
          have h_frobenius : ∀ (r : ZMod N), r ^ N = r := by
            exact fun r => by rw [ ZMod.pow_card ] ;
          convert h_frobenius ( r : ZMod N ) using 1;
          norm_cast;
          erw [ ZMod.intCast_eq_intCast_iff ];
          exact?);
        convert h_frobenius r using 1;
      · intro x y hx hy hx' hy'; simp_all +decide [ ← map_mul, ← map_add ] ;
        convert congr_arg₂ ( · + · ) hx' hy' using 1 <;> ring;
        · convert map_add _ _ _ using 1;
          rotate_left 1;
          exact inferInstance;
          · infer_instance;
          · unfold sigma_int349; aesop;
        · rw [ ← add_pow_char ];
          rw [ map_add ];
      · simp +contextual [ *, mul_pow ];
        intro x y hx hy; rw [ ← hx, ← hy ] ; simp +decide [ ← map_mul ] ;
        unfold sigma_int349; aesop;
    exact h_frobenius x

/-
The Frobenius automorphism permutes the Gaussian periods by shifting their index by ind(N).
-/
lemma sigma_period'' (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 349) (i : ZMod 3) :
  sigma349 (gal_unit349 N hN) (period'' i) = period'' (i + ind'' (N : ZMod 349)) := by
    -- By definition of the automorphism, it permutes the Gaussian periods by shifting their index by ind(N).
    have h_aut_perm : ∀ x : ZMod 349, x ≠ 0 → sigma349 (gal_unit349 N hN) (ζ349 ^ (x.val : ℕ)) = ζ349 ^ ((x * N : ZMod 349).val : ℕ) := by
      intro x hx_ne_zero
      have h_sigma_zeta : sigma349 (gal_unit349 N hN) (ζ349) = ζ349 ^ (N : ZMod 349).val := by
        have h_sigma_zeta : ∀ u : (ZMod 349)ˣ, (IsCyclotomicExtension.autEquivPow L349 (Polynomial.cyclotomic.irreducible_rat (n := 349) (by norm_num))).symm u (IsCyclotomicExtension.zeta 349 ℚ L349) = (IsCyclotomicExtension.zeta 349 ℚ L349) ^ (u.val.val : ℕ) := by
          intro u
          simp [IsCyclotomicExtension.autEquivPow];
          rw [ PowerBasis.equivOfMinpoly_apply ];
          convert ( IsPrimitiveRoot.powerBasis ℚ ( show IsPrimitiveRoot ( IsCyclotomicExtension.zeta 349 ℚ L349 ) 349 from ?_ ) ).lift_gen _ _ using 1;
          exact?;
        convert h_sigma_zeta ( gal_unit349 N hN ) using 1;
      convert congr_arg ( · ^ x.val ) h_sigma_zeta using 1 <;> norm_num [ pow_mul', mul_comm ];
      rw [ ← pow_mul, mul_comm, ZMod.val_mul ];
      rw [ ← Nat.mod_add_div ( N % 349 * x.val ) 349, pow_add, pow_mul ] ; norm_num [ pow_mul, pow_succ ];
      have h_zeta_order : ζ349 ^ 349 = 1 := by
        exact IsPrimitiveRoot.pow_eq_one ( IsCyclotomicExtension.zeta_spec 349 ℚ L349 );
      simp_all +decide [ pow_succ, mul_assoc ];
    -- By definition of the automorphism, it permutes the Gaussian periods by shifting their index by ind(N). Hence, we can rewrite the sum.
    have h_sum_perm : ∑ x ∈ C_coset'' i, sigma349 (gal_unit349 N hN) (ζ349 ^ (x.val : ℕ)) = ∑ x ∈ C_coset'' (i + ind'' (N : ZMod 349)), ζ349 ^ (x.val : ℕ) := by
      apply Finset.sum_bij (fun x hx => (x * N : ZMod 349));
      · intro x hx
        simp [C_coset''] at hx ⊢
        generalize_proofs at *;
        have h_ind_mul : ∀ x y : ZMod 349, x ≠ 0 → y ≠ 0 → ind'' (x * y) = ind'' x + ind'' y := by
          exact?
        generalize_proofs at *; (
        have hN_ne_zero : (N : ZMod 349) ≠ 0 := by
          exact?
        generalize_proofs at *; (
        exact ⟨ ⟨ hx.1, hN_ne_zero ⟩, by rw [ h_ind_mul x N hx.1 hN_ne_zero, hx.2 ] ⟩));
      · intro a₁ ha₁ a₂ ha₂ h_eq
        have h_inv : (N : ZMod 349) ≠ 0 := by
          exact?
        have h_inv_mul : (a₁ : ZMod 349) = (a₂ : ZMod 349) := by
          haveI := Fact.mk ( by norm_num : Nat.Prime 349 ) ; exact mul_right_cancel₀ h_inv h_eq;
        exact h_inv_mul;
      · intro b hb
        use b * (N : ZMod 349)⁻¹;
        have h_inv : (N : ZMod 349) ≠ 0 := by
          exact?;
        have h_ind : ind'' (b * (N : ZMod 349)⁻¹) = ind'' b - ind'' (N : ZMod 349) := by
          have h_ind : ind'' (b * (N : ZMod 349)⁻¹) = ind'' b + ind'' ((N : ZMod 349)⁻¹) := by
            apply ind_mul'';
            · exact Finset.mem_filter.mp hb |>.2.1;
            · haveI := Fact.mk ( by norm_num : Nat.Prime 349 ) ; exact inv_ne_zero h_inv;
          have h_ind_inv : ind'' ((N : ZMod 349)⁻¹) = -ind'' (N : ZMod 349) := by
            exact?;
          rw [h_ind, h_ind_inv]
          ring;
        unfold C_coset'' at *; aesop;
      · exact fun x hx => h_aut_perm x <| Finset.mem_filter.mp hx |>.2.1;
    convert h_sum_perm using 1;
    · rw [ period_eq_sum_C_coset'' ];
      rw [ map_sum ];
    · exact?

/-
If c'' N = s1'', then sigma_N(alpha'') = gamma''.
-/
lemma sigma_alpha_eq_gamma_if_s1'' (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 349) (h : c'' N = s1'') :
  sigma_int349 (gal_unit349 N hN) α''_int = γ''_int := by
    have h_sigma_period : sigma349 (gal_unit349 N hN) α'' = γ'' := by
      have h_sigma_period : sigma349 (gal_unit349 N hN) (period'' 1) = period'' 2 ∧ sigma349 (gal_unit349 N hN) (period'' 2) = period'' 0 ∧ sigma349 (gal_unit349 N hN) (period'' 0) = period'' 1 := by
        have h_sigma_period : sigma349 (gal_unit349 N hN) (period'' 1) = period'' (1 + ind'' (N : ZMod 349)) ∧ sigma349 (gal_unit349 N hN) (period'' 2) = period'' (2 + ind'' (N : ZMod 349)) ∧ sigma349 (gal_unit349 N hN) (period'' 0) = period'' (0 + ind'' (N : ZMod 349)) := by
          exact ⟨ sigma_period'' N hN 1, sigma_period'' N hN 2, sigma_period'' N hN 0 ⟩;
        have h_ind : ind'' (N : ZMod 349) = 1 := by
          exact?;
        simp_all +decide [ ZMod ];
      convert congr_arg₂ ( fun x y : L349 => - ( x - y ) ) h_sigma_period.1 h_sigma_period.2.1 using 1;
      rw [ show α'' = - ( period'' 1 - period'' 2 ) by rfl ] ; norm_num;
    refine' Subtype.ext _;
    convert h_sigma_period using 1;
    · convert congr_arg ( sigma349 ( gal_unit349 N hN ) ) ( coe_alpha''_int ) using 1;
    · exact coe_gamma''_int

/-
If c'' N = s2'', then sigma_N(alpha'') = beta''.
-/
lemma sigma_alpha_eq_beta_if_s2'' (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 349) (h : c'' N = s2'') :
  sigma_int349 (gal_unit349 N hN) α''_int = β''_int := by
    -- By definition of $c''$, we know that $c'' N = s2''$ implies $ind'' (N : ZMod 349) = 2$.
    have h_ind_N_eq_2 : ind'' (N : ZMod 349) = 2 := by
      exact?;
    -- By definition of $sigma_int349$, we know that $sigma_int349 (gal_unit349 N hN) (α''_int) = σ_N (α''_int)$.
    have h_sigma_int349_alpha : sigma_int349 (gal_unit349 N hN) α''_int = - (sigma_int349 (gal_unit349 N hN) (period_int'' 1) - sigma_int349 (gal_unit349 N hN) (period_int'' 2)) := by
      unfold sigma_int349 α''_int; norm_num;
      exact?;
    -- By definition of $sigma_int349$, we know that $sigma_int349 (gal_unit349 N hN) (period_int'' i) = period_int'' (i + ind'' (N : ZMod 349))$.
    have h_sigma_int349_period : ∀ i : ZMod 3, sigma_int349 (gal_unit349 N hN) (period_int'' i) = period_int'' (i + ind'' (N : ZMod 349)) := by
      intro i
      have h_sigma_int349_period_i : sigma_int349 (gal_unit349 N hN) (period_int'' i) = sigma349 (gal_unit349 N hN) (period'' i) := by
        exact congr_arg ( fun x : L349 => x ) ( coe_period_int'' i ) ▸ rfl;
      have h_sigma_int349_period_i : sigma349 (gal_unit349 N hN) (period'' i) = period'' (i + ind'' (N : ZMod 349)) := by
        exact?;
      have h_sigma_int349_period_i : period'' (i + ind'' (N : ZMod 349)) = (period_int'' (i + ind'' (N : ZMod 349)) : L349) := by
        convert coe_period_int'' ( i + ind'' ( N : ZMod 349 ) ) |> Eq.symm using 1;
      exact Subtype.ext <| by aesop;
    simp_all +decide [ ZMod ];
    unfold β''_int; ring;

/-
Final result for q=349: Frobenius action on alpha'' depends on c'' N.
-/
theorem final_result_349 {N : ℕ} [Fact (Nat.Prime N)] (hN : N ≠ 349) (P : Ideal 𝓞L349) [P.IsMaximal] [CharP (kP349 P) N] :
  (c'' N = s1'' → (red349 P α''_int) ^ N = red349 P γ''_int) ∧
  (c'' N = s2'' → (red349 P α''_int) ^ N = red349 P β''_int) := by
    apply And.intro;
    · intro h
      have h_sigma : sigma_int349 (gal_unit349 N hN) α''_int = γ''_int := by
        convert sigma_alpha_eq_gamma_if_s1'' N hN h using 1;
      rw [ ← h_sigma, artin_property349 ];
    · -- Apply the artin property349 theorem to get the reduction.
      have h_reduction : red349 P (sigma_int349 (gal_unit349 N hN) α''_int) = (red349 P α''_int) ^ N := by
        convert artin_property349 hN P α''_int using 1;
      intro h; rw [ ← h_reduction, sigma_alpha_eq_beta_if_s2'' N hN h ] ;

/-
Define the polynomial f'' = X^3 - 349X - 349.
-/
def f_poly'' : Polynomial L349 := X^3 - 349*X - 349

/-
Prove that alpha'' is a root of f''.
-/
theorem alpha_root'' : (f_poly'').eval α'' = 0 := by
  -- By definition of $f_poly''$, we know that $f_poly''.eval α'' = α''^3 - 349 * α'' - 349$.
  simp [f_poly''];
  field_simp;
  rw [ show α'' ^ 2 = 232 - 13 * η₀'' + 4 * η₂'' + 7 * η₁'' from ?_, show η₀'' = -1 - η₁'' - η₂'' from ?_ ] <;> ring;
  · rw [ show α'' = - ( η₂'' - η₁'' ) by rfl ] ; ring;
    rw [ show η₂'' ^ 2 = 116 + 36 * η₀'' + 37 * η₁'' + 42 * η₂'' by
          convert eta_mul_table''.2.2.1 using 1, show η₁'' ^ 2 = 116 + 37 * η₀'' + 42 * η₁'' + 36 * η₂'' by
                                                                            -- Apply the lemma eta_mul_table'' to conclude the proof.
                                                                            apply (eta_mul_table'' |>.2.1), show η₂'' * η₁'' = 43 * η₀'' + 36 * η₁'' + 37 * η₂'' by
                                                                                                                                              exact eta_mul_table_corrected''.2.2.2.2.2.symm ▸ by ring; ] ; ring;
    -- By definition of η₀'', η₁'', and η₂'', we know that their sum is -1.
    have h_sum : η₀'' + η₁'' + η₂'' = -1 := by
      exact?;
    linear_combination -h_sum;
  · exact eq_add_of_sub_eq' ( by linear_combination' sum_eta'' );
  · convert alpha_sq_eq'' using 1 ; ring!

/-
Check if f_poly'' is defined.
-/
#check f_poly''

/-
Check if the main declarations are present.
-/
#check f_poly''
#check α''
#check alpha_root''
#check final_result_349

/-
Prove that alpha'' is a root of f''.
-/
theorem alpha_is_root_of_f : (f_poly'').eval α'' = 0 := by
  -- Substitute α'' into the polynomial f_poly'' and simplify using the known relation.
  convert alpha_root'' using 1
