/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4b146ef4-58ea-40bb-8c15-943459eb4abb

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have successfully formalized and proved the Dream Theorem for q = 7489.
The file defines the cyclotomic field K = Q(zeta_7489), the ring of integers Ok, and the periods alpha, beta, gamma.
We proved the Artin property for the extension K/Q and determined the action of the Frobenius automorphism on the periods.
Finally, we proved `final_result_7489`, which states that for a prime N != 7489, the value of the character c(N) determines the image of alpha under the Frobenius map, confirming the Dream Theorem.
All proofs are complete with no sorrys.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 8011b3b0-5b9d-44a9-a431-7da2e7415d10

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have successfully proved the Dream Theorem for the prime $q = 1567$.
The proof follows the structure of prior proofs for $q = 877, 937, 1063, 1129$.
We defined the field $K = \mathbb{Q}(\zeta_{1567})$, the ring of integers $\mathcal{O}_K$, and the Gaussian periods $\eta_0, \eta_1, \eta_2$.
We defined the period differences $\alpha, \beta, \gamma$ with the appropriate sign convention.
We established the algebraic relations between $\alpha, \beta, \gamma$ using the period equation and computation.
We proved the Artin property for the extension $K/\mathbb{Q}$.
We characterized the cosets $C_1, C_2$ using the cubic character $\chi$.
Finally, we proved `final_result_1567`, which states that for a prime $N \neq 1567$, the Frobenius action on $\alpha$ is determined by the value of the cubic character $\chi(N)$.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ff94a4ce-df04-43b6-855b-2c35922c8831

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the cyclotomic field $K = \mathbb{Q}(\zeta_{1129})$, the ring of integers $\mathcal{O}_K$, and the Gaussian periods $\eta_0, \eta_1, \eta_2$. We define the period differences $\alpha, \beta, \gamma$ with the correct sign convention. We prove the Artin property for $\mathcal{O}_K$ and use it to prove the Dream Theorem for $q = 1129$, which relates the Frobenius action on $\alpha$ to the cubic character $c(N)$. The proof assumes the period equation for $\alpha$ as requested.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 49ab742d-7e60-49a0-9635-aa76ebf271b7

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Proof of the Dream Theorem for q = 1063.

We define the cyclotomic field K = Q(zeta_1063), the ring of integers Ok, and the Gaussian periods.
We identify a generator g = 6 such that the cubic character c(g) = s2 = 719.
We define the roots alpha, beta, gamma using this generator and the standard sign convention.
We prove the Artin property for the extension.
We prove the global permutation of roots under the Galois group.
Finally, we prove the Dream Theorem:
If c(N) = s1, then alpha^N = gamma mod P.
If c(N) = s2, then alpha^N = beta mod P.
This relies on the period equation alpha^3 = 1063*alpha + 1063, which is added as a hypothesis.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f1e85200-2efb-4b56-a019-1c5b75f4b05f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Proof of the Dream Theorem for q = 937.

We define the cyclotomic field K = Q(zeta_937), its ring of integers Ok, and the Gaussian periods.
We identify a generator g = 7 for which the cubic character values match the s1/s2 definitions.
We prove the Artin property for the extension K/Q.
We prove the main theorem `dream_theorem_937` which states that for a prime N != 937:
- If c(N) = s1, then alpha^N = gamma mod P.
- If c(N) = s2, then alpha^N = beta mod P.
This assumes the period equation `alpha^3 = 937*alpha + 937`.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b08f138a-15ed-40a2-a0c0-b8f4ce6443e1

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the cyclotomic field K for q = 877 and the Gaussian periods. We prove the Dream Theorem for q = 877, which states that the Frobenius automorphism maps the period difference α to β or γ depending on the cubic character of the prime N modulo 877. The proof relies on the Artin property of the Frobenius map and the explicit calculation of the Galois action on the periods.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f1f9f2e4-1b7a-4d8c-ad24-d62d489ea7c9

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: a7add749-96ca-48e2-a89d-fbb216918bc3

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 22a1ac83-9054-4f97-9a50-f0ea72bded01

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e6ee589a-f550-42ef-89e5-1fd2afd7fa5e

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We defined the constants s1, s2, and the value c(N). We proved lemmas characterizing the cosets C1 and C2 in terms of the 12th power residue symbol (which relates to c(N)). Finally, we proved the main theorem `final_result` which establishes the Frobenius action on alpha (i.e., alpha^N) in terms of beta and gamma, depending on the value of c(N). The proof utilizes the `explicit_frobenius` theorem and the algebraic relations between alpha, beta, and gamma.
-/

/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 939f55fb-68a7-4ef0-bca3-475f675055ca

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes the proof of the Frobenius Orientation conjecture for q=37.
It defines the cyclotomic field K = Q(zeta_37), the Gaussian periods, and the cubic roots.
It proves the cyclic algebraic relations between these roots and establishes the global Galois action.
It descends to the residue field modulo a prime P lying over N != 37, proving the Artin property.
Finally, it derives the explicit Frobenius action on the reduction of alpha modulo P.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section












/-
Definitions for q = 7489, s1, s2, and the character c(N).
-/
def q7489 : ℕ := 7489

instance fact_prime_7489 : Fact (Nat.Prime 7489) := ⟨by native_decide⟩

def s1_7489 : ZMod 7489 := 2467
def s2_7489 : ZMod 7489 := 5021
def c7489 (N : ℕ) : ZMod 7489 := (N : ZMod 7489)^2496

/-
Find a primitive root g modulo 7489 such that g^((q-1)/3) = s2.
-/
def find_g_7489 : IO Unit := do
  let q := 7489
  let s2 := 5021
  let c (n : Nat) := (n : Nat) ^ 2496 % q
  let order := q - 1
  -- 7488 = 16 * 468 = 16 * 4 * 117 = 64 * 9 * 13 = 2^6 * 3^2 * 13
  let factors := [2, 3, 13]
  
  for g in [2:100] do
    let mut is_prim := true
    for f in factors do
      if (g ^ (order / f)) % q == 1 then
        is_prim := false
        break
    
    if is_prim then
      if c g == s2 then
        IO.println s!"Found good generator: {g}"
        return
  
  IO.println "No generator found in range"

#eval find_g_7489

/-
Definitions of the field K, zeta, generator g, and the cubic residue cosets H, C1, C2.
-/
abbrev K7489 := CyclotomicField 7489 ℚ

noncomputable def zeta7489 : K7489 := IsCyclotomicExtension.zeta 7489 ℚ K7489

def g7489 : ZMod 7489 := 7

def H7489 : Finset (ZMod 7489) := ((Finset.univ : Finset (ZMod 7489)).filter (fun x => x ≠ 0)).image (fun x => x^3)

def C1_7489 : Finset (ZMod 7489) := H7489.image (fun x => g7489 * x)

def C2_7489 : Finset (ZMod 7489) := H7489.image (fun x => g7489^2 * x)

/-
Definitions of the periods eta and the differences alpha', beta', gamma'.
-/
open scoped BigOperators

noncomputable def eta7489 (S : Finset (ZMod 7489)) : K7489 := ∑ x ∈ S, zeta7489^(x.val)

noncomputable def eta0_7489 := eta7489 H7489
noncomputable def eta1_7489 := eta7489 C1_7489
noncomputable def eta2_7489 := eta7489 C2_7489

noncomputable def alpha_prime_7489 := eta0_7489 - eta1_7489
noncomputable def beta_prime_7489 := eta1_7489 - eta2_7489
noncomputable def gamma_prime_7489 := eta2_7489 - eta0_7489

/-
Definition of the ring of integers and irreducibility of the cyclotomic polynomial.
-/
abbrev Ok7489 := NumberField.RingOfIntegers K7489

theorem h_irr_7489 : Irreducible (Polynomial.cyclotomic 7489 ℚ) := by
  exact Polynomial.cyclotomic.irreducible_rat <| by norm_num;

/-
Automorphisms of the field and integrality of zeta.
-/
noncomputable def sigma7489 (n : (ZMod 7489)ˣ) : K7489 ≃ₐ[ℚ] K7489 :=
  (IsCyclotomicExtension.autEquivPow K7489 h_irr_7489).symm n

theorem zeta_isIntegral_7489 : IsIntegral ℤ zeta7489 := by
  refine' ⟨ Polynomial.X ^ 7489 - 1, _, _ ⟩;
  · exact Polynomial.monic_X_pow_sub_C _ ( by norm_num );
  · norm_num;
    convert sub_eq_zero.mpr <| IsPrimitiveRoot.pow_eq_one _;
    convert IsCyclotomicExtension.zeta_spec 7489 ℚ K7489

/-
Integral definitions of zeta, sigma, eta, and the differences.
-/
def zeta_int7489 : Ok7489 := ⟨zeta7489, zeta_isIntegral_7489⟩

noncomputable def sigma_int7489 (n : (ZMod 7489)ˣ) : Ok7489 ≃ₐ[ℤ] Ok7489 :=
  (NumberField.RingOfIntegers.mapAlgEquiv (sigma7489 n)).restrictScalars ℤ

noncomputable def eta_int7489 (S : Finset (ZMod 7489)) : Ok7489 := ∑ x ∈ S, zeta_int7489^(x.val)

noncomputable def eta0_int7489 := eta_int7489 H7489
noncomputable def eta1_int7489 := eta_int7489 C1_7489
noncomputable def eta2_int7489 := eta_int7489 C2_7489

noncomputable def alpha_prime_int7489 := eta0_int7489 - eta1_int7489
noncomputable def beta_prime_int7489 := eta1_int7489 - eta2_int7489
noncomputable def gamma_prime_int7489 := eta2_int7489 - eta0_int7489

/-
Definitions of the signed periods alpha, beta, gamma.
-/
open Classical

noncomputable def sign_7489 : ℤ :=
  if alpha_prime_int7489 * beta_prime_int7489 * gamma_prime_int7489 = (7489 : Ok7489) then 1 else -1

noncomputable def alpha_int7489 := (sign_7489 : Ok7489) * alpha_prime_int7489
noncomputable def beta_int7489 := (sign_7489 : Ok7489) * beta_prime_int7489
noncomputable def gamma_int7489 := (sign_7489 : Ok7489) * gamma_prime_int7489

noncomputable def alpha7489_field : K7489 := alpha_int7489
noncomputable def beta7489_field : K7489 := beta_int7489
noncomputable def gamma7489_field : K7489 := gamma_int7489

/-
Helper function to find coefficients for the algebraic relations.
-/
def find_coeffs_7489 : IO Unit := do
  let q := 7489
  let a := 173
  -- Find p = k*q + 1
  let mut p := 0
  for k in [2:200] do
    let cand := k * q + 1
    if Nat.Prime cand then
      p := cand
      break
  
  if p == 0 then
    IO.println "No prime found"
    return

  IO.println s!"Using prime p = {p}"

  -- Find element of order q
  let mut g_p := 0
  for g in [2:p] do
    let zeta := (g : Nat) ^ ((p - 1) / q) % p
    if zeta != 1 then
      g_p := g
      break
  
  let zeta := (g_p : Nat) ^ ((p - 1) / q) % p
  IO.println s!"zeta = {zeta}"

  -- Cosets of cubic residues mod q
  -- g_q = 7
  let g_q := 7
  let mut H : List Nat := []
  let mut x := 1
  let g_q_3 := (g_q * g_q * g_q) % q
  for _ in [0:(q-1)/3] do
    H := x :: H
    x := (x * g_q_3) % q
  
  let C1 := H.map (fun h => (h * g_q) % q)
  let C2 := H.map (fun h => (h * g_q * g_q) % q)

  -- Periods mod p
  let sum_zeta (S : List Nat) : Nat :=
    S.foldl (fun acc h => (acc + (zeta ^ h) % p) % p) 0
  
  let eta0 := sum_zeta H
  let eta1 := sum_zeta C1
  let eta2 := sum_zeta C2

  -- Differences
  let alpha_prime := (eta0 + p - eta1) % p
  let beta_prime := (eta1 + p - eta2) % p
  let gamma_prime := (eta2 + p - eta0) % p

  -- Check sign convention
  let prod := (alpha_prime * beta_prime) % p * gamma_prime % p
  let q_mod_p := q % p
  
  let mut alpha := 0
  let mut beta := 0
  let mut gamma := 0

  if prod == q_mod_p then
    alpha := alpha_prime
    beta := beta_prime
    gamma := gamma_prime
    IO.println "Sign convention: positive"
  else
    alpha := (p - alpha_prime) % p
    beta := (p - beta_prime) % p
    gamma := (p - gamma_prime) % p
    IO.println "Sign convention: negative"

  -- Solve 173 * beta = c0 + c1 * alpha + c2 * alpha^2 mod p
  let sub (x y : Nat) := (x + p - y) % p
  let mul (x y : Nat) := (x * y) % p
  let add (x y : Nat) := (x + y) % p
  let pow (x n : Nat) := x ^ n % p
  let inv (x : Nat) := x ^ (p - 2) % p

  let det := mul (sub beta alpha) (mul (sub gamma alpha) (sub gamma beta))
  let det_inv := inv det

  let rhs0 := mul 173 beta
  let rhs1 := mul 173 gamma
  let rhs2 := mul 173 alpha

  -- Solve for c0, c1, c2
  -- c0
  let term0 := mul rhs0 (sub (mul beta (mul gamma gamma)) (mul gamma (mul beta beta)))
  let term1 := mul rhs1 (sub (mul gamma (mul alpha alpha)) (mul alpha (mul gamma gamma)))
  let term2 := mul rhs2 (sub (mul alpha (mul beta beta)) (mul beta (mul alpha alpha)))
  let c0 := mul (add term0 (add term1 term2)) det_inv

  -- c1
  let term0_1 := mul 1 (sub (mul rhs1 (mul gamma gamma)) (mul rhs2 (mul beta beta)))
  let term1_1 := mul 1 (sub (mul rhs2 (mul alpha alpha)) (mul rhs0 (mul gamma gamma)))
  let term2_1 := mul 1 (sub (mul rhs0 (mul beta beta)) (mul rhs1 (mul alpha alpha)))
  let c1 := mul (add term0_1 (add term1_1 term2_1)) det_inv

  -- c2
  let term0_2 := mul 1 (sub (mul beta rhs2) (mul gamma rhs1))
  let term1_2 := mul 1 (sub (mul gamma rhs0) (mul alpha rhs2))
  let term2_2 := mul 1 (sub (mul alpha rhs1) (mul beta rhs0))
  let c2 := mul (add term0_2 (add term1_2 term2_2)) det_inv

  let to_signed (x : Nat) : Int :=
    if x > p / 2 then (x : Int) - p else x

  IO.println s!"Coefficients for beta: c0={to_signed c0}, c1={to_signed c1}, c2={to_signed c2}"
  
  -- Also for gamma
  let rhs0_g := mul 173 gamma
  let rhs1_g := mul 173 alpha
  let rhs2_g := mul 173 beta

  let term0_g := mul rhs0_g (sub (mul beta (mul gamma gamma)) (mul gamma (mul beta beta)))
  let term1_g := mul rhs1_g (sub (mul gamma (mul alpha alpha)) (mul alpha (mul gamma gamma)))
  let term2_g := mul rhs2_g (sub (mul alpha (mul beta beta)) (mul beta (mul alpha alpha)))
  let d0 := mul (add term0_g (add term1_g term2_g)) det_inv

  let term0_1g := mul 1 (sub (mul rhs1_g (mul gamma gamma)) (mul rhs2_g (mul beta beta)))
  let term1_1g := mul 1 (sub (mul rhs2_g (mul alpha alpha)) (mul rhs0_g (mul gamma gamma)))
  let term2_1g := mul 1 (sub (mul rhs0_g (mul beta beta)) (mul rhs1_g (mul alpha alpha)))
  let d1 := mul (add term0_1g (add term1_1g term2_1g)) det_inv

  let term0_2g := mul 1 (sub (mul beta rhs2_g) (mul gamma rhs1_g))
  let term1_2g := mul 1 (sub (mul gamma rhs0_g) (mul alpha rhs2_g))
  let term2_2g := mul 1 (sub (mul alpha rhs1_g) (mul beta rhs0_g))
  let d2 := mul (add term0_2g (add term1_2g term2_2g)) det_inv

  IO.println s!"Coefficients for gamma: d0={to_signed d0}, d1={to_signed d1}, d2={to_signed d2}"

#eval find_coeffs_7489

/-
Assumptions for the Dream Theorem (algebraic relations) and helper definitions for N mod q and the character chi.
-/
def DreamAssumptions_7489 : Prop :=
  alpha_int7489^3 = 7489 * alpha_int7489 + 7489 ∧
  alpha_int7489 * beta_int7489 * gamma_int7489 = 7489 ∧
  173 * beta_int7489 = 3 * alpha_int7489^2 - 91 * alpha_int7489 - 14978 ∧
  173 * gamma_int7489 = -3 * alpha_int7489^2 + 82 * alpha_int7489 + 14978

def N_mod_7489 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 7489) : (ZMod 7489)ˣ :=
  ZMod.unitOfCoprime N (Nat.Coprime.symm ((Nat.coprime_primes (by norm_num) (Fact.out)).mpr hN.symm))

def chi7489 (x : ZMod 7489) : ZMod 7489 := x ^ 2496

/-
Lemma: sigma_n(zeta) = zeta^n.
-/
lemma sigma_int_zeta_pow_7489 (n : (ZMod 7489)ˣ) :
  sigma_int7489 n zeta_int7489 = zeta_int7489 ^ (n : ZMod 7489).val := by
    unfold sigma_int7489;
    unfold sigma7489;
    erw [ Subtype.mk_eq_mk ] ; norm_num;
    erw [ PowerBasis.equivOfMinpoly_gen ];
    rfl

/-
The Artin property for zeta: sigma_N(zeta) = zeta^N mod P.
-/
theorem artin_property_zeta_7489 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 7489) (P : Ideal Ok7489) [P.IsPrime] (hP : P.LiesOver (Ideal.span {(N : ℤ)})) :
  Ideal.Quotient.mk P (sigma_int7489 (N_mod_7489 N hN) zeta_int7489) = (Ideal.Quotient.mk P zeta_int7489)^N := by
    -- By definition of $sigma$, we know that $sigma_N(zeta) = zeta^N$.
    have h_sigma_zeta : sigma_int7489 (N_mod_7489 N hN) zeta_int7489 = zeta_int7489 ^ (N_mod_7489 N hN : ZMod 7489).val := by
      exact?;
    -- Since $N$ is coprime to $7489$, we have $zeta^{N \mod 7489} = zeta^N$ in the quotient ring.
    have h_exp : (zeta_int7489 : Ok7489) ^ (N_mod_7489 N hN : ZMod 7489).val = (zeta_int7489 : Ok7489) ^ N := by
      have h_exp : (zeta_int7489 : Ok7489) ^ 7489 = 1 := by
        have h_exp : zeta7489 ^ 7489 = 1 := by
          exact IsCyclotomicExtension.zeta_pow _ _ _;
        exact Subtype.ext h_exp;
      -- Since $N$ is coprime to $7489$, we have $N \mod 7489 = N$.
      have h_mod : (N_mod_7489 N hN : ZMod 7489).val = N % 7489 := by
        unfold N_mod_7489; aesop;
      rw [ h_mod, ← Nat.mod_add_div N 7489, pow_add, pow_mul ] ; aesop;
    aesop

/-
Zeta is a primitive 7489-th root of unity.
-/
theorem zeta_isPrimitiveRoot_7489 : IsPrimitiveRoot zeta7489 7489 := by
  convert IsCyclotomicExtension.zeta_spec 7489 ℚ K7489 using 1

/-
The ring of integers is generated by zeta.
-/
theorem Ok7489_eq_adjoin : (⊤ : Subalgebra ℤ Ok7489) = Algebra.adjoin ℤ {zeta_int7489} := by
  -- Apply the theorem that states the ring of integers is generated by any primitive root of unity.
  have h_gen : Algebra.adjoin ℤ {zeta_int7489} = ⊤ := by
    have h_primitive : IsPrimitiveRoot zeta7489 7489 := by
      exact?
    have h_adjoin : IsCyclotomicExtension {7489} ℤ Ok7489 := by
      infer_instance;
    convert h_adjoin.adjoin_primitive_root_eq_top ( show IsPrimitiveRoot zeta_int7489 7489 from ?_ ) using 1;
    rw [ IsPrimitiveRoot.iff_def ] at *;
    convert h_primitive;
    · erw [ ← Subtype.coe_inj ] ; simp +decide [ zeta_int7489 ];
      exact?;
    · erw [ ← Subtype.coe_inj ] ; norm_num [ zeta_int7489 ];
      exact?;
  exact h_gen.symm

/-
The Artin property holds for all elements of the ring of integers.
-/
theorem artin_property_7489 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 7489) (P : Ideal Ok7489) [P.IsPrime] (hP : P.LiesOver (Ideal.span {(N : ℤ)})) (x : Ok7489) :
  Ideal.Quotient.mk P (sigma_int7489 (N_mod_7489 N hN) x) = (Ideal.Quotient.mk P x)^N := by
    have h_sigma_pow : ∀ x : Ok7489, Ideal.Quotient.mk P (sigma_int7489 (N_mod_7489 N hN) x) = (Ideal.Quotient.mk P x)^N := by
      intro x
      have h_gen : x ∈ Algebra.adjoin ℤ {zeta_int7489} := by
        have h_gen : (⊤ : Subalgebra ℤ Ok7489) = Algebra.adjoin ℤ {zeta_int7489} := by
          exact?;
        exact h_gen ▸ Algebra.mem_top
      refine' Algebra.adjoin_induction _ _ _ _ h_gen <;> norm_num +zetaDelta at *;
      · convert artin_property_zeta_7489 N hN P hP using 1;
      · intro r; exact (by
        erw [ Ideal.Quotient.eq ] ; norm_num [ Ideal.mem_span_singleton ];
        have h_div : ↑N ∣ (r : ℤ) - r ^ N := by
          haveI := Fact.mk ( Fact.out : Nat.Prime N ) ; simp +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ] ;
        obtain ⟨ k, hk ⟩ := h_div;
        convert P.mul_mem_right ( k : Ok7489 ) ( hP.1 ▸ Ideal.mem_span_singleton_self ( N : ℤ ) ) using 1 ; norm_cast ; aesop);
      · intro x y hx hy hx' hy';
        have h_exp : (Ideal.Quotient.mk P) (sigma_int7489 (N_mod_7489 N hN) (x + y)) = (Ideal.Quotient.mk P) (sigma_int7489 (N_mod_7489 N hN) x + sigma_int7489 (N_mod_7489 N hN) y) := by
          exact congr_arg _ ( map_add _ _ _ );
        have h_exp : (Ideal.Quotient.mk P) ((x + y) ^ N) = (Ideal.Quotient.mk P) (x ^ N + y ^ N) := by
          have h_exp : (x + y) ^ N ≡ x ^ N + y ^ N [SMOD P] := by
            have h_exp : (x + y) ^ N = x ^ N + y ^ N + ∑ i ∈ Finset.Ico 1 N, Nat.choose N i * x ^ i * y ^ (N - i) := by
              rw [ add_pow ];
              rw [ Finset.sum_range_succ, Finset.sum_Ico_eq_sub _ ] <;> norm_num [ mul_assoc, mul_comm, mul_left_comm ];
              · ring;
              · exact Nat.Prime.pos Fact.out;
            have h_exp : ∀ i ∈ Finset.Ico 1 N, Nat.choose N i * x ^ i * y ^ (N - i) ∈ P := by
              intros i hi
              have h_choose : (Nat.choose N i : ℤ) * x ^ i * y ^ (N - i) ∈ P := by
                have h_choose : (Nat.choose N i : ℤ) ∈ Ideal.span {(N : ℤ)} := by
                  exact Ideal.mem_span_singleton.mpr ( mod_cast Nat.dvd_of_mod_eq_zero ( by rw [ Nat.mod_eq_zero_of_dvd ] ; exact Nat.Prime.dvd_choose_self ( Fact.out : Nat.Prime N ) ( by linarith [ Finset.mem_Ico.mp hi ] ) ( by linarith [ Finset.mem_Ico.mp hi ] ) ) )
                have h_choose : (Nat.choose N i : Ok7489) ∈ P := by
                  have h_choose : Ideal.span {(N : ℤ)} ≤ P.comap (algebraMap ℤ Ok7489) := by
                    exact hP.1.le
                  generalize_proofs at *; (
                  exact h_choose ‹_› |> fun h => by simpa using h;)
                generalize_proofs at *; (
                exact P.mul_mem_right _ ( P.mul_mem_right _ h_choose ))
              generalize_proofs at *; (
              convert h_choose using 1
              skip);
            rw [ SModEq ];
            rw [ Submodule.Quotient.eq ];
            exact ‹ ( x + y ) ^ N = x ^ N + y ^ N + ∑ i ∈ Finset.Ico 1 N, ↑ ( N.choose i ) * x ^ i * y ^ ( N - i ) › ▸ by simpa using P.sum_mem fun i hi => h_exp i hi;
          exact?;
        convert congr_arg₂ ( · + · ) hx' hy' using 1;
      · intro x y hx hy hx' hy'; rw [ mul_pow, hx', hy' ] ;
    exact h_sigma_pow x

/-
Multiplicativity of the character chi.
-/
lemma chi7489_mul (x y : ZMod 7489) : chi7489 (x * y) = chi7489 x * chi7489 y := by
  exact mul_pow x y _ |> congr_arg ( fun z => z : ZMod 7489 → ZMod 7489 )

/-
Check the value of chi(g).
-/
def check_chi_values_7489 : IO Unit := do
  let q := 7489
  let s1 := 2467
  let s2 := 5021
  let g := 7
  let chi (n : Nat) := (n : Nat) ^ 2496 % q
  let chig := chi g
  IO.println s!"chi(g) = {chig}"
  if chig == s1 then IO.println "chi(g) = s1"
  else if chig == s2 then IO.println "chi(g) = s2"
  else IO.println "chi(g) is neither"

#eval check_chi_values_7489

/-
Action of sigma on eta sums: sigma_n(sum zeta^x) = sum zeta^(nx).
-/
lemma sigma_eta_7489 (n : (ZMod 7489)ˣ) (S : Finset (ZMod 7489)) :
  sigma_int7489 n (eta_int7489 S) = eta_int7489 (S.image (fun x => (n : ZMod 7489) * x)) := by
    have h_sigma_zeta : sigma_int7489 n zeta_int7489 = zeta_int7489 ^ (n : ZMod 7489).val := by
      exact?;
    unfold eta_int7489; simp +decide [ h_sigma_zeta ] ;
    refine' Finset.sum_congr rfl fun x hx => _;
    rw [ ← pow_mul, ZMod.val_mul ];
    have h_exp : zeta_int7489 ^ 7489 = 1 := by
      have h_exp : zeta7489 ^ 7489 = 1 := by
        exact IsPrimitiveRoot.pow_eq_one ( zeta_isPrimitiveRoot_7489 );
      exact Subtype.ext h_exp;
    rw [ ← Nat.mod_add_div ( ( n : ZMod 7489 ).val * x.val ) 7489, pow_add, pow_mul ] ; aesop

/-
If n is in H, then multiplication by n permutes H, C1, C2 trivially.
-/
lemma action_H_7489 (n : ZMod 7489) (hn : n ∈ H7489) :
  H7489.image (fun x => n * x) = H7489 ∧
  C1_7489.image (fun x => n * x) = C1_7489 ∧
  C2_7489.image (fun x => n * x) = C2_7489 := by
    refine' ⟨ Finset.eq_of_subset_of_card_le ( Finset.image_subset_iff.mpr _ ) _, Finset.eq_of_subset_of_card_le ( Finset.image_subset_iff.mpr _ ) _, Finset.eq_of_subset_of_card_le ( Finset.image_subset_iff.mpr _ ) _ ⟩;
    all_goals push_cast [ H7489, C1_7489, C2_7489 ] at *;
    all_goals push_cast [ Finset.mem_image, Finset.mem_filter ] at *;
    all_goals rcases hn with ⟨ a, ⟨ ha₁, ha₂ ⟩, rfl ⟩;
    all_goals norm_num [ Finset.card_image_of_injective, Function.Injective, ha₂ ];
    · intro b hb;
      exact ⟨ a * b, mul_ne_zero ha₂ hb, by ring ⟩;
    · intro b hb; use a * b; simp +decide [ *, mul_comm, mul_assoc, mul_left_comm ] ;
      ring;
    · intro b hb; use a * b; simp +decide [ *, mul_pow, mul_assoc, mul_comm, mul_left_comm ] ;

/-
If n is in C1, then multiplication by n permutes H -> C1 -> C2 -> H.
-/
lemma action_C1_7489 (n : ZMod 7489) (hn : n ∈ C1_7489) :
  H7489.image (fun x => n * x) = C1_7489 ∧
  C1_7489.image (fun x => n * x) = C2_7489 ∧
  C2_7489.image (fun x => n * x) = H7489 := by
    norm_num [ C1_7489, C2_7489, H7489 ] at *;
    rcases hn with ⟨ a, ha, rfl ⟩;
    refine' ⟨ _, _, _ ⟩ <;> ext x <;> simp +contextual [ Finset.mem_image ];
    · constructor;
      · rintro ⟨ y, hy, rfl ⟩;
        exact ⟨ a * y, mul_ne_zero ha hy, by ring ⟩;
      · rintro ⟨ b, hb, rfl ⟩;
        -- Since $a \neq 0$ and $b \neq 0$, we can find $a_1$ such that $a_1^3 = b^3 / a^3$.
        obtain ⟨a_1, ha_1⟩ : ∃ a_1 : ZMod 7489, a_1^3 = b^3 / a^3 := by
          haveI := Fact.mk ( by norm_num : Nat.Prime 7489 ) ; exact ⟨ b / a, by ring ⟩ ;
        grind;
    · constructor <;> rintro ⟨ b, hb, rfl ⟩;
      · exact ⟨ a * b, mul_ne_zero ha hb, by ring ⟩;
      · -- Let $a_1 = b / a$.
        use b / a;
        grind;
    · constructor <;> intro h;
      · obtain ⟨ b, hb, rfl ⟩ := h;
        refine' ⟨ a * b * g7489, _, _ ⟩ <;> ring_nf at * ; simp_all +decide;
      · obtain ⟨ b, hb, rfl ⟩ := h;
        -- We need to find $a_1$ such that $g7489 * a^3 * (g7489^2 * a_1^3) = b^3$.
        -- This simplifies to $g7489^3 * a^3 * a_1^3 = b^3$, or $(g7489 * a * a_1)^3 = b^3$.
        -- Taking the cube root of both sides, we get $g7489 * a * a_1 = b$.
        suffices h_cube_root : ∃ a_1 : ZMod 7489, g7489 * a * a_1 = b by
          obtain ⟨ a_1, rfl ⟩ := h_cube_root;
          exact ⟨ a_1, by aesop_cat, by ring ⟩;
        have h_inv : ∃ a_1 : ZMod 7489, g7489 * a * a_1 = 1 := by
          have h_inv : IsUnit (g7489 * a) := by
            haveI := Fact.mk ( by native_decide : Nat.Prime 7489 ) ; exact IsUnit.mul ( by native_decide ) ( IsUnit.mk0 _ ha ) ;
          exact h_inv.exists_right_inv;
        exact ⟨ h_inv.choose * b, by linear_combination' h_inv.choose_spec * b ⟩

/-
If n is in C2, then multiplication by n permutes H -> C2 -> C1 -> H.
-/
lemma action_C2_7489 (n : ZMod 7489) (hn : n ∈ C2_7489) :
  H7489.image (fun x => n * x) = C2_7489 ∧
  C1_7489.image (fun x => n * x) = H7489 ∧
  C2_7489.image (fun x => n * x) = C1_7489 := by
    -- Since $n \in C2_7489$, there exists $m \in H7489$ such that $n = g7489^2 * m$.
    obtain ⟨m, hm⟩ : ∃ m ∈ H7489, n = g7489^2 * m := by
      native_decide +revert;
    -- Since multiplication by $m$ (which is in $H7489$) permutes $H7489$, $C1_7489$, and $C2_7489$ trivially, we can simplify the images.
    have h_perm : Finset.image (fun x => m * x) H7489 = H7489 ∧ Finset.image (fun x => m * x) C1_7489 = C1_7489 ∧ Finset.image (fun x => m * x) C2_7489 = C2_7489 := by
      exact ⟨ action_H_7489 m hm.1 |>.1, action_H_7489 m hm.1 |>.2.1, action_H_7489 m hm.1 |>.2.2 ⟩;
    -- Since multiplication by $g7489^2$ permutes $H7489$, $C1_7489$, and $C2_7489$ cyclically, we can simplify the images.
    have h_perm_g : Finset.image (fun x => g7489^2 * x) H7489 = C2_7489 ∧ Finset.image (fun x => g7489^2 * x) C1_7489 = H7489 ∧ Finset.image (fun x => g7489^2 * x) C2_7489 = C1_7489 := by
      native_decide +revert;
    simp +decide only [hm.2, mul_comm, mul_left_comm];
    have h_perm_final : Finset.image (fun x => m * (x * g7489^2)) H7489 = Finset.image (fun x => g7489^2 * x) (Finset.image (fun x => m * x) H7489) ∧ Finset.image (fun x => m * (x * g7489^2)) C1_7489 = Finset.image (fun x => g7489^2 * x) (Finset.image (fun x => m * x) C1_7489) ∧ Finset.image (fun x => m * (x * g7489^2)) C2_7489 = Finset.image (fun x => g7489^2 * x) (Finset.image (fun x => m * x) C2_7489) := by
      simp +decide [ mul_assoc, mul_comm, mul_left_comm, Finset.ext_iff ];
    aesop

/-
The automorphism sigma_n permutes alpha, beta, gamma according to which coset n belongs to.
-/
lemma global_permutation_7489 (n : (ZMod 7489)ˣ) :
  ((n : ZMod 7489) ∈ C1_7489 → sigma_int7489 n alpha_int7489 = beta_int7489) ∧
  ((n : ZMod 7489) ∈ C2_7489 → sigma_int7489 n alpha_int7489 = gamma_int7489) ∧
  ((n : ZMod 7489) ∈ H7489 → sigma_int7489 n alpha_int7489 = alpha_int7489) := by
    refine' ⟨ _, _, _ ⟩;
    · intro hn
      have h_sigma_eta : sigma_int7489 n (eta0_int7489 - eta1_int7489) = eta1_int7489 - eta2_int7489 := by
        have h_sigma_eta : sigma_int7489 n eta0_int7489 = eta1_int7489 ∧ sigma_int7489 n eta1_int7489 = eta2_int7489 := by
          have := action_C1_7489 n.val hn;
          have h_sigma_eta : ∀ S : Finset (ZMod 7489), sigma_int7489 n (eta_int7489 S) = eta_int7489 (S.image (fun x => (n : ZMod 7489) * x)) := by
            exact?;
          exact ⟨ h_sigma_eta H7489 ▸ this.1 ▸ rfl, h_sigma_eta C1_7489 ▸ this.2.1 ▸ rfl ⟩;
        rw [ map_sub, h_sigma_eta.1, h_sigma_eta.2 ];
      unfold alpha_int7489 beta_int7489;
      unfold sign_7489;
      split_ifs <;> simp_all +decide [ mul_assoc ];
      · unfold alpha_prime_int7489 beta_prime_int7489 gamma_prime_int7489 at * ; aesop;
      · unfold alpha_prime_int7489 beta_prime_int7489 gamma_prime_int7489 at * ; aesop;
    · intro hn;
      unfold alpha_int7489 gamma_int7489;
      unfold alpha_prime_int7489 gamma_prime_int7489; simp +decide [ mul_assoc, map_mul ] ;
      unfold eta0_int7489 eta1_int7489 eta2_int7489; simp +decide [ sigma_eta_7489, hn ] ;
      rw [ action_C2_7489 _ hn |>.1, action_C2_7489 _ hn |>.2.1 ] ; norm_num;
    · unfold alpha_int7489;
      unfold alpha_prime_int7489;
      unfold eta0_int7489 eta1_int7489; simp +decide [ mul_sub, sub_mul, sigma_eta_7489 ] ;
      intro hn; rw [ action_H_7489 _ hn |>.1, action_H_7489 _ hn |>.2.1 ] ;

/-
Check if s2^2 = s1 mod q.
-/
def check_s_relation_7489 : IO Unit := do
  let s1 := 2467
  let s2 := 5021
  let q := 7489
  let s2_sq := s2 * s2 % q
  IO.println s!"s2^2 = {s2_sq}"
  if s2_sq == s1 then IO.println "s2^2 = s1" else IO.println "s2^2 != s1"

#eval check_s_relation_7489

/-
n is in C1 iff chi(n) = s2.
-/
lemma mem_C1_iff_chi_eq_s2_7489 (n : ZMod 7489) (hn : n ≠ 0) : n ∈ C1_7489 ↔ chi7489 n = s2_7489 := by
  native_decide +revert

/-
n is in C2 iff chi(n) = s1.
-/
lemma mem_C2_iff_chi_eq_s1_7489 (n : ZMod 7489) (hn : n ≠ 0) : n ∈ C2_7489 ↔ chi7489 n = s1_7489 := by
  native_decide +revert

/-
The Dream Theorem for q = 7489.
-/
theorem final_result_7489 (N : ℕ) [Fact (Nat.Prime N)] (hN : N ≠ 7489) (hN_odd : N % 2 = 1) (hN_a : Nat.Coprime 173 N)
  (P : Ideal Ok7489) [P.IsMaximal] (hP : P.LiesOver (Ideal.span {(N : ℤ)}))
  (h_assum : DreamAssumptions_7489) :
  let alpha_bar := Ideal.Quotient.mk P alpha_int7489
  let beta_bar := Ideal.Quotient.mk P beta_int7489
  let gamma_bar := Ideal.Quotient.mk P gamma_int7489
  (chi7489 N = s1_7489 → alpha_bar ^ N = gamma_bar) ∧
  (chi7489 N = s2_7489 → alpha_bar ^ N = beta_bar) := by
    refine' ⟨ fun h => _, fun h => _ ⟩;
    · have := global_permutation_7489 ( N_mod_7489 N hN );
      have h_coset : (N_mod_7489 N hN : ZMod 7489) ∈ C2_7489 := by
        apply (mem_C2_iff_chi_eq_s1_7489 (N_mod_7489 N hN : ZMod 7489) (by
        simp_all +decide [ ZMod.natCast_eq_zero_iff ])).mpr h;
      rw [ ← this.2.1 h_coset, artin_property_7489 N hN P hP ];
    · have h_sigma_beta : Ideal.Quotient.mk P (sigma_int7489 (N_mod_7489 N hN) alpha_int7489) = Ideal.Quotient.mk P beta_int7489 := by
        have h_sigma_beta : (N_mod_7489 N hN : ZMod 7489) ∈ C1_7489 := by
          apply (mem_C1_iff_chi_eq_s2_7489 (N_mod_7489 N hN) (by
          simp +decide [ ZMod.natCast_eq_zero_iff ])).mpr h;
        exact congr_arg _ ( global_permutation_7489 _ |>.1 h_sigma_beta );
      rw [ ← h_sigma_beta, artin_property_7489 ];
      exact hP